packages:
  - "apps/*"
  - "packages/*"
  - "packages/*/example"
  - "infra/Yoopta-Editor/packages/core/*"
  - "infra/Yoopta-Editor/packages/plugins/*"
  - "infra/Yoopta-Editor/packages/marks"
  - "infra/Yoopta-Editor/packages/themes/*"
