packages:
  - "apps/desktop"
  - "apps/cli"
  - "apps/docs"
  - "apps/web"
  - "packages/*"
  - "packages/*/example"
  - "packages/core/examples/*"

  - "!pages/**"
shamefullyHoist: true
strictPeerDependencies: false
