import type { PresentationStep } from "@viben/presentation"
import { describeCommand } from "@viben/presentation"

/**
 * Demo presentation steps -- AI Chip Market Analysis
 *
 * 13 steps simulating a presentation-style walkthrough:
 * Focus -> Explain -> Data -> Compare -> Conclusion
 */
export const DEMO_STEPS: PresentationStep[] = [
  {
    id: "step-01-spotlight-title",
    toolUseId: "tool-01",
    toolName: "presentation_spotlight",
    toolInput: {},
    command: {
      type: "spotlight",
      region: { x: 20, y: 20, width: 700, height: 80 },
      maskOpacity: 0.7,
      borderRadius: 12,
      animate: true,
    },
    description: "Spotlight on title region",
    status: "done",
  },
  {
    id: "step-01-card-intro",
    toolUseId: "tool-01",
    toolName: "presentation_draw",
    toolInput: {},
    command: {
      type: "card",
      position: { x: 780, y: 60 },
      width: 340,
      title: "Let's talk about AI chips",
      content: "A trillion-dollar market -- who wins?\nLet the data speak.",
      tag: "Intro",
      tagColor: "#818CF8",
      enterFrom: "right",
      animate: true,
    },
    description: "Intro card slides in from right",
    status: "done",
  },
  {
    id: "step-02-spotlight-nvidia",
    toolUseId: "tool-02",
    toolName: "presentation_spotlight",
    toolInput: {},
    command: {
      type: "spotlight",
      region: { x: 20, y: 108, width: 300, height: 110 },
      maskOpacity: 0.65,
      borderRadius: 12,
      animate: true,
    },
    description: "Spotlight moves to NVIDIA data card",
    status: "done",
  },
  {
    id: "step-02-text-nvidia",
    toolUseId: "tool-02",
    toolName: "presentation_draw",
    toolInput: {},
    command: {
      type: "text",
      position: { x: 40, y: 225 },
      content: "First, the biggest player: NVIDIA",
      fontSize: 15,
      fontWeight: 700,
      color: "#FFFFFF",
      background: "rgba(118, 185, 0, 0.85)",
      animate: true,
    },
    description: "Text annotation: biggest player",
    status: "done",
  },
  {
    id: "step-03-card-nvidia",
    toolUseId: "tool-03",
    toolName: "presentation_draw",
    toolInput: {},
    command: {
      type: "card",
      position: { x: 780, y: 180 },
      width: 340,
      title: "NVIDIA Dominance",
      content: "Market share: 80%\nDC revenue: $26B (YoY +265%)\nCore: H100 / H200 / B100\nCUDA locks in developers",
      tag: "Leader",
      tagColor: "#76B900",
      enterFrom: "right",
      animate: true,
    },
    description: "NVIDIA details card",
    status: "done",
  },
  {
    id: "step-04-arrow-nvidia",
    toolUseId: "tool-04",
    toolName: "presentation_callout",
    toolInput: {},
    command: {
      type: "arrow",
      from: { x: 780, y: 240 },
      to: { x: 200, y: 175 },
      color: "#76B900",
      label: "80% monopoly",
      strokeWidth: 2.5,
      animate: true,
    },
    description: "Arrow from card to data",
    status: "done",
  },
  {
    id: "step-04-circle-80",
    toolUseId: "tool-04",
    toolName: "presentation_draw",
    toolInput: {},
    command: {
      type: "circle",
      center: { x: 155, y: 175 },
      radius: 24,
      color: "#76B900",
      strokeWidth: 3,
      animate: true,
    },
    description: "Circle around 80% number",
    status: "done",
  },
  {
    id: "step-05-spotlight-amd",
    toolUseId: "tool-05",
    toolName: "presentation_spotlight",
    toolInput: {},
    command: {
      type: "spotlight",
      region: { x: 330, y: 108, width: 300, height: 110 },
      maskOpacity: 0.6,
      borderRadius: 12,
      animate: true,
    },
    description: "Spotlight moves to AMD region",
    status: "done",
  },
  {
    id: "step-06-card-amd",
    toolUseId: "tool-06",
    toolName: "presentation_draw",
    toolInput: {},
    command: {
      type: "card",
      position: { x: 780, y: 380 },
      width: 340,
      title: "AMD's Comeback",
      content: "MI300X excellent price-performance\nShare: 12% (YoY +8.1%)\nROCm ecosystem maturing\nStrong in inference",
      tag: "Challenger",
      tagColor: "#ED1C24",
      enterFrom: "left",
      animate: true,
    },
    description: "AMD details card",
    status: "done",
  },
  {
    id: "step-07-arrow-amd",
    toolUseId: "tool-07",
    toolName: "presentation_callout",
    toolInput: {},
    command: {
      type: "arrow",
      from: { x: 780, y: 440 },
      to: { x: 490, y: 175 },
      color: "#ED1C24",
      label: "12% fastest growth",
      strokeWidth: 2.5,
      animate: true,
    },
    description: "Arrow from AMD card to data",
    status: "done",
  },
  {
    id: "step-09-highlight-others",
    toolUseId: "tool-09",
    toolName: "presentation_draw",
    toolInput: {},
    command: {
      type: "highlight",
      region: { x: 640, y: 108, width: 300, height: 110 },
      color: "rgba(99, 102, 241, 0.4)",
      opacity: 0.4,
      borderRadius: 12,
      animate: true,
    },
    description: "Highlight Others region",
    status: "done",
  },
  {
    id: "step-10-text-conclusion",
    toolUseId: "tool-10",
    toolName: "presentation_draw",
    toolInput: {},
    command: {
      type: "text",
      position: { x: 200, y: 320 },
      content: "Conclusion: Competition rising, but NVIDIA still reigns",
      fontSize: 22,
      fontWeight: 800,
      color: "#FFFFFF",
      background: "linear-gradient(135deg, #6366F1, #8B5CF6)",
      animate: true,
    },
    description: "Large conclusion text",
    status: "done",
  },
  {
    id: "step-11-card-summary",
    toolUseId: "tool-11",
    toolName: "presentation_draw",
    toolInput: {},
    command: {
      type: "card",
      position: { x: 340, y: 400 },
      width: 440,
      title: "Key Takeaways",
      content: "1. NVIDIA 80% share is hard to shake short-term\n2. AMD MI300X is the strongest challenger\n3. Custom chips (TPU/Ascend) reshaping the landscape",
      tag: "Summary",
      tagColor: "#10B981",
      enterFrom: "bottom",
      animate: true,
      borderColor: "rgba(16, 185, 129, 0.3)",
    },
    description: "Summary card",
    status: "done",
  },
]
