export const CLIENT_SIDE_MCP_SERVER_NAME = "client_side";
export const LEGACY_GUI_ACTION_MCP_SERVER_NAME = "gui_action";

export const GUI_EXECUTE_TOOL_NAME = "GUI_execute";
export const CLIENT_SIDE_BASH_TOOL_NAME = "ClientSideBash";

export const CLIENT_SIDE_MCP_TOOL_PREFIX = `mcp__${CLIENT_SIDE_MCP_SERVER_NAME}__`;
export const LEGACY_GUI_ACTION_MCP_TOOL_PREFIX = `mcp__${LEGACY_GUI_ACTION_MCP_SERVER_NAME}__`;

export const CLIENT_SIDE_GUI_EXECUTE_TOOL_NAME = `${CLIENT_SIDE_MCP_TOOL_PREFIX}${GUI_EXECUTE_TOOL_NAME}`;
export const LEGACY_GUI_ACTION_GUI_EXECUTE_TOOL_NAME = `${LEGACY_GUI_ACTION_MCP_TOOL_PREFIX}${GUI_EXECUTE_TOOL_NAME}`;
export const CLIENT_SIDE_BASH_MCP_TOOL_NAME = `${CLIENT_SIDE_MCP_TOOL_PREFIX}${CLIENT_SIDE_BASH_TOOL_NAME}`;

export function isAcpClientSideBridgeTool(toolName: string): boolean {
  return toolName === CLIENT_SIDE_GUI_EXECUTE_TOOL_NAME
    || toolName === LEGACY_GUI_ACTION_GUI_EXECUTE_TOOL_NAME
    || toolName === CLIENT_SIDE_BASH_MCP_TOOL_NAME;
}
