/* auto-generated by NAPI-RS */

// ============================================================================
// Initialization
// ============================================================================

/** Initialize the viben-core library */
export function initialize(): Promise<void>

/** Get the version of viben-core */
export function version(): string

/** Get the state directory path */
export function getStateDir(): string

// ============================================================================
// Agent Management
// ============================================================================

export interface Agent {
  id: string
  /** Absolute path to the agent directory */
  path?: string
  name: string
  description?: string
  model?: string
  provider?: string
  systemPrompt?: string
  appendPrompt?: string
  temperature?: number
  maxTokens?: number
  executorType?: string
  planMode: boolean
  approvals: boolean
}

export interface CreateAgentOptions {
  name: string
  description?: string
  model?: string
  provider?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
  fromTemplate?: string
}

export interface UpdateAgentOptions {
  name?: string
  description?: string
  model?: string
  provider?: string
  systemPrompt?: string
  temperature?: number
  maxTokens?: number
}

/** List all agents */
export function agentList(): Promise<Agent[]>

/** Get an agent by ID */
export function agentGet(id: string): Promise<Agent | null>

/** Create a new agent */
export function agentCreate(options: CreateAgentOptions): Promise<Agent>

/** Update an agent */
export function agentUpdate(id: string, options: UpdateAgentOptions): Promise<Agent>

/** Remove an agent */
export function agentRemove(id: string): Promise<void>

/** Set the default agent */
export function agentSetDefault(id: string): Promise<void>

/** Get the default agent ID */
export function agentGetDefault(): Promise<string | null>

// ============================================================================
// Config Management
// ============================================================================

/** Get a config value */
export function configGet(key: string): Promise<string | null>

/** Set a config value */
export function configSet(key: string, value: string): Promise<void>

/** Delete a config key */
export function configDelete(key: string): Promise<void>

/** List all config keys */
export function configList(): Promise<Record<string, string>>

// ============================================================================
// Provider Management
// ============================================================================

export interface Provider {
  id: string
  type: string
  name: string
  baseUrl?: string
  isDefault: boolean
  createdAt: string
  updatedAt: string
}

export interface CreateProviderOptions {
  type: string
  name: string
  apiKey: string
  baseUrl?: string
}

/** List all providers */
export function providerList(): Promise<Provider[]>

/** Get a provider by ID */
export function providerGet(id: string): Promise<Provider | null>

/** Create a new provider */
export function providerCreate(options: CreateProviderOptions): Promise<Provider>

/** Remove a provider */
export function providerRemove(id: string): Promise<void>

/** Set the default provider */
export function providerSetDefault(id: string): Promise<void>

// ============================================================================
// Model Management
// ============================================================================

export interface Model {
  id: string
  name: string
  provider: string
  isDefault: boolean
}

/** List all models */
export function modelList(): Promise<Model[]>

/** Get a model by ID */
export function modelGet(id: string): Promise<Model | null>

/** Set the default model */
export function modelSetDefault(id: string): Promise<void>

/** Get the default model */
export function modelGetDefault(): Promise<string | null>
