import type { StepCommandDef } from "./types"
import { num, numOpt, str, strOpt, bool, json } from "./parse-utils"

export const advancedCommands: StepCommandDef[] = [
  {
    name: "radar",
    description: "Spider/radar chart with multiple axes",
    category: "advanced",
    defaultDurationMs: 5000,
    parseArgs: (args) => ({
      type: "radar",
      position: json(args.position, { x: 360, y: 180 }),
      axes: json(args.axes, [
        { label: "Speed", value: 85 },
        { label: "Power", value: 72 },
        { label: "Range", value: 60 },
        { label: "Defense", value: 90 },
        { label: "Accuracy", value: 78 },
        { label: "Stealth", value: 65 },
      ]),
      color: strOpt(args.color) ?? "#6366F1",
      fillOpacity: numOpt(args.fillOpacity) ?? 0.3,
      size: numOpt(args.size) ?? 220,
    }),
  },
  {
    name: "sankey",
    description: "Flow diagram showing connections and quantities",
    category: "advanced",
    defaultDurationMs: 5000,
    parseArgs: (args) => ({
      type: "sankey",
      position: json(args.position, { x: 200, y: 180 }),
      nodes: json(args.nodes, [
        { id: "organic", label: "Organic" },
        { id: "paid", label: "Paid Ads" },
        { id: "social", label: "Social" },
        { id: "signup", label: "Sign Up" },
        { id: "convert", label: "Conversion" },
      ]),
      links: json(args.links, [
        { source: "organic", target: "signup", value: 40 },
        { source: "paid", target: "signup", value: 30 },
        { source: "social", target: "signup", value: 20 },
        { source: "signup", target: "convert", value: 55 },
      ]),
      width: numOpt(args.width) ?? 520,
      height: numOpt(args.height) ?? 280,
    }),
  },
  {
    name: "kpi",
    description: "KPI metric card with trend indicator and sparkline",
    category: "advanced",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "kpi",
      position: json(args.position, { x: 360, y: 240 }),
      value: args.value !== undefined ? (typeof args.value === "number" ? args.value : Number(args.value) || 2847000) : 2847000,
      label: str(args.label, "Monthly Revenue"),
      trend: (strOpt(args.trend) as "up" | "down" | "flat") ?? "up",
      trendValue: strOpt(args.trendValue) ?? "+12.5%",
      sparkData: json(args.sparkData, [20, 35, 28, 45, 42, 58, 55, 68, 72, 85]),
      color: strOpt(args.color) ?? "#10B981",
    }),
  },
  {
    name: "matrix",
    description: "Comparison matrix with yes/no/partial indicators",
    category: "advanced",
    defaultDurationMs: 5000,
    parseArgs: (args) => ({
      type: "matrix",
      position: json(args.position, { x: 280, y: 180 }),
      columns: json(args.columns, ["Free", "Pro", "Enterprise"]),
      rows: json(args.rows, [
        { label: "Unlimited projects", values: ["no", "yes", "yes"] },
        { label: "Custom domains", values: ["no", "yes", "yes"] },
        { label: "Analytics", values: ["partial", "yes", "yes"] },
        { label: "API Access", values: ["no", "partial", "yes"] },
        { label: "Priority Support", values: ["no", "no", "yes"] },
      ]),
      width: numOpt(args.width) ?? 400,
    }),
  },
  {
    name: "stat-card",
    description: "Before vs after comparison card with delta",
    category: "advanced",
    defaultDurationMs: 5000,
    parseArgs: (args) => ({
      type: "stat-card",
      position: json(args.position, { x: 360, y: 240 }),
      label: str(args.label, "Page Load Time"),
      before: num(args.before, 3200),
      after: num(args.after, 890),
      unit: strOpt(args.unit) ?? "ms",
      color: strOpt(args.color) ?? "#10B981",
    }),
  },
  {
    name: "code-block",
    description: "Code snippet with syntax highlighting and line glow",
    category: "advanced",
    defaultDurationMs: 5000,
    parseArgs: (args) => ({
      type: "code-block",
      position: json(args.position, { x: 280, y: 180 }),
      code: str(args.code, `import { spring } from "remotion";\n\nconst anim = spring({\n  frame,\n  fps: 30,\n  config: { damping: 12 },\n});`),
      language: strOpt(args.language) ?? "typescript",
      highlightLines: json(args.highlightLines, [3, 4, 5, 6]),
    }),
  },
  {
    name: "ribbon",
    description: "Banner ribbon with text overlay",
    category: "advanced",
    defaultDurationMs: 3000,
    parseArgs: (args) => ({
      type: "ribbon",
      position: json(args.position, { x: 360, y: 260 }),
      text: str(args.text, "AWARD WINNER"),
      width: numOpt(args.width) ?? 240,
      color: strOpt(args.color) ?? "#6366F1",
      textColor: strOpt(args.textColor) ?? "#FFFFFF",
      fontSize: numOpt(args.fontSize) ?? 14,
      variant: (strOpt(args.variant) as "flat" | "award") ?? "award",
    }),
  },
  {
    name: "polar-area",
    description: "Polar area chart (rose chart) with animated segments",
    category: "advanced",
    defaultDurationMs: 5000,
    parseArgs: (args) => ({
      type: "polar-area",
      position: json(args.position, { x: 380, y: 200 }),
      segments: json(args.segments, [
        { label: "Sales", value: 85, color: "#6366F1" },
        { label: "Marketing", value: 62, color: "#10B981" },
        { label: "R&D", value: 78, color: "#F59E0B" },
        { label: "Support", value: 45, color: "#EC4899" },
      ]),
      size: numOpt(args.size) ?? 200,
      colors: json(args.colors, undefined),
    }),
  },
  {
    name: "stacked-bar",
    description: "Horizontal stacked bar chart with labels",
    category: "advanced",
    defaultDurationMs: 5000,
    parseArgs: (args) => ({
      type: "stacked-bar",
      position: json(args.position, { x: 280, y: 200 }),
      bars: json(args.bars, [
        {
          label: "2023",
          segments: [
            { value: 40, color: "#6366F1", label: "Product" },
            { value: 30, color: "#10B981", label: "Services" },
            { value: 20, color: "#F59E0B", label: "Other" },
          ],
        },
        {
          label: "2024",
          segments: [
            { value: 55, color: "#6366F1", label: "Product" },
            { value: 25, color: "#10B981", label: "Services" },
            { value: 30, color: "#F59E0B", label: "Other" },
          ],
        },
      ]),
      width: numOpt(args.width) ?? 320,
      barHeight: numOpt(args.barHeight) ?? 32,
      gap: numOpt(args.gap) ?? 12,
    }),
  },
  {
    name: "tooltip",
    description: "Contextual tooltip pointing at a target",
    category: "advanced",
    defaultDurationMs: 3000,
    parseArgs: (args) => ({
      type: "tooltip",
      position: json(args.position, { x: 400, y: 280 }),
      content: str(args.content, "Hover for more details"),
      direction: (strOpt(args.direction) as "top" | "bottom" | "left" | "right") ?? "top",
      background: strOpt(args.background),
      color: strOpt(args.color),
      maxWidth: numOpt(args.maxWidth) ?? 200,
      fontSize: numOpt(args.fontSize) ?? 12,
    }),
  },
  {
    name: "badge-group",
    description: "Multiple animated badges in a grid/flow layout",
    category: "advanced",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "badge-group",
      position: json(args.position, { x: 320, y: 240 }),
      badges: json(args.badges, [
        { text: "React", background: "#61DAFB", color: "#000" },
        { text: "TypeScript", background: "#3178C6", color: "#fff" },
        { text: "Tailwind", background: "#06B6D4", color: "#fff" },
        { text: "Remotion", background: "#6366F1", color: "#fff" },
      ]),
      layout: (strOpt(args.layout) as "flow" | "grid") ?? "flow",
      gap: numOpt(args.gap) ?? 8,
      columns: numOpt(args.columns) ?? 3,
    }),
  },
  {
    name: "meter",
    description: "Linear meter with gradient fill and animated needle",
    category: "advanced",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "meter",
      position: json(args.position, { x: 320, y: 280 }),
      value: num(args.value, 72),
      min: numOpt(args.min) ?? 0,
      max: numOpt(args.max) ?? 100,
      width: numOpt(args.width) ?? 280,
      label: strOpt(args.label) ?? "CPU Usage",
      color: strOpt(args.color) ?? "#6366F1",
      trackColor: strOpt(args.trackColor),
      ticks: numOpt(args.ticks) ?? 5,
      unit: strOpt(args.unit) ?? "%",
      showNeedle: bool(args.showNeedle, true),
    }),
  },
]
