import type { StepCommandDef } from "./types"
import { num, numOpt, str, strOpt, bool, json } from "./parse-utils"

export const coreCommands: StepCommandDef[] = [
  {
    name: "spotlight",
    description: "Dark mask with a highlighted region cutout",
    category: "core",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "spotlight",
      region: json(args.region, { x: 300, y: 200, width: 360, height: 240 }),
      maskOpacity: numOpt(args.maskOpacity) ?? 0.75,
      borderRadius: numOpt(args.borderRadius) ?? 12,
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "arrow",
    description: "Animated arrow from one point to another",
    category: "core",
    defaultDurationMs: 3000,
    parseArgs: (args) => ({
      type: "arrow",
      from: json(args.from, { x: 200, y: 300 }),
      to: json(args.to, { x: 600, y: 200 }),
      color: strOpt(args.color) ?? "#6366F1",
      label: strOpt(args.label) ?? "Look here",
      strokeWidth: numOpt(args.strokeWidth) ?? 3,
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "text",
    description: "Text annotation at a given position",
    category: "core",
    defaultDurationMs: 3000,
    parseArgs: (args) => ({
      type: "text",
      position: json(args.position, { x: 300, y: 260 }),
      content: str(args.content, "Important insight about the data"),
      color: strOpt(args.color) ?? "#fff",
      fontSize: numOpt(args.fontSize) ?? 22,
      background: strOpt(args.background) ?? "rgba(99,102,241,0.85)",
    }),
  },
  {
    name: "circle",
    description: "Circle annotation around a focal point",
    category: "core",
    defaultDurationMs: 3000,
    parseArgs: (args) => ({
      type: "circle",
      center: json(args.center, { x: 480, y: 300 }),
      radius: num(args.radius, 80),
      color: strOpt(args.color) ?? "#EF4444",
      strokeWidth: numOpt(args.strokeWidth) ?? 3,
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "highlight",
    description: "Semi-transparent color block over a region",
    category: "core",
    defaultDurationMs: 3000,
    parseArgs: (args) => ({
      type: "highlight",
      region: json(args.region, { x: 280, y: 200, width: 400, height: 200 }),
      color: strOpt(args.color) ?? "#F59E0B",
      opacity: numOpt(args.opacity) ?? 0.25,
      borderRadius: numOpt(args.borderRadius) ?? 8,
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "card",
    description: "Info card with title and content text",
    category: "core",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "card",
      position: json(args.position, { x: 280, y: 180 }),
      width: numOpt(args.width) ?? 380,
      title: strOpt(args.title) ?? "Key Finding",
      content: str(args.content, "Revenue grew 42% year-over-year, exceeding all analyst expectations."),
      tag: strOpt(args.tag) ?? "Insight",
      tagColor: strOpt(args.tagColor) ?? "#6366F1",
      background: strOpt(args.background) ?? "rgba(15,20,40,0.92)",
      borderColor: strOpt(args.borderColor) ?? "rgba(99,102,241,0.4)",
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "pulse",
    description: "Pulsing concentric rings drawing attention",
    category: "core",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "pulse",
      center: json(args.center, { x: 480, y: 300 }),
      radius: num(args.radius, 30),
      color: strOpt(args.color) ?? "#EC4899",
      rings: numOpt(args.rings) ?? 3,
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "underline",
    description: "Animated underline below a region of text",
    category: "core",
    defaultDurationMs: 3000,
    parseArgs: (args) => ({
      type: "underline",
      from: json(args.from, { x: 280, y: 310 }),
      to: json(args.to, { x: 680, y: 310 }),
      color: strOpt(args.color) ?? "#F59E0B",
      strokeWidth: numOpt(args.strokeWidth) ?? 3,
      style: (strOpt(args.style) as "straight" | "wavy") ?? "wavy",
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "badge",
    description: "Floating label pill / chip annotation",
    category: "core",
    defaultDurationMs: 3000,
    parseArgs: (args) => ({
      type: "badge",
      position: json(args.position, { x: 420, y: 280 }),
      text: str(args.text, "NEW"),
      color: strOpt(args.color) ?? "#fff",
      background: strOpt(args.background) ?? "#6366F1",
      size: (strOpt(args.size) as "sm" | "md" | "lg") ?? "md",
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "progress",
    description: "Animated horizontal progress bar",
    category: "core",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "progress",
      position: json(args.position, { x: 280, y: 290 }),
      width: numOpt(args.width) ?? 400,
      value: num(args.value, 73),
      color: strOpt(args.color) ?? "#10B981",
      showLabel: bool(args.showLabel, true),
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "counter",
    description: "Animated number counting up to a value",
    category: "core",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "counter",
      position: json(args.position, { x: 380, y: 250 }),
      value: num(args.value, 8742),
      prefix: strOpt(args.prefix) ?? "$",
      suffix: strOpt(args.suffix) ?? "M",
      color: strOpt(args.color) ?? "#76B900",
      fontSize: numOpt(args.fontSize) ?? 48,
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "bracket",
    description: "Curly brace grouping two points together",
    category: "core",
    defaultDurationMs: 3000,
    parseArgs: (args) => ({
      type: "bracket",
      from: json(args.from, { x: 380, y: 180 }),
      to: json(args.to, { x: 380, y: 420 }),
      direction: (strOpt(args.direction) as "left" | "right") ?? "right",
      color: strOpt(args.color) ?? "#A855F7",
      strokeWidth: numOpt(args.strokeWidth) ?? 2,
      label: strOpt(args.label) ?? "Group A",
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "trendline",
    description: "SVG polyline with optional dots and area fill",
    category: "core",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "trendline",
      points: json(args.points, [
        { x: 200, y: 400 },
        { x: 320, y: 340 },
        { x: 440, y: 360 },
        { x: 560, y: 240 },
        { x: 680, y: 200 },
      ]),
      color: strOpt(args.color) ?? "#38BDF8",
      strokeWidth: numOpt(args.strokeWidth) ?? 3,
      showDots: bool(args.showDots, true),
      fillBelow: strOpt(args.fillBelow) ?? "rgba(56,189,248,0.15)",
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "comparison",
    description: "Side-by-side bar comparison of two values",
    category: "core",
    defaultDurationMs: 4000,
    parseArgs: (args) => ({
      type: "comparison",
      position: json(args.position, { x: 280, y: 220 }),
      width: numOpt(args.width) ?? 400,
      leftLabel: str(args.leftLabel, "Revenue"),
      rightLabel: str(args.rightLabel, "Expenses"),
      leftValue: num(args.leftValue, 84),
      rightValue: num(args.rightValue, 56),
      leftColor: strOpt(args.leftColor) ?? "#10B981",
      rightColor: strOpt(args.rightColor) ?? "#EF4444",
      unit: strOpt(args.unit) ?? "%",
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "typewriter",
    description: "Text that types itself character by character",
    category: "core",
    defaultDurationMs: 5000,
    parseArgs: (args) => ({
      type: "typewriter",
      position: json(args.position, { x: 240, y: 270 }),
      content: str(args.content, "The future of AI is here..."),
      fontSize: numOpt(args.fontSize) ?? 28,
      color: strOpt(args.color) ?? "#fff",
      speed: (strOpt(args.speed) as "slow" | "normal" | "fast") ?? "normal",
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "chart",
    description: "Professional animated chart (bar, line, area, pie)",
    category: "core",
    defaultDurationMs: 5000,
    parseArgs: (args) => ({
      type: "chart",
      position: json(args.position, { x: 260, y: 160 }),
      width: numOpt(args.width) ?? 420,
      height: numOpt(args.height) ?? 260,
      chartType: (strOpt(args.chartType) as "line" | "bar" | "area" | "pie") ?? "bar",
      data: json(args.data, [
        { name: "Q1", value: 42, color: "#6366F1" },
        { name: "Q2", value: 58, color: "#8B5CF6" },
        { name: "Q3", value: 71, color: "#A855F7" },
        { name: "Q4", value: 89, color: "#C084FC" },
      ]),
      title: strOpt(args.title) ?? "Quarterly Revenue",
      showGrid: bool(args.showGrid, true),
      showAxis: bool(args.showAxis, true),
      animate: bool(args.animate, true),
    }),
  },
  {
    name: "clear",
    description: "Remove all current annotations",
    category: "core",
    defaultDurationMs: 500,
    parseArgs: () => ({ type: "clear" }),
  },
  {
    name: "wait",
    description: "Pause in the timeline",
    category: "core",
    defaultDurationMs: 2000,
    parseArgs: (args) => ({
      type: "wait",
      ms: num(args.ms, 2000),
    }),
  },
]
