import type { StepCommandDef } from "./types"
import { num, numOpt, strOpt, bool, json } from "./parse-utils"

export const datavizCommands: StepCommandDef[] = [
  {
    name: "gauge",
    description: "Circular gauge meter with animated needle",
    category: "dataviz",
    defaultDurationMs: 4000,
    inputSchema: {
      type: "object",
      properties: {
        position: { type: "object", description: "Position {x, y}" },
        value: { type: "number", description: "Gauge value (0-100), default 78" },
        label: { type: "string", description: "Gauge label, default 'Performance'" },
        color: { type: "string", description: "Gauge color, default #6366F1" },
      },
    },
    parseArgs: (args) => ({
      type: "gauge",
      position: json(args.position, { x: 370, y: 200 }),
      value: num(args.value, 78),
      label: strOpt(args.label) ?? "Performance",
      color: strOpt(args.color) ?? "#6366F1",
    }),
  },
  {
    name: "sparkline",
    description: "Compact inline line chart with optional fill",
    category: "dataviz",
    defaultDurationMs: 4000,
    inputSchema: {
      type: "object",
      properties: {
        position: { type: "object", description: "Position {x, y}" },
        data: { type: "array", description: "Array of numeric values" },
        width: { type: "number", description: "Width in px, default 280" },
        height: { type: "number", description: "Height in px, default 80" },
        color: { type: "string", description: "Line color, default #10B981" },
        fill: { type: "boolean", description: "Fill area below line, default true" },
        showEndDot: { type: "boolean", description: "Show dot at end of line, default true" },
      },
    },
    parseArgs: (args) => ({
      type: "sparkline",
      position: json(args.position, { x: 340, y: 250 }),
      data: json(args.data, [10, 25, 18, 42, 35, 60, 55, 72, 68, 80]),
      width: numOpt(args.width) ?? 280,
      height: numOpt(args.height) ?? 80,
      color: strOpt(args.color) ?? "#10B981",
      fill: bool(args.fill, true),
      showEndDot: bool(args.showEndDot, true),
    }),
  },
  {
    name: "heatmap",
    description: "Grid of colored cells showing intensity values",
    category: "dataviz",
    defaultDurationMs: 4000,
    inputSchema: {
      type: "object",
      properties: {
        position: { type: "object", description: "Position {x, y}" },
        data: { type: "array", description: "2D array of values (0-1) representing cell intensities" },
        cellSize: { type: "number", description: "Cell size in px, default 48" },
        rowLabels: { type: "array", description: "Row label strings" },
        colLabels: { type: "array", description: "Column label strings" },
      },
    },
    parseArgs: (args) => ({
      type: "heatmap",
      position: json(args.position, { x: 350, y: 200 }),
      data: json(args.data, [
        [0.2, 0.8, 0.5],
        [0.9, 0.3, 0.7],
        [0.4, 0.6, 1.0],
      ]),
      cellSize: numOpt(args.cellSize) ?? 48,
      rowLabels: json(args.rowLabels, ["A", "B", "C"]),
      colLabels: json(args.colLabels, ["X", "Y", "Z"]),
    }),
  },
  {
    name: "funnel",
    description: "Vertical funnel / pyramid with stage labels",
    category: "dataviz",
    defaultDurationMs: 4000,
    inputSchema: {
      type: "object",
      properties: {
        position: { type: "object", description: "Position {x, y}" },
        stages: { type: "array", description: "Array of {label, value, color} funnel stages" },
        width: { type: "number", description: "Width in px, default 320" },
        height: { type: "number", description: "Height in px, default 280" },
      },
    },
    parseArgs: (args) => ({
      type: "funnel",
      position: json(args.position, { x: 320, y: 140 }),
      stages: json(args.stages, [
        { label: "Visitors", value: 10000, color: "#6366F1" },
        { label: "Leads", value: 5200, color: "#8B5CF6" },
        { label: "Trials", value: 2100, color: "#A855F7" },
        { label: "Customers", value: 800, color: "#C084FC" },
      ]),
      width: numOpt(args.width) ?? 320,
      height: numOpt(args.height) ?? 280,
    }),
  },
  {
    name: "waterfall",
    description: "Incremental increase / decrease bar chart",
    category: "dataviz",
    defaultDurationMs: 4000,
    inputSchema: {
      type: "object",
      properties: {
        position: { type: "object", description: "Position {x, y}" },
        data: { type: "array", description: "Array of {label, value, type} where type is 'total', 'increase', or 'decrease'" },
        width: { type: "number", description: "Width in px, default 440" },
        height: { type: "number", description: "Height in px, default 260" },
      },
    },
    parseArgs: (args) => ({
      type: "waterfall",
      position: json(args.position, { x: 260, y: 160 }),
      data: json(args.data, [
        { label: "Revenue", value: 100, type: "total" },
        { label: "Sales", value: 40, type: "increase" },
        { label: "Services", value: 25, type: "increase" },
        { label: "Costs", value: -35, type: "decrease" },
        { label: "Tax", value: -15, type: "decrease" },
        { label: "Net", value: 115, type: "total" },
      ]),
      width: numOpt(args.width) ?? 440,
      height: numOpt(args.height) ?? 260,
    }),
  },
  {
    name: "treemap",
    description: "Rectangular treemap showing hierarchical proportions",
    category: "dataviz",
    defaultDurationMs: 5000,
    inputSchema: {
      type: "object",
      properties: {
        position: { type: "object", description: "Position {x, y}" },
        data: { type: "array", description: "Array of {label, value, color} items" },
        width: { type: "number", description: "Width in px, default 360" },
        height: { type: "number", description: "Height in px, default 220" },
      },
    },
    parseArgs: (args) => ({
      type: "treemap",
      position: json(args.position, { x: 300, y: 180 }),
      data: json(args.data, [
        { label: "React", value: 42, color: "#61DAFB" },
        { label: "Vue", value: 28, color: "#42B883" },
        { label: "Angular", value: 18, color: "#DD0031" },
        { label: "Svelte", value: 12, color: "#FF3E00" },
        { label: "Solid", value: 8, color: "#2C4F7C" },
      ]),
      width: numOpt(args.width) ?? 360,
      height: numOpt(args.height) ?? 220,
    }),
  },
  {
    name: "donut",
    description: "Ring chart with animated arc drawing",
    category: "dataviz",
    defaultDurationMs: 5000,
    inputSchema: {
      type: "object",
      properties: {
        position: { type: "object", description: "Position {x, y}" },
        segments: { type: "array", description: "Array of {label, value, color} segments" },
        size: { type: "number", description: "Outer diameter in px, default 180" },
        innerRatio: { type: "number", description: "Inner hole ratio (0-1), default 0.6" },
      },
    },
    parseArgs: (args) => ({
      type: "donut",
      position: json(args.position, { x: 380, y: 200 }),
      segments: json(args.segments, [
        { label: "Desktop", value: 54, color: "#6366F1" },
        { label: "Mobile", value: 32, color: "#10B981" },
        { label: "Tablet", value: 9, color: "#F59E0B" },
        { label: "Other", value: 5, color: "#EC4899" },
      ]),
      size: numOpt(args.size) ?? 180,
      innerRatio: numOpt(args.innerRatio) ?? 0.6,
    }),
  },
  {
    name: "scatter",
    description: "Scatter plot with physics-based dot animation",
    category: "dataviz",
    defaultDurationMs: 5000,
    inputSchema: {
      type: "object",
      properties: {
        position: { type: "object", description: "Position {x, y}" },
        points: { type: "array", description: "Array of {x, y} data points" },
        width: { type: "number", description: "Width in px, default 280" },
        height: { type: "number", description: "Height in px, default 200" },
        color: { type: "string", description: "Dot color, default #6366F1" },
        dotRadius: { type: "number", description: "Dot radius in px, default 5" },
        xLabel: { type: "string", description: "X axis label" },
        yLabel: { type: "string", description: "Y axis label" },
        showGrid: { type: "boolean", description: "Show grid lines, default true" },
      },
    },
    parseArgs: (args) => ({
      type: "scatter",
      position: json(args.position, { x: 320, y: 180 }),
      points: json(args.points, [
        { x: 10, y: 30 },
        { x: 25, y: 55 },
        { x: 40, y: 45 },
        { x: 55, y: 70 },
        { x: 70, y: 62 },
        { x: 85, y: 88 },
      ]),
      width: numOpt(args.width) ?? 280,
      height: numOpt(args.height) ?? 200,
      color: strOpt(args.color) ?? "#6366F1",
      dotRadius: numOpt(args.dotRadius) ?? 5,
      xLabel: strOpt(args.xLabel),
      yLabel: strOpt(args.yLabel),
      showGrid: bool(args.showGrid, true),
    }),
  },
]
