/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AgentGetTasksRequest = {
  agentId: string;
};

/** @internal */
export type AgentGetTasksRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const AgentGetTasksRequest$outboundSchema: z.ZodType<
  AgentGetTasksRequest$Outbound,
  z.ZodTypeDef,
  AgentGetTasksRequest
> = z.object({
  agentId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentGetTasksRequest$ {
  /** @deprecated use `AgentGetTasksRequest$outboundSchema` instead. */
  export const outboundSchema = AgentGetTasksRequest$outboundSchema;
  /** @deprecated use `AgentGetTasksRequest$Outbound` instead. */
  export type Outbound = AgentGetTasksRequest$Outbound;
}

export function agentGetTasksRequestToJSON(
  agentGetTasksRequest: AgentGetTasksRequest,
): string {
  return JSON.stringify(
    AgentGetTasksRequest$outboundSchema.parse(agentGetTasksRequest),
  );
}
