/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type AgentGetSessionMessagesRequest = {
  id: string;
  sessionId: string;
};

/** @internal */
export type AgentGetSessionMessagesRequest$Outbound = {
  id: string;
  session_id: string;
};

/** @internal */
export const AgentGetSessionMessagesRequest$outboundSchema: z.ZodType<
  AgentGetSessionMessagesRequest$Outbound,
  z.ZodTypeDef,
  AgentGetSessionMessagesRequest
> = z.object({
  id: z.string(),
  sessionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    sessionId: "session_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentGetSessionMessagesRequest$ {
  /** @deprecated use `AgentGetSessionMessagesRequest$outboundSchema` instead. */
  export const outboundSchema = AgentGetSessionMessagesRequest$outboundSchema;
  /** @deprecated use `AgentGetSessionMessagesRequest$Outbound` instead. */
  export type Outbound = AgentGetSessionMessagesRequest$Outbound;
}

export function agentGetSessionMessagesRequestToJSON(
  agentGetSessionMessagesRequest: AgentGetSessionMessagesRequest,
): string {
  return JSON.stringify(
    AgentGetSessionMessagesRequest$outboundSchema.parse(
      agentGetSessionMessagesRequest,
    ),
  );
}
