/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AgentUpdateRequest = {
  id: string;
};

/** @internal */
export type AgentUpdateRequest$Outbound = {
  id: string;
};

/** @internal */
export const AgentUpdateRequest$outboundSchema: z.ZodType<
  AgentUpdateRequest$Outbound,
  z.ZodTypeDef,
  AgentUpdateRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentUpdateRequest$ {
  /** @deprecated use `AgentUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = AgentUpdateRequest$outboundSchema;
  /** @deprecated use `AgentUpdateRequest$Outbound` instead. */
  export type Outbound = AgentUpdateRequest$Outbound;
}

export function agentUpdateRequestToJSON(
  agentUpdateRequest: AgentUpdateRequest,
): string {
  return JSON.stringify(
    AgentUpdateRequest$outboundSchema.parse(agentUpdateRequest),
  );
}
