/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AgentGetSessionTaskMessagesRequest = {
  agentId: string;
  sessionId: string;
  taskId: string;
};

/** @internal */
export type AgentGetSessionTaskMessagesRequest$Outbound = {
  agentId: string;
  sessionId: string;
  taskId: string;
};

/** @internal */
export const AgentGetSessionTaskMessagesRequest$outboundSchema: z.ZodType<
  AgentGetSessionTaskMessagesRequest$Outbound,
  z.ZodTypeDef,
  AgentGetSessionTaskMessagesRequest
> = z.object({
  agentId: z.string(),
  sessionId: z.string(),
  taskId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentGetSessionTaskMessagesRequest$ {
  /** @deprecated use `AgentGetSessionTaskMessagesRequest$outboundSchema` instead. */
  export const outboundSchema =
    AgentGetSessionTaskMessagesRequest$outboundSchema;
  /** @deprecated use `AgentGetSessionTaskMessagesRequest$Outbound` instead. */
  export type Outbound = AgentGetSessionTaskMessagesRequest$Outbound;
}

export function agentGetSessionTaskMessagesRequestToJSON(
  agentGetSessionTaskMessagesRequest: AgentGetSessionTaskMessagesRequest,
): string {
  return JSON.stringify(
    AgentGetSessionTaskMessagesRequest$outboundSchema.parse(
      agentGetSessionTaskMessagesRequest,
    ),
  );
}
