/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AgentGetSession2Request = {
  sessionId: string;
};

/** @internal */
export type AgentGetSession2Request$Outbound = {
  sessionId: string;
};

/** @internal */
export const AgentGetSession2Request$outboundSchema: z.ZodType<
  AgentGetSession2Request$Outbound,
  z.ZodTypeDef,
  AgentGetSession2Request
> = z.object({
  sessionId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentGetSession2Request$ {
  /** @deprecated use `AgentGetSession2Request$outboundSchema` instead. */
  export const outboundSchema = AgentGetSession2Request$outboundSchema;
  /** @deprecated use `AgentGetSession2Request$Outbound` instead. */
  export type Outbound = AgentGetSession2Request$Outbound;
}

export function agentGetSession2RequestToJSON(
  agentGetSession2Request: AgentGetSession2Request,
): string {
  return JSON.stringify(
    AgentGetSession2Request$outboundSchema.parse(agentGetSession2Request),
  );
}
