/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ApiLogsGetRequest = {
  runId: string;
};

/** @internal */
export type ApiLogsGetRequest$Outbound = {
  runId: string;
};

/** @internal */
export const ApiLogsGetRequest$outboundSchema: z.ZodType<
  ApiLogsGetRequest$Outbound,
  z.ZodTypeDef,
  ApiLogsGetRequest
> = z.object({
  runId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiLogsGetRequest$ {
  /** @deprecated use `ApiLogsGetRequest$outboundSchema` instead. */
  export const outboundSchema = ApiLogsGetRequest$outboundSchema;
  /** @deprecated use `ApiLogsGetRequest$Outbound` instead. */
  export type Outbound = ApiLogsGetRequest$Outbound;
}

export function apiLogsGetRequestToJSON(
  apiLogsGetRequest: ApiLogsGetRequest,
): string {
  return JSON.stringify(
    ApiLogsGetRequest$outboundSchema.parse(apiLogsGetRequest),
  );
}
