/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AuthCreateCallbackRequest = {
  provider: string;
};

/** @internal */
export type AuthCreateCallbackRequest$Outbound = {
  provider: string;
};

/** @internal */
export const AuthCreateCallbackRequest$outboundSchema: z.ZodType<
  AuthCreateCallbackRequest$Outbound,
  z.ZodTypeDef,
  AuthCreateCallbackRequest
> = z.object({
  provider: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthCreateCallbackRequest$ {
  /** @deprecated use `AuthCreateCallbackRequest$outboundSchema` instead. */
  export const outboundSchema = AuthCreateCallbackRequest$outboundSchema;
  /** @deprecated use `AuthCreateCallbackRequest$Outbound` instead. */
  export type Outbound = AuthCreateCallbackRequest$Outbound;
}

export function authCreateCallbackRequestToJSON(
  authCreateCallbackRequest: AuthCreateCallbackRequest,
): string {
  return JSON.stringify(
    AuthCreateCallbackRequest$outboundSchema.parse(authCreateCallbackRequest),
  );
}
