/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ChannelType = {
  Telegram: "telegram",
  Discord: "discord",
  Feishu: "feishu",
  Whatsapp: "whatsapp",
  Slack: "slack",
  Webhook: "webhook",
} as const;
export type ChannelType = ClosedEnum<typeof ChannelType>;

export type ChannelsListConfig = {};

export const NotificationMode = {
  None: "none",
  All: "all",
  Errors: "errors",
  Success: "success",
} as const;
export type NotificationMode = ClosedEnum<typeof NotificationMode>;

export type ChannelsListAgentBinding = {
  bindingType?: string | undefined;
  id?: string | undefined;
  name?: string | undefined;
  workspacePath?: string | undefined;
};

export type Channels = {
  id?: string | undefined;
  channelType?: ChannelType | undefined;
  name?: string | undefined;
  config?: ChannelsListConfig | undefined;
  isDefault?: boolean | undefined;
  enabled?: boolean | undefined;
  notificationMode?: NotificationMode | undefined;
  agentBinding?: ChannelsListAgentBinding | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

/**
 * Default Response
 */
export type ChannelsListResponseBody = {
  channels?: Array<Channels> | undefined;
};

/** @internal */
export const ChannelType$inboundSchema: z.ZodNativeEnum<typeof ChannelType> = z
  .nativeEnum(ChannelType);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChannelType$ {
  /** @deprecated use `ChannelType$inboundSchema` instead. */
  export const inboundSchema = ChannelType$inboundSchema;
}

/** @internal */
export const ChannelsListConfig$inboundSchema: z.ZodType<
  ChannelsListConfig,
  z.ZodTypeDef,
  unknown
> = z.object({});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChannelsListConfig$ {
  /** @deprecated use `ChannelsListConfig$inboundSchema` instead. */
  export const inboundSchema = ChannelsListConfig$inboundSchema;
}

export function channelsListConfigFromJSON(
  jsonString: string,
): SafeParseResult<ChannelsListConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChannelsListConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChannelsListConfig' from JSON`,
  );
}

/** @internal */
export const NotificationMode$inboundSchema: z.ZodNativeEnum<
  typeof NotificationMode
> = z.nativeEnum(NotificationMode);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationMode$ {
  /** @deprecated use `NotificationMode$inboundSchema` instead. */
  export const inboundSchema = NotificationMode$inboundSchema;
}

/** @internal */
export const ChannelsListAgentBinding$inboundSchema: z.ZodType<
  ChannelsListAgentBinding,
  z.ZodTypeDef,
  unknown
> = z.object({
  binding_type: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  workspace_path: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "binding_type": "bindingType",
    "workspace_path": "workspacePath",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChannelsListAgentBinding$ {
  /** @deprecated use `ChannelsListAgentBinding$inboundSchema` instead. */
  export const inboundSchema = ChannelsListAgentBinding$inboundSchema;
}

export function channelsListAgentBindingFromJSON(
  jsonString: string,
): SafeParseResult<ChannelsListAgentBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChannelsListAgentBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChannelsListAgentBinding' from JSON`,
  );
}

/** @internal */
export const Channels$inboundSchema: z.ZodType<
  Channels,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  channel_type: ChannelType$inboundSchema.optional(),
  name: z.string().optional(),
  config: z.lazy(() => ChannelsListConfig$inboundSchema).optional(),
  is_default: z.boolean().optional(),
  enabled: z.boolean().optional(),
  notification_mode: NotificationMode$inboundSchema.optional(),
  agent_binding: z.lazy(() => ChannelsListAgentBinding$inboundSchema)
    .optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "channel_type": "channelType",
    "is_default": "isDefault",
    "notification_mode": "notificationMode",
    "agent_binding": "agentBinding",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Channels$ {
  /** @deprecated use `Channels$inboundSchema` instead. */
  export const inboundSchema = Channels$inboundSchema;
}

export function channelsFromJSON(
  jsonString: string,
): SafeParseResult<Channels, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Channels$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Channels' from JSON`,
  );
}

/** @internal */
export const ChannelsListResponseBody$inboundSchema: z.ZodType<
  ChannelsListResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  channels: z.array(z.lazy(() => Channels$inboundSchema)).optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChannelsListResponseBody$ {
  /** @deprecated use `ChannelsListResponseBody$inboundSchema` instead. */
  export const inboundSchema = ChannelsListResponseBody$inboundSchema;
}

export function channelsListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ChannelsListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChannelsListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChannelsListResponseBody' from JSON`,
  );
}
