/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ChannelsCreateWebhook2Request = {
  id: string;
};

/** @internal */
export type ChannelsCreateWebhook2Request$Outbound = {
  id: string;
};

/** @internal */
export const ChannelsCreateWebhook2Request$outboundSchema: z.ZodType<
  ChannelsCreateWebhook2Request$Outbound,
  z.ZodTypeDef,
  ChannelsCreateWebhook2Request
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChannelsCreateWebhook2Request$ {
  /** @deprecated use `ChannelsCreateWebhook2Request$outboundSchema` instead. */
  export const outboundSchema = ChannelsCreateWebhook2Request$outboundSchema;
  /** @deprecated use `ChannelsCreateWebhook2Request$Outbound` instead. */
  export type Outbound = ChannelsCreateWebhook2Request$Outbound;
}

export function channelsCreateWebhook2RequestToJSON(
  channelsCreateWebhook2Request: ChannelsCreateWebhook2Request,
): string {
  return JSON.stringify(
    ChannelsCreateWebhook2Request$outboundSchema.parse(
      channelsCreateWebhook2Request,
    ),
  );
}
