/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CollectionsCreateForkRequest = {
  id: string;
};

/** @internal */
export type CollectionsCreateForkRequest$Outbound = {
  id: string;
};

/** @internal */
export const CollectionsCreateForkRequest$outboundSchema: z.ZodType<
  CollectionsCreateForkRequest$Outbound,
  z.ZodTypeDef,
  CollectionsCreateForkRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollectionsCreateForkRequest$ {
  /** @deprecated use `CollectionsCreateForkRequest$outboundSchema` instead. */
  export const outboundSchema = CollectionsCreateForkRequest$outboundSchema;
  /** @deprecated use `CollectionsCreateForkRequest$Outbound` instead. */
  export type Outbound = CollectionsCreateForkRequest$Outbound;
}

export function collectionsCreateForkRequestToJSON(
  collectionsCreateForkRequest: CollectionsCreateForkRequest,
): string {
  return JSON.stringify(
    CollectionsCreateForkRequest$outboundSchema.parse(
      collectionsCreateForkRequest,
    ),
  );
}
