/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CollectionsDeleteItemRequest = {
  id: string;
  eid: string;
};

/** @internal */
export type CollectionsDeleteItemRequest$Outbound = {
  id: string;
  eid: string;
};

/** @internal */
export const CollectionsDeleteItemRequest$outboundSchema: z.ZodType<
  CollectionsDeleteItemRequest$Outbound,
  z.ZodTypeDef,
  CollectionsDeleteItemRequest
> = z.object({
  id: z.string(),
  eid: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollectionsDeleteItemRequest$ {
  /** @deprecated use `CollectionsDeleteItemRequest$outboundSchema` instead. */
  export const outboundSchema = CollectionsDeleteItemRequest$outboundSchema;
  /** @deprecated use `CollectionsDeleteItemRequest$Outbound` instead. */
  export type Outbound = CollectionsDeleteItemRequest$Outbound;
}

export function collectionsDeleteItemRequestToJSON(
  collectionsDeleteItemRequest: CollectionsDeleteItemRequest,
): string {
  return JSON.stringify(
    CollectionsDeleteItemRequest$outboundSchema.parse(
      collectionsDeleteItemRequest,
    ),
  );
}
