/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CommandQueueGetItemLogsRequest = {
  id: string;
};

/** @internal */
export type CommandQueueGetItemLogsRequest$Outbound = {
  id: string;
};

/** @internal */
export const CommandQueueGetItemLogsRequest$outboundSchema: z.ZodType<
  CommandQueueGetItemLogsRequest$Outbound,
  z.ZodTypeDef,
  CommandQueueGetItemLogsRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommandQueueGetItemLogsRequest$ {
  /** @deprecated use `CommandQueueGetItemLogsRequest$outboundSchema` instead. */
  export const outboundSchema = CommandQueueGetItemLogsRequest$outboundSchema;
  /** @deprecated use `CommandQueueGetItemLogsRequest$Outbound` instead. */
  export type Outbound = CommandQueueGetItemLogsRequest$Outbound;
}

export function commandQueueGetItemLogsRequestToJSON(
  commandQueueGetItemLogsRequest: CommandQueueGetItemLogsRequest,
): string {
  return JSON.stringify(
    CommandQueueGetItemLogsRequest$outboundSchema.parse(
      commandQueueGetItemLogsRequest,
    ),
  );
}
