/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CommandQueueCancelItemRequest = {
  id: string;
};

/** @internal */
export type CommandQueueCancelItemRequest$Outbound = {
  id: string;
};

/** @internal */
export const CommandQueueCancelItemRequest$outboundSchema: z.ZodType<
  CommandQueueCancelItemRequest$Outbound,
  z.ZodTypeDef,
  CommandQueueCancelItemRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommandQueueCancelItemRequest$ {
  /** @deprecated use `CommandQueueCancelItemRequest$outboundSchema` instead. */
  export const outboundSchema = CommandQueueCancelItemRequest$outboundSchema;
  /** @deprecated use `CommandQueueCancelItemRequest$Outbound` instead. */
  export type Outbound = CommandQueueCancelItemRequest$Outbound;
}

export function commandQueueCancelItemRequestToJSON(
  commandQueueCancelItemRequest: CommandQueueCancelItemRequest,
): string {
  return JSON.stringify(
    CommandQueueCancelItemRequest$outboundSchema.parse(
      commandQueueCancelItemRequest,
    ),
  );
}
