/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CommandQueueGetItemRequest = {
  id: string;
};

/** @internal */
export type CommandQueueGetItemRequest$Outbound = {
  id: string;
};

/** @internal */
export const CommandQueueGetItemRequest$outboundSchema: z.ZodType<
  CommandQueueGetItemRequest$Outbound,
  z.ZodTypeDef,
  CommandQueueGetItemRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommandQueueGetItemRequest$ {
  /** @deprecated use `CommandQueueGetItemRequest$outboundSchema` instead. */
  export const outboundSchema = CommandQueueGetItemRequest$outboundSchema;
  /** @deprecated use `CommandQueueGetItemRequest$Outbound` instead. */
  export type Outbound = CommandQueueGetItemRequest$Outbound;
}

export function commandQueueGetItemRequestToJSON(
  commandQueueGetItemRequest: CommandQueueGetItemRequest,
): string {
  return JSON.stringify(
    CommandQueueGetItemRequest$outboundSchema.parse(commandQueueGetItemRequest),
  );
}
