/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const JobType = {
  Agent: "agent",
  Script: "script",
  Message: "message",
} as const;
export type JobType = ClosedEnum<typeof JobType>;

export type CronListNotifications = {};

export type Jobs = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  enabled?: boolean | undefined;
  jobType?: JobType | undefined;
  message?: string | undefined;
  script?: string | undefined;
  /**
   * Cron expression
   */
  cron?: string | undefined;
  /**
   * Interval in milliseconds
   */
  every?: number | undefined;
  channel?: string | undefined;
  agent?: string | undefined;
  workspacePath?: string | undefined;
  notifications?: CronListNotifications | undefined;
  lastRun?: number | undefined;
  lastStatus?: string | undefined;
  lastError?: string | undefined;
  lastOutput?: string | undefined;
  nextRun?: number | undefined;
  createdAt?: number | undefined;
  updatedAt?: number | undefined;
};

/**
 * Default Response
 */
export type CronListResponseBody = {
  jobs?: Array<Jobs> | undefined;
};

/** @internal */
export const JobType$inboundSchema: z.ZodNativeEnum<typeof JobType> = z
  .nativeEnum(JobType);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace JobType$ {
  /** @deprecated use `JobType$inboundSchema` instead. */
  export const inboundSchema = JobType$inboundSchema;
}

/** @internal */
export const CronListNotifications$inboundSchema: z.ZodType<
  CronListNotifications,
  z.ZodTypeDef,
  unknown
> = z.object({});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CronListNotifications$ {
  /** @deprecated use `CronListNotifications$inboundSchema` instead. */
  export const inboundSchema = CronListNotifications$inboundSchema;
}

export function cronListNotificationsFromJSON(
  jsonString: string,
): SafeParseResult<CronListNotifications, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CronListNotifications$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CronListNotifications' from JSON`,
  );
}

/** @internal */
export const Jobs$inboundSchema: z.ZodType<Jobs, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    enabled: z.boolean().optional(),
    job_type: JobType$inboundSchema.optional(),
    message: z.string().optional(),
    script: z.string().optional(),
    cron: z.string().optional(),
    every: z.number().optional(),
    channel: z.string().optional(),
    agent: z.string().optional(),
    workspace_path: z.string().optional(),
    notifications: z.lazy(() => CronListNotifications$inboundSchema).optional(),
    last_run: z.number().optional(),
    last_status: z.string().optional(),
    last_error: z.string().optional(),
    last_output: z.string().optional(),
    next_run: z.number().optional(),
    created_at: z.number().optional(),
    updated_at: z.number().optional(),
  }).transform((v) => {
    return remap$(v, {
      "job_type": "jobType",
      "workspace_path": "workspacePath",
      "last_run": "lastRun",
      "last_status": "lastStatus",
      "last_error": "lastError",
      "last_output": "lastOutput",
      "next_run": "nextRun",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Jobs$ {
  /** @deprecated use `Jobs$inboundSchema` instead. */
  export const inboundSchema = Jobs$inboundSchema;
}

export function jobsFromJSON(
  jsonString: string,
): SafeParseResult<Jobs, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Jobs$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Jobs' from JSON`,
  );
}

/** @internal */
export const CronListResponseBody$inboundSchema: z.ZodType<
  CronListResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  jobs: z.array(z.lazy(() => Jobs$inboundSchema)).optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CronListResponseBody$ {
  /** @deprecated use `CronListResponseBody$inboundSchema` instead. */
  export const inboundSchema = CronListResponseBody$inboundSchema;
}

export function cronListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CronListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CronListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CronListResponseBody' from JSON`,
  );
}
