/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type CronDeleteRequest = {
  id: string;
};

/** @internal */
export type CronDeleteRequest$Outbound = {
  id: string;
};

/** @internal */
export const CronDeleteRequest$outboundSchema: z.ZodType<
  CronDeleteRequest$Outbound,
  z.ZodTypeDef,
  CronDeleteRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CronDeleteRequest$ {
  /** @deprecated use `CronDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = CronDeleteRequest$outboundSchema;
  /** @deprecated use `CronDeleteRequest$Outbound` instead. */
  export type Outbound = CronDeleteRequest$Outbound;
}

export function cronDeleteRequestToJSON(
  cronDeleteRequest: CronDeleteRequest,
): string {
  return JSON.stringify(
    CronDeleteRequest$outboundSchema.parse(cronDeleteRequest),
  );
}
