/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CronGetRequest = {
  /**
   * Cron job ID
   */
  id: string;
};

/**
 * Default Response
 */
export type CronGetCronResponseBody = {
  error?: string | undefined;
};

export type Notifications = {};

/**
 * Default Response
 */
export type CronGetResponseBody = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  enabled?: boolean | undefined;
  jobType?: string | undefined;
  message?: string | undefined;
  script?: string | undefined;
  cron?: string | undefined;
  every?: number | undefined;
  channel?: string | undefined;
  agent?: string | undefined;
  workspacePath?: string | undefined;
  notifications?: Notifications | undefined;
  lastRun?: number | undefined;
  lastStatus?: string | undefined;
  lastError?: string | undefined;
  lastOutput?: string | undefined;
  nextRun?: number | undefined;
  createdAt?: number | undefined;
  updatedAt?: number | undefined;
};

export type CronGetResponse = CronGetResponseBody | CronGetCronResponseBody;

/** @internal */
export type CronGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const CronGetRequest$outboundSchema: z.ZodType<
  CronGetRequest$Outbound,
  z.ZodTypeDef,
  CronGetRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CronGetRequest$ {
  /** @deprecated use `CronGetRequest$outboundSchema` instead. */
  export const outboundSchema = CronGetRequest$outboundSchema;
  /** @deprecated use `CronGetRequest$Outbound` instead. */
  export type Outbound = CronGetRequest$Outbound;
}

export function cronGetRequestToJSON(cronGetRequest: CronGetRequest): string {
  return JSON.stringify(CronGetRequest$outboundSchema.parse(cronGetRequest));
}

/** @internal */
export const CronGetCronResponseBody$inboundSchema: z.ZodType<
  CronGetCronResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CronGetCronResponseBody$ {
  /** @deprecated use `CronGetCronResponseBody$inboundSchema` instead. */
  export const inboundSchema = CronGetCronResponseBody$inboundSchema;
}

export function cronGetCronResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CronGetCronResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CronGetCronResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CronGetCronResponseBody' from JSON`,
  );
}

/** @internal */
export const Notifications$inboundSchema: z.ZodType<
  Notifications,
  z.ZodTypeDef,
  unknown
> = z.object({});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Notifications$ {
  /** @deprecated use `Notifications$inboundSchema` instead. */
  export const inboundSchema = Notifications$inboundSchema;
}

export function notificationsFromJSON(
  jsonString: string,
): SafeParseResult<Notifications, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Notifications$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Notifications' from JSON`,
  );
}

/** @internal */
export const CronGetResponseBody$inboundSchema: z.ZodType<
  CronGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  enabled: z.boolean().optional(),
  job_type: z.string().optional(),
  message: z.string().optional(),
  script: z.string().optional(),
  cron: z.string().optional(),
  every: z.number().optional(),
  channel: z.string().optional(),
  agent: z.string().optional(),
  workspace_path: z.string().optional(),
  notifications: z.lazy(() => Notifications$inboundSchema).optional(),
  last_run: z.number().optional(),
  last_status: z.string().optional(),
  last_error: z.string().optional(),
  last_output: z.string().optional(),
  next_run: z.number().optional(),
  created_at: z.number().optional(),
  updated_at: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "job_type": "jobType",
    "workspace_path": "workspacePath",
    "last_run": "lastRun",
    "last_status": "lastStatus",
    "last_error": "lastError",
    "last_output": "lastOutput",
    "next_run": "nextRun",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CronGetResponseBody$ {
  /** @deprecated use `CronGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = CronGetResponseBody$inboundSchema;
}

export function cronGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CronGetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CronGetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CronGetResponseBody' from JSON`,
  );
}

/** @internal */
export const CronGetResponse$inboundSchema: z.ZodType<
  CronGetResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => CronGetResponseBody$inboundSchema),
  z.lazy(() => CronGetCronResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CronGetResponse$ {
  /** @deprecated use `CronGetResponse$inboundSchema` instead. */
  export const inboundSchema = CronGetResponse$inboundSchema;
}

export function cronGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<CronGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CronGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CronGetResponse' from JSON`,
  );
}
