/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteApiOfficialRegistryServersNameCacheRequest = {
  name: string;
};

/** @internal */
export type DeleteApiOfficialRegistryServersNameCacheRequest$Outbound = {
  name: string;
};

/** @internal */
export const DeleteApiOfficialRegistryServersNameCacheRequest$outboundSchema:
  z.ZodType<
    DeleteApiOfficialRegistryServersNameCacheRequest$Outbound,
    z.ZodTypeDef,
    DeleteApiOfficialRegistryServersNameCacheRequest
  > = z.object({
    name: z.string(),
  });

export function deleteApiOfficialRegistryServersNameCacheRequestToJSON(
  deleteApiOfficialRegistryServersNameCacheRequest:
    DeleteApiOfficialRegistryServersNameCacheRequest,
): string {
  return JSON.stringify(
    DeleteApiOfficialRegistryServersNameCacheRequest$outboundSchema.parse(
      deleteApiOfficialRegistryServersNameCacheRequest,
    ),
  );
}
