/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteApiKanbanTasksTaskIdCommentsCommentIdRequest = {
  commentId: string;
  taskId: string;
};

/** @internal */
export type DeleteApiKanbanTasksTaskIdCommentsCommentIdRequest$Outbound = {
  commentId: string;
  taskId: string;
};

/** @internal */
export const DeleteApiKanbanTasksTaskIdCommentsCommentIdRequest$outboundSchema:
  z.ZodType<
    DeleteApiKanbanTasksTaskIdCommentsCommentIdRequest$Outbound,
    z.ZodTypeDef,
    DeleteApiKanbanTasksTaskIdCommentsCommentIdRequest
  > = z.object({
    commentId: z.string(),
    taskId: z.string(),
  });

export function deleteApiKanbanTasksTaskIdCommentsCommentIdRequestToJSON(
  deleteApiKanbanTasksTaskIdCommentsCommentIdRequest:
    DeleteApiKanbanTasksTaskIdCommentsCommentIdRequest,
): string {
  return JSON.stringify(
    DeleteApiKanbanTasksTaskIdCommentsCommentIdRequest$outboundSchema.parse(
      deleteApiKanbanTasksTaskIdCommentsCommentIdRequest,
    ),
  );
}
