/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteApiQueueTasksIdRequest = {
  id: string;
};

/** @internal */
export type DeleteApiQueueTasksIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteApiQueueTasksIdRequest$outboundSchema: z.ZodType<
  DeleteApiQueueTasksIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiQueueTasksIdRequest
> = z.object({
  id: z.string(),
});

export function deleteApiQueueTasksIdRequestToJSON(
  deleteApiQueueTasksIdRequest: DeleteApiQueueTasksIdRequest,
): string {
  return JSON.stringify(
    DeleteApiQueueTasksIdRequest$outboundSchema.parse(
      deleteApiQueueTasksIdRequest,
    ),
  );
}
