/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ExecutorsGetDiscoverSessionsRequest = {
  type: string;
};

/** @internal */
export type ExecutorsGetDiscoverSessionsRequest$Outbound = {
  type: string;
};

/** @internal */
export const ExecutorsGetDiscoverSessionsRequest$outboundSchema: z.ZodType<
  ExecutorsGetDiscoverSessionsRequest$Outbound,
  z.ZodTypeDef,
  ExecutorsGetDiscoverSessionsRequest
> = z.object({
  type: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecutorsGetDiscoverSessionsRequest$ {
  /** @deprecated use `ExecutorsGetDiscoverSessionsRequest$outboundSchema` instead. */
  export const outboundSchema =
    ExecutorsGetDiscoverSessionsRequest$outboundSchema;
  /** @deprecated use `ExecutorsGetDiscoverSessionsRequest$Outbound` instead. */
  export type Outbound = ExecutorsGetDiscoverSessionsRequest$Outbound;
}

export function executorsGetDiscoverSessionsRequestToJSON(
  executorsGetDiscoverSessionsRequest: ExecutorsGetDiscoverSessionsRequest,
): string {
  return JSON.stringify(
    ExecutorsGetDiscoverSessionsRequest$outboundSchema.parse(
      executorsGetDiscoverSessionsRequest,
    ),
  );
}
