/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ExecutorsGetCommandsRequest = {
  type: string;
};

/** @internal */
export type ExecutorsGetCommandsRequest$Outbound = {
  type: string;
};

/** @internal */
export const ExecutorsGetCommandsRequest$outboundSchema: z.ZodType<
  ExecutorsGetCommandsRequest$Outbound,
  z.ZodTypeDef,
  ExecutorsGetCommandsRequest
> = z.object({
  type: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecutorsGetCommandsRequest$ {
  /** @deprecated use `ExecutorsGetCommandsRequest$outboundSchema` instead. */
  export const outboundSchema = ExecutorsGetCommandsRequest$outboundSchema;
  /** @deprecated use `ExecutorsGetCommandsRequest$Outbound` instead. */
  export type Outbound = ExecutorsGetCommandsRequest$Outbound;
}

export function executorsGetCommandsRequestToJSON(
  executorsGetCommandsRequest: ExecutorsGetCommandsRequest,
): string {
  return JSON.stringify(
    ExecutorsGetCommandsRequest$outboundSchema.parse(
      executorsGetCommandsRequest,
    ),
  );
}
