/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiRewardTypesRequest = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type GetApiRewardTypesRewardResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

export const GetApiRewardTypesSource = {
  Builtin: "builtin",
  Custom: "custom",
} as const;
export type GetApiRewardTypesSource = ClosedEnum<
  typeof GetApiRewardTypesSource
>;

export type GetApiRewardTypesTypes = {
  description?: string | undefined;
  name?: string | undefined;
  promptPath?: string | undefined;
  source?: GetApiRewardTypesSource | undefined;
  weightDefault?: number | null | undefined;
};

/**
 * Default Response
 */
export type GetApiRewardTypesResponseBody = {
  count?: number | undefined;
  success?: boolean | undefined;
  types?: Array<GetApiRewardTypesTypes> | undefined;
};

export type GetApiRewardTypesResponse =
  | GetApiRewardTypesResponseBody
  | GetApiRewardTypesRewardResponseBody;

/** @internal */
export type GetApiRewardTypesRequest$Outbound = {
  workspace_path: string;
};

/** @internal */
export const GetApiRewardTypesRequest$outboundSchema: z.ZodType<
  GetApiRewardTypesRequest$Outbound,
  z.ZodTypeDef,
  GetApiRewardTypesRequest
> = z.object({
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});

export function getApiRewardTypesRequestToJSON(
  getApiRewardTypesRequest: GetApiRewardTypesRequest,
): string {
  return JSON.stringify(
    GetApiRewardTypesRequest$outboundSchema.parse(getApiRewardTypesRequest),
  );
}

/** @internal */
export const GetApiRewardTypesRewardResponseBody$inboundSchema: z.ZodType<
  GetApiRewardTypesRewardResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function getApiRewardTypesRewardResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiRewardTypesRewardResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiRewardTypesRewardResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiRewardTypesRewardResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiRewardTypesSource$inboundSchema: z.ZodNativeEnum<
  typeof GetApiRewardTypesSource
> = z.nativeEnum(GetApiRewardTypesSource);

/** @internal */
export const GetApiRewardTypesTypes$inboundSchema: z.ZodType<
  GetApiRewardTypesTypes,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().optional(),
  name: z.string().optional(),
  prompt_path: z.string().optional(),
  source: GetApiRewardTypesSource$inboundSchema.optional(),
  weight_default: z.nullable(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    "prompt_path": "promptPath",
    "weight_default": "weightDefault",
  });
});

export function getApiRewardTypesTypesFromJSON(
  jsonString: string,
): SafeParseResult<GetApiRewardTypesTypes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiRewardTypesTypes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiRewardTypesTypes' from JSON`,
  );
}

/** @internal */
export const GetApiRewardTypesResponseBody$inboundSchema: z.ZodType<
  GetApiRewardTypesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().optional(),
  success: z.boolean().optional(),
  types: z.array(z.lazy(() => GetApiRewardTypesTypes$inboundSchema)).optional(),
});

export function getApiRewardTypesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiRewardTypesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiRewardTypesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiRewardTypesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiRewardTypesResponse$inboundSchema: z.ZodType<
  GetApiRewardTypesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetApiRewardTypesResponseBody$inboundSchema),
  z.lazy(() => GetApiRewardTypesRewardResponseBody$inboundSchema),
]);

export function getApiRewardTypesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiRewardTypesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiRewardTypesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiRewardTypesResponse' from JSON`,
  );
}
