/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApiUsageServerServerIdRequest = {
  serverId: string;
};

/** @internal */
export type GetApiUsageServerServerIdRequest$Outbound = {
  serverId: string;
};

/** @internal */
export const GetApiUsageServerServerIdRequest$outboundSchema: z.ZodType<
  GetApiUsageServerServerIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiUsageServerServerIdRequest
> = z.object({
  serverId: z.string(),
});

export function getApiUsageServerServerIdRequestToJSON(
  getApiUsageServerServerIdRequest: GetApiUsageServerServerIdRequest,
): string {
  return JSON.stringify(
    GetApiUsageServerServerIdRequest$outboundSchema.parse(
      getApiUsageServerServerIdRequest,
    ),
  );
}
