/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApiProvidersIdModelsRequest = {
  id: string;
};

/** @internal */
export type GetApiProvidersIdModelsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiProvidersIdModelsRequest$outboundSchema: z.ZodType<
  GetApiProvidersIdModelsRequest$Outbound,
  z.ZodTypeDef,
  GetApiProvidersIdModelsRequest
> = z.object({
  id: z.string(),
});

export function getApiProvidersIdModelsRequestToJSON(
  getApiProvidersIdModelsRequest: GetApiProvidersIdModelsRequest,
): string {
  return JSON.stringify(
    GetApiProvidersIdModelsRequest$outboundSchema.parse(
      getApiProvidersIdModelsRequest,
    ),
  );
}
