/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiSkillInfoIdOrSlugRequest = {
  /**
   * Skill ID or slug
   */
  idOrSlug: string;
};

/**
 * Default Response
 */
export type GetApiSkillInfoIdOrSlugSkillResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

export type Skill = {
  description?: string | undefined;
  downloadsCount?: number | undefined;
  favoritesCount?: number | undefined;
  id?: string | undefined;
  name?: string | undefined;
  skillType?: string | undefined;
  slug?: string | undefined;
  version?: string | undefined;
};

/**
 * Default Response
 */
export type GetApiSkillInfoIdOrSlugResponseBody = {
  skill?: Skill | undefined;
  success?: boolean | undefined;
};

export type GetApiSkillInfoIdOrSlugResponse =
  | GetApiSkillInfoIdOrSlugResponseBody
  | GetApiSkillInfoIdOrSlugSkillResponseBody;

/** @internal */
export type GetApiSkillInfoIdOrSlugRequest$Outbound = {
  idOrSlug: string;
};

/** @internal */
export const GetApiSkillInfoIdOrSlugRequest$outboundSchema: z.ZodType<
  GetApiSkillInfoIdOrSlugRequest$Outbound,
  z.ZodTypeDef,
  GetApiSkillInfoIdOrSlugRequest
> = z.object({
  idOrSlug: z.string(),
});

export function getApiSkillInfoIdOrSlugRequestToJSON(
  getApiSkillInfoIdOrSlugRequest: GetApiSkillInfoIdOrSlugRequest,
): string {
  return JSON.stringify(
    GetApiSkillInfoIdOrSlugRequest$outboundSchema.parse(
      getApiSkillInfoIdOrSlugRequest,
    ),
  );
}

/** @internal */
export const GetApiSkillInfoIdOrSlugSkillResponseBody$inboundSchema: z.ZodType<
  GetApiSkillInfoIdOrSlugSkillResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function getApiSkillInfoIdOrSlugSkillResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetApiSkillInfoIdOrSlugSkillResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiSkillInfoIdOrSlugSkillResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetApiSkillInfoIdOrSlugSkillResponseBody' from JSON`,
  );
}

/** @internal */
export const Skill$inboundSchema: z.ZodType<Skill, z.ZodTypeDef, unknown> = z
  .object({
    description: z.string().optional(),
    downloads_count: z.number().optional(),
    favorites_count: z.number().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    skill_type: z.string().optional(),
    slug: z.string().optional(),
    version: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "downloads_count": "downloadsCount",
      "favorites_count": "favoritesCount",
      "skill_type": "skillType",
    });
  });

export function skillFromJSON(
  jsonString: string,
): SafeParseResult<Skill, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Skill$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Skill' from JSON`,
  );
}

/** @internal */
export const GetApiSkillInfoIdOrSlugResponseBody$inboundSchema: z.ZodType<
  GetApiSkillInfoIdOrSlugResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  skill: z.lazy(() => Skill$inboundSchema).optional(),
  success: z.boolean().optional(),
});

export function getApiSkillInfoIdOrSlugResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiSkillInfoIdOrSlugResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiSkillInfoIdOrSlugResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiSkillInfoIdOrSlugResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiSkillInfoIdOrSlugResponse$inboundSchema: z.ZodType<
  GetApiSkillInfoIdOrSlugResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetApiSkillInfoIdOrSlugResponseBody$inboundSchema),
  z.lazy(() => GetApiSkillInfoIdOrSlugSkillResponseBody$inboundSchema),
]);

export function getApiSkillInfoIdOrSlugResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiSkillInfoIdOrSlugResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiSkillInfoIdOrSlugResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiSkillInfoIdOrSlugResponse' from JSON`,
  );
}
