/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiWorkspacesDetectRequest = {
  /**
   * Folder path to detect
   */
  path: string;
};

/**
 * Default Response
 */
export type GetApiWorkspacesDetectWorkspacesResponseResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type GetApiWorkspacesDetectWorkspacesResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type GetApiWorkspacesDetectResponseBody = {
  folderName?: string | undefined;
  hasGit?: boolean | undefined;
  hasViben?: boolean | undefined;
  path?: string | undefined;
};

export type GetApiWorkspacesDetectResponse =
  | GetApiWorkspacesDetectResponseBody
  | GetApiWorkspacesDetectWorkspacesResponseBody
  | GetApiWorkspacesDetectWorkspacesResponseResponseBody;

/** @internal */
export type GetApiWorkspacesDetectRequest$Outbound = {
  path: string;
};

/** @internal */
export const GetApiWorkspacesDetectRequest$outboundSchema: z.ZodType<
  GetApiWorkspacesDetectRequest$Outbound,
  z.ZodTypeDef,
  GetApiWorkspacesDetectRequest
> = z.object({
  path: z.string(),
});

export function getApiWorkspacesDetectRequestToJSON(
  getApiWorkspacesDetectRequest: GetApiWorkspacesDetectRequest,
): string {
  return JSON.stringify(
    GetApiWorkspacesDetectRequest$outboundSchema.parse(
      getApiWorkspacesDetectRequest,
    ),
  );
}

/** @internal */
export const GetApiWorkspacesDetectWorkspacesResponseResponseBody$inboundSchema:
  z.ZodType<
    GetApiWorkspacesDetectWorkspacesResponseResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
  });

export function getApiWorkspacesDetectWorkspacesResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetApiWorkspacesDetectWorkspacesResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiWorkspacesDetectWorkspacesResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetApiWorkspacesDetectWorkspacesResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiWorkspacesDetectWorkspacesResponseBody$inboundSchema:
  z.ZodType<
    GetApiWorkspacesDetectWorkspacesResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
  });

export function getApiWorkspacesDetectWorkspacesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetApiWorkspacesDetectWorkspacesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiWorkspacesDetectWorkspacesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetApiWorkspacesDetectWorkspacesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiWorkspacesDetectResponseBody$inboundSchema: z.ZodType<
  GetApiWorkspacesDetectResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  folder_name: z.string().optional(),
  has_git: z.boolean().optional(),
  has_viben: z.boolean().optional(),
  path: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "folder_name": "folderName",
    "has_git": "hasGit",
    "has_viben": "hasViben",
  });
});

export function getApiWorkspacesDetectResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiWorkspacesDetectResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiWorkspacesDetectResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiWorkspacesDetectResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiWorkspacesDetectResponse$inboundSchema: z.ZodType<
  GetApiWorkspacesDetectResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetApiWorkspacesDetectResponseBody$inboundSchema),
  z.lazy(() => GetApiWorkspacesDetectWorkspacesResponseBody$inboundSchema),
  z.lazy(() =>
    GetApiWorkspacesDetectWorkspacesResponseResponseBody$inboundSchema
  ),
]);

export function getApiWorkspacesDetectResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiWorkspacesDetectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiWorkspacesDetectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiWorkspacesDetectResponse' from JSON`,
  );
}
