/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiPageServeRequest = {
  /**
   * File path within the page (optional)
   */
  path?: string | undefined;
  /**
   * Page uid (required)
   */
  uid: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type GetApiPageServePageResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

/**
 * Default Response
 */
export type GetApiPageServeResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

export type GetApiPageServeResponse =
  | ReadableStream<Uint8Array>
  | GetApiPageServeResponseBody
  | GetApiPageServePageResponseBody;

/** @internal */
export type GetApiPageServeRequest$Outbound = {
  path?: string | undefined;
  uid: string;
  workspace_path: string;
};

/** @internal */
export const GetApiPageServeRequest$outboundSchema: z.ZodType<
  GetApiPageServeRequest$Outbound,
  z.ZodTypeDef,
  GetApiPageServeRequest
> = z.object({
  path: z.string().optional(),
  uid: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});

export function getApiPageServeRequestToJSON(
  getApiPageServeRequest: GetApiPageServeRequest,
): string {
  return JSON.stringify(
    GetApiPageServeRequest$outboundSchema.parse(getApiPageServeRequest),
  );
}

/** @internal */
export const GetApiPageServePageResponseBody$inboundSchema: z.ZodType<
  GetApiPageServePageResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function getApiPageServePageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiPageServePageResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiPageServePageResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiPageServePageResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiPageServeResponseBody$inboundSchema: z.ZodType<
  GetApiPageServeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function getApiPageServeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiPageServeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiPageServeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiPageServeResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiPageServeResponse$inboundSchema: z.ZodType<
  GetApiPageServeResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.instanceof(ReadableStream<Uint8Array>),
  z.lazy(() => GetApiPageServeResponseBody$inboundSchema),
  z.lazy(() => GetApiPageServePageResponseBody$inboundSchema),
]);

export function getApiPageServeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiPageServeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiPageServeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiPageServeResponse' from JSON`,
  );
}
