/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type GetApiExecutorsTypeCommandsCommandIdRequest = {
  commandId: string;
  type: string;
};

/** @internal */
export type GetApiExecutorsTypeCommandsCommandIdRequest$Outbound = {
  command_id: string;
  type: string;
};

/** @internal */
export const GetApiExecutorsTypeCommandsCommandIdRequest$outboundSchema:
  z.ZodType<
    GetApiExecutorsTypeCommandsCommandIdRequest$Outbound,
    z.ZodTypeDef,
    GetApiExecutorsTypeCommandsCommandIdRequest
  > = z.object({
    commandId: z.string(),
    type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      commandId: "command_id",
    });
  });

export function getApiExecutorsTypeCommandsCommandIdRequestToJSON(
  getApiExecutorsTypeCommandsCommandIdRequest:
    GetApiExecutorsTypeCommandsCommandIdRequest,
): string {
  return JSON.stringify(
    GetApiExecutorsTypeCommandsCommandIdRequest$outboundSchema.parse(
      getApiExecutorsTypeCommandsCommandIdRequest,
    ),
  );
}
