/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiChannelsIdRequest = {
  /**
   * Channel ID
   */
  id: string;
};

/**
 * Default Response
 */
export type GetApiChannelsIdChannelsResponseBody = {
  error?: string | undefined;
};

export type AgentBinding = {};

export type Config = {};

/**
 * Default Response
 */
export type GetApiChannelsIdResponseBody = {
  agentBinding?: AgentBinding | undefined;
  channelType?: string | undefined;
  config?: Config | undefined;
  createdAt?: Date | undefined;
  enabled?: boolean | undefined;
  id?: string | undefined;
  isDefault?: boolean | undefined;
  name?: string | undefined;
  notificationMode?: string | undefined;
  updatedAt?: Date | undefined;
};

export type GetApiChannelsIdResponse =
  | GetApiChannelsIdResponseBody
  | GetApiChannelsIdChannelsResponseBody;

/** @internal */
export type GetApiChannelsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiChannelsIdRequest$outboundSchema: z.ZodType<
  GetApiChannelsIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiChannelsIdRequest
> = z.object({
  id: z.string(),
});

export function getApiChannelsIdRequestToJSON(
  getApiChannelsIdRequest: GetApiChannelsIdRequest,
): string {
  return JSON.stringify(
    GetApiChannelsIdRequest$outboundSchema.parse(getApiChannelsIdRequest),
  );
}

/** @internal */
export const GetApiChannelsIdChannelsResponseBody$inboundSchema: z.ZodType<
  GetApiChannelsIdChannelsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});

export function getApiChannelsIdChannelsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiChannelsIdChannelsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiChannelsIdChannelsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiChannelsIdChannelsResponseBody' from JSON`,
  );
}

/** @internal */
export const AgentBinding$inboundSchema: z.ZodType<
  AgentBinding,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function agentBindingFromJSON(
  jsonString: string,
): SafeParseResult<AgentBinding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentBinding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentBinding' from JSON`,
  );
}

/** @internal */
export const Config$inboundSchema: z.ZodType<Config, z.ZodTypeDef, unknown> = z
  .object({});

export function configFromJSON(
  jsonString: string,
): SafeParseResult<Config, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Config$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Config' from JSON`,
  );
}

/** @internal */
export const GetApiChannelsIdResponseBody$inboundSchema: z.ZodType<
  GetApiChannelsIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  agent_binding: z.lazy(() => AgentBinding$inboundSchema).optional(),
  channel_type: z.string().optional(),
  config: z.lazy(() => Config$inboundSchema).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  enabled: z.boolean().optional(),
  id: z.string().optional(),
  is_default: z.boolean().optional(),
  name: z.string().optional(),
  notification_mode: z.string().optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "agent_binding": "agentBinding",
    "channel_type": "channelType",
    "created_at": "createdAt",
    "is_default": "isDefault",
    "notification_mode": "notificationMode",
    "updated_at": "updatedAt",
  });
});

export function getApiChannelsIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiChannelsIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiChannelsIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiChannelsIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiChannelsIdResponse$inboundSchema: z.ZodType<
  GetApiChannelsIdResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetApiChannelsIdResponseBody$inboundSchema),
  z.lazy(() => GetApiChannelsIdChannelsResponseBody$inboundSchema),
]);

export function getApiChannelsIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiChannelsIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiChannelsIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiChannelsIdResponse' from JSON`,
  );
}
