/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type GetApiPreviewStartSseRequest = {
  /**
   * Custom command to run (e.g., 'npm run serve')
   */
  command?: string | undefined;
  /**
   * Preferred port (optional)
   */
  port?: string | undefined;
  /**
   * Regex pattern to detect server ready in stdout/stderr
   */
  readyPattern?: string | undefined;
  /**
   * Task identifier
   */
  taskId: string;
  /**
   * Startup timeout in milliseconds
   */
  timeout?: string | undefined;
  /**
   * Working directory path
   */
  workDir: string;
};

/** @internal */
export type GetApiPreviewStartSseRequest$Outbound = {
  command?: string | undefined;
  port?: string | undefined;
  ready_pattern?: string | undefined;
  task_id: string;
  timeout?: string | undefined;
  work_dir: string;
};

/** @internal */
export const GetApiPreviewStartSseRequest$outboundSchema: z.ZodType<
  GetApiPreviewStartSseRequest$Outbound,
  z.ZodTypeDef,
  GetApiPreviewStartSseRequest
> = z.object({
  command: z.string().optional(),
  port: z.string().optional(),
  readyPattern: z.string().optional(),
  taskId: z.string(),
  timeout: z.string().optional(),
  workDir: z.string(),
}).transform((v) => {
  return remap$(v, {
    readyPattern: "ready_pattern",
    taskId: "task_id",
    workDir: "work_dir",
  });
});

export function getApiPreviewStartSseRequestToJSON(
  getApiPreviewStartSseRequest: GetApiPreviewStartSseRequest,
): string {
  return JSON.stringify(
    GetApiPreviewStartSseRequest$outboundSchema.parse(
      getApiPreviewStartSseRequest,
    ),
  );
}
