/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApiGroupChatsIdPicturesRequest = {
  id: string;
};

/** @internal */
export type GetApiGroupChatsIdPicturesRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiGroupChatsIdPicturesRequest$outboundSchema: z.ZodType<
  GetApiGroupChatsIdPicturesRequest$Outbound,
  z.ZodTypeDef,
  GetApiGroupChatsIdPicturesRequest
> = z.object({
  id: z.string(),
});

export function getApiGroupChatsIdPicturesRequestToJSON(
  getApiGroupChatsIdPicturesRequest: GetApiGroupChatsIdPicturesRequest,
): string {
  return JSON.stringify(
    GetApiGroupChatsIdPicturesRequest$outboundSchema.parse(
      getApiGroupChatsIdPicturesRequest,
    ),
  );
}
