/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApiUsageSourceSourceIdRequest = {
  sourceId: string;
};

/** @internal */
export type GetApiUsageSourceSourceIdRequest$Outbound = {
  sourceId: string;
};

/** @internal */
export const GetApiUsageSourceSourceIdRequest$outboundSchema: z.ZodType<
  GetApiUsageSourceSourceIdRequest$Outbound,
  z.ZodTypeDef,
  GetApiUsageSourceSourceIdRequest
> = z.object({
  sourceId: z.string(),
});

export function getApiUsageSourceSourceIdRequestToJSON(
  getApiUsageSourceSourceIdRequest: GetApiUsageSourceSourceIdRequest,
): string {
  return JSON.stringify(
    GetApiUsageSourceSourceIdRequest$outboundSchema.parse(
      getApiUsageSourceSourceIdRequest,
    ),
  );
}
