/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiSessionsSessionData = {};

export type Sessions = {
  agentId?: string | undefined;
  createdAt?: Date | undefined;
  id?: string | undefined;
  prompt?: string | undefined;
  sessionData?: GetApiSessionsSessionData | undefined;
  status?: string | undefined;
  taskId?: string | undefined;
  updatedAt?: Date | undefined;
};

/**
 * Default Response
 */
export type GetApiSessionsResponseBody = {
  sessions?: Array<Sessions> | undefined;
};

/** @internal */
export const GetApiSessionsSessionData$inboundSchema: z.ZodType<
  GetApiSessionsSessionData,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function getApiSessionsSessionDataFromJSON(
  jsonString: string,
): SafeParseResult<GetApiSessionsSessionData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiSessionsSessionData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiSessionsSessionData' from JSON`,
  );
}

/** @internal */
export const Sessions$inboundSchema: z.ZodType<
  Sessions,
  z.ZodTypeDef,
  unknown
> = z.object({
  agent_id: z.string().optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  id: z.string().optional(),
  prompt: z.string().optional(),
  session_data: z.lazy(() => GetApiSessionsSessionData$inboundSchema)
    .optional(),
  status: z.string().optional(),
  task_id: z.string().optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "agent_id": "agentId",
    "created_at": "createdAt",
    "session_data": "sessionData",
    "task_id": "taskId",
    "updated_at": "updatedAt",
  });
});

export function sessionsFromJSON(
  jsonString: string,
): SafeParseResult<Sessions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sessions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sessions' from JSON`,
  );
}

/** @internal */
export const GetApiSessionsResponseBody$inboundSchema: z.ZodType<
  GetApiSessionsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  sessions: z.array(z.lazy(() => Sessions$inboundSchema)).optional(),
});

export function getApiSessionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiSessionsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiSessionsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiSessionsResponseBody' from JSON`,
  );
}
