/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiAgentRequest = {
  /**
   * Include global agents (default: true)
   */
  includeGlobal?: string | undefined;
  /**
   * Workspace path to include workspace agents
   */
  workspacePath?: string | undefined;
};

export const Source = {
  Global: "global",
  Workspace: "workspace",
} as const;
export type Source = ClosedEnum<typeof Source>;

export type Agents = {
  agentDir?: string | undefined;
  agentType?: string | undefined;
  configPath?: string | undefined;
  description?: string | undefined;
  executorType?: string | undefined;
  id?: string | undefined;
  model?: string | undefined;
  name?: string | undefined;
  provider?: string | undefined;
  source?: Source | undefined;
  workspacePath?: string | undefined;
};

/**
 * Default Response
 */
export type GetApiAgentResponseBody = {
  agents?: Array<Agents> | undefined;
  total?: number | undefined;
};

/** @internal */
export type GetApiAgentRequest$Outbound = {
  include_global?: string | undefined;
  workspace_path?: string | undefined;
};

/** @internal */
export const GetApiAgentRequest$outboundSchema: z.ZodType<
  GetApiAgentRequest$Outbound,
  z.ZodTypeDef,
  GetApiAgentRequest
> = z.object({
  includeGlobal: z.string().optional(),
  workspacePath: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    includeGlobal: "include_global",
    workspacePath: "workspace_path",
  });
});

export function getApiAgentRequestToJSON(
  getApiAgentRequest: GetApiAgentRequest,
): string {
  return JSON.stringify(
    GetApiAgentRequest$outboundSchema.parse(getApiAgentRequest),
  );
}

/** @internal */
export const Source$inboundSchema: z.ZodNativeEnum<typeof Source> = z
  .nativeEnum(Source);

/** @internal */
export const Agents$inboundSchema: z.ZodType<Agents, z.ZodTypeDef, unknown> = z
  .object({
    agent_dir: z.string().optional(),
    agent_type: z.string().optional(),
    config_path: z.string().optional(),
    description: z.string().optional(),
    executor_type: z.string().optional(),
    id: z.string().optional(),
    model: z.string().optional(),
    name: z.string().optional(),
    provider: z.string().optional(),
    source: Source$inboundSchema.optional(),
    workspace_path: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "agent_dir": "agentDir",
      "agent_type": "agentType",
      "config_path": "configPath",
      "executor_type": "executorType",
      "workspace_path": "workspacePath",
    });
  });

export function agentsFromJSON(
  jsonString: string,
): SafeParseResult<Agents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Agents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Agents' from JSON`,
  );
}

/** @internal */
export const GetApiAgentResponseBody$inboundSchema: z.ZodType<
  GetApiAgentResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  agents: z.array(z.lazy(() => Agents$inboundSchema)).optional(),
  total: z.number().optional(),
});

export function getApiAgentResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiAgentResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiAgentResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiAgentResponseBody' from JSON`,
  );
}
