/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type GetApiTaskExecutionStreamRequest = {
  /**
   * Task directory or ID (required)
   */
  taskDir: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/** @internal */
export type GetApiTaskExecutionStreamRequest$Outbound = {
  task_dir: string;
  workspace_path: string;
};

/** @internal */
export const GetApiTaskExecutionStreamRequest$outboundSchema: z.ZodType<
  GetApiTaskExecutionStreamRequest$Outbound,
  z.ZodTypeDef,
  GetApiTaskExecutionStreamRequest
> = z.object({
  taskDir: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskDir: "task_dir",
    workspacePath: "workspace_path",
  });
});

export function getApiTaskExecutionStreamRequestToJSON(
  getApiTaskExecutionStreamRequest: GetApiTaskExecutionStreamRequest,
): string {
  return JSON.stringify(
    GetApiTaskExecutionStreamRequest$outboundSchema.parse(
      getApiTaskExecutionStreamRequest,
    ),
  );
}
