/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApiOfficialRegistryServersNameVersionsRequest = {
  name: string;
};

/** @internal */
export type GetApiOfficialRegistryServersNameVersionsRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetApiOfficialRegistryServersNameVersionsRequest$outboundSchema:
  z.ZodType<
    GetApiOfficialRegistryServersNameVersionsRequest$Outbound,
    z.ZodTypeDef,
    GetApiOfficialRegistryServersNameVersionsRequest
  > = z.object({
    name: z.string(),
  });

export function getApiOfficialRegistryServersNameVersionsRequestToJSON(
  getApiOfficialRegistryServersNameVersionsRequest:
    GetApiOfficialRegistryServersNameVersionsRequest,
): string {
  return JSON.stringify(
    GetApiOfficialRegistryServersNameVersionsRequest$outboundSchema.parse(
      getApiOfficialRegistryServersNameVersionsRequest,
    ),
  );
}
