/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApiModelsIdConfigRequest = {
  id: string;
};

/** @internal */
export type GetApiModelsIdConfigRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiModelsIdConfigRequest$outboundSchema: z.ZodType<
  GetApiModelsIdConfigRequest$Outbound,
  z.ZodTypeDef,
  GetApiModelsIdConfigRequest
> = z.object({
  id: z.string(),
});

export function getApiModelsIdConfigRequestToJSON(
  getApiModelsIdConfigRequest: GetApiModelsIdConfigRequest,
): string {
  return JSON.stringify(
    GetApiModelsIdConfigRequest$outboundSchema.parse(
      getApiModelsIdConfigRequest,
    ),
  );
}
