/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetApiSkillViewNameQueryParamTarget = {
  Agent: "agent",
  Global: "global",
  Claude: "claude",
  Custom: "custom",
} as const;
export type GetApiSkillViewNameQueryParamTarget = ClosedEnum<
  typeof GetApiSkillViewNameQueryParamTarget
>;

export type GetApiSkillViewNameRequest = {
  agentId?: string | undefined;
  customPath?: string | undefined;
  /**
   * Skill name
   */
  name: string;
  target?: GetApiSkillViewNameQueryParamTarget | undefined;
};

/**
 * Default Response
 */
export type GetApiSkillViewNameSkillResponseBody = {
  error?: string | undefined;
};

export type GetApiSkillViewNameSkill = {
  description?: string | undefined;
  id?: string | undefined;
  name?: string | undefined;
  path?: string | undefined;
  source?: string | undefined;
  version?: string | undefined;
};

/**
 * Default Response
 */
export type GetApiSkillViewNameResponseBody = {
  skill?: GetApiSkillViewNameSkill | undefined;
};

export type GetApiSkillViewNameResponse =
  | GetApiSkillViewNameResponseBody
  | GetApiSkillViewNameSkillResponseBody;

/** @internal */
export const GetApiSkillViewNameQueryParamTarget$outboundSchema:
  z.ZodNativeEnum<typeof GetApiSkillViewNameQueryParamTarget> = z.nativeEnum(
    GetApiSkillViewNameQueryParamTarget,
  );

/** @internal */
export type GetApiSkillViewNameRequest$Outbound = {
  agent_id?: string | undefined;
  custom_path?: string | undefined;
  name: string;
  target?: string | undefined;
};

/** @internal */
export const GetApiSkillViewNameRequest$outboundSchema: z.ZodType<
  GetApiSkillViewNameRequest$Outbound,
  z.ZodTypeDef,
  GetApiSkillViewNameRequest
> = z.object({
  agentId: z.string().optional(),
  customPath: z.string().optional(),
  name: z.string(),
  target: GetApiSkillViewNameQueryParamTarget$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    agentId: "agent_id",
    customPath: "custom_path",
  });
});

export function getApiSkillViewNameRequestToJSON(
  getApiSkillViewNameRequest: GetApiSkillViewNameRequest,
): string {
  return JSON.stringify(
    GetApiSkillViewNameRequest$outboundSchema.parse(getApiSkillViewNameRequest),
  );
}

/** @internal */
export const GetApiSkillViewNameSkillResponseBody$inboundSchema: z.ZodType<
  GetApiSkillViewNameSkillResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});

export function getApiSkillViewNameSkillResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiSkillViewNameSkillResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetApiSkillViewNameSkillResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiSkillViewNameSkillResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiSkillViewNameSkill$inboundSchema: z.ZodType<
  GetApiSkillViewNameSkill,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  path: z.string().optional(),
  source: z.string().optional(),
  version: z.string().optional(),
});

export function getApiSkillViewNameSkillFromJSON(
  jsonString: string,
): SafeParseResult<GetApiSkillViewNameSkill, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiSkillViewNameSkill$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiSkillViewNameSkill' from JSON`,
  );
}

/** @internal */
export const GetApiSkillViewNameResponseBody$inboundSchema: z.ZodType<
  GetApiSkillViewNameResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  skill: z.lazy(() => GetApiSkillViewNameSkill$inboundSchema).optional(),
});

export function getApiSkillViewNameResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetApiSkillViewNameResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiSkillViewNameResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiSkillViewNameResponseBody' from JSON`,
  );
}

/** @internal */
export const GetApiSkillViewNameResponse$inboundSchema: z.ZodType<
  GetApiSkillViewNameResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetApiSkillViewNameResponseBody$inboundSchema),
  z.lazy(() => GetApiSkillViewNameSkillResponseBody$inboundSchema),
]);

export function getApiSkillViewNameResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiSkillViewNameResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiSkillViewNameResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiSkillViewNameResponse' from JSON`,
  );
}
