/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApiGroupChatsIdSessionsRequest = {
  id: string;
};

/** @internal */
export type GetApiGroupChatsIdSessionsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetApiGroupChatsIdSessionsRequest$outboundSchema: z.ZodType<
  GetApiGroupChatsIdSessionsRequest$Outbound,
  z.ZodTypeDef,
  GetApiGroupChatsIdSessionsRequest
> = z.object({
  id: z.string(),
});

export function getApiGroupChatsIdSessionsRequestToJSON(
  getApiGroupChatsIdSessionsRequest: GetApiGroupChatsIdSessionsRequest,
): string {
  return JSON.stringify(
    GetApiGroupChatsIdSessionsRequest$outboundSchema.parse(
      getApiGroupChatsIdSessionsRequest,
    ),
  );
}
