/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type GetApiAgentIdSessionsSessionIdUiMessagesRequest = {
  id: string;
  sessionId: string;
};

/** @internal */
export type GetApiAgentIdSessionsSessionIdUiMessagesRequest$Outbound = {
  id: string;
  session_id: string;
};

/** @internal */
export const GetApiAgentIdSessionsSessionIdUiMessagesRequest$outboundSchema:
  z.ZodType<
    GetApiAgentIdSessionsSessionIdUiMessagesRequest$Outbound,
    z.ZodTypeDef,
    GetApiAgentIdSessionsSessionIdUiMessagesRequest
  > = z.object({
    id: z.string(),
    sessionId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      sessionId: "session_id",
    });
  });

export function getApiAgentIdSessionsSessionIdUiMessagesRequestToJSON(
  getApiAgentIdSessionsSessionIdUiMessagesRequest:
    GetApiAgentIdSessionsSessionIdUiMessagesRequest,
): string {
  return JSON.stringify(
    GetApiAgentIdSessionsSessionIdUiMessagesRequest$outboundSchema.parse(
      getApiAgentIdSessionsSessionIdUiMessagesRequest,
    ),
  );
}
