/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApiGithubIssuesNumberRequest = {
  number: string;
};

/** @internal */
export type GetApiGithubIssuesNumberRequest$Outbound = {
  number: string;
};

/** @internal */
export const GetApiGithubIssuesNumberRequest$outboundSchema: z.ZodType<
  GetApiGithubIssuesNumberRequest$Outbound,
  z.ZodTypeDef,
  GetApiGithubIssuesNumberRequest
> = z.object({
  number: z.string(),
});

export function getApiGithubIssuesNumberRequestToJSON(
  getApiGithubIssuesNumberRequest: GetApiGithubIssuesNumberRequest,
): string {
  return JSON.stringify(
    GetApiGithubIssuesNumberRequest$outboundSchema.parse(
      getApiGithubIssuesNumberRequest,
    ),
  );
}
