/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type GithubApproveAutofixTaskRequest = {
  taskId: string;
};

/** @internal */
export type GithubApproveAutofixTaskRequest$Outbound = {
  task_id: string;
};

/** @internal */
export const GithubApproveAutofixTaskRequest$outboundSchema: z.ZodType<
  GithubApproveAutofixTaskRequest$Outbound,
  z.ZodTypeDef,
  GithubApproveAutofixTaskRequest
> = z.object({
  taskId: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GithubApproveAutofixTaskRequest$ {
  /** @deprecated use `GithubApproveAutofixTaskRequest$outboundSchema` instead. */
  export const outboundSchema = GithubApproveAutofixTaskRequest$outboundSchema;
  /** @deprecated use `GithubApproveAutofixTaskRequest$Outbound` instead. */
  export type Outbound = GithubApproveAutofixTaskRequest$Outbound;
}

export function githubApproveAutofixTaskRequestToJSON(
  githubApproveAutofixTaskRequest: GithubApproveAutofixTaskRequest,
): string {
  return JSON.stringify(
    GithubApproveAutofixTaskRequest$outboundSchema.parse(
      githubApproveAutofixTaskRequest,
    ),
  );
}
