/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GithubInvestigateIssueRequest = {
  number: string;
};

/** @internal */
export type GithubInvestigateIssueRequest$Outbound = {
  number: string;
};

/** @internal */
export const GithubInvestigateIssueRequest$outboundSchema: z.ZodType<
  GithubInvestigateIssueRequest$Outbound,
  z.ZodTypeDef,
  GithubInvestigateIssueRequest
> = z.object({
  number: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GithubInvestigateIssueRequest$ {
  /** @deprecated use `GithubInvestigateIssueRequest$outboundSchema` instead. */
  export const outboundSchema = GithubInvestigateIssueRequest$outboundSchema;
  /** @deprecated use `GithubInvestigateIssueRequest$Outbound` instead. */
  export type Outbound = GithubInvestigateIssueRequest$Outbound;
}

export function githubInvestigateIssueRequestToJSON(
  githubInvestigateIssueRequest: GithubInvestigateIssueRequest,
): string {
  return JSON.stringify(
    GithubInvestigateIssueRequest$outboundSchema.parse(
      githubInvestigateIssueRequest,
    ),
  );
}
