/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type GithubGetAutofixTaskRequest = {
  taskId: string;
};

/** @internal */
export type GithubGetAutofixTaskRequest$Outbound = {
  task_id: string;
};

/** @internal */
export const GithubGetAutofixTaskRequest$outboundSchema: z.ZodType<
  GithubGetAutofixTaskRequest$Outbound,
  z.ZodTypeDef,
  GithubGetAutofixTaskRequest
> = z.object({
  taskId: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GithubGetAutofixTaskRequest$ {
  /** @deprecated use `GithubGetAutofixTaskRequest$outboundSchema` instead. */
  export const outboundSchema = GithubGetAutofixTaskRequest$outboundSchema;
  /** @deprecated use `GithubGetAutofixTaskRequest$Outbound` instead. */
  export type Outbound = GithubGetAutofixTaskRequest$Outbound;
}

export function githubGetAutofixTaskRequestToJSON(
  githubGetAutofixTaskRequest: GithubGetAutofixTaskRequest,
): string {
  return JSON.stringify(
    GithubGetAutofixTaskRequest$outboundSchema.parse(
      githubGetAutofixTaskRequest,
    ),
  );
}
