/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GithubAnalyzeIssueRequest = {
  number: string;
};

/** @internal */
export type GithubAnalyzeIssueRequest$Outbound = {
  number: string;
};

/** @internal */
export const GithubAnalyzeIssueRequest$outboundSchema: z.ZodType<
  GithubAnalyzeIssueRequest$Outbound,
  z.ZodTypeDef,
  GithubAnalyzeIssueRequest
> = z.object({
  number: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GithubAnalyzeIssueRequest$ {
  /** @deprecated use `GithubAnalyzeIssueRequest$outboundSchema` instead. */
  export const outboundSchema = GithubAnalyzeIssueRequest$outboundSchema;
  /** @deprecated use `GithubAnalyzeIssueRequest$Outbound` instead. */
  export type Outbound = GithubAnalyzeIssueRequest$Outbound;
}

export function githubAnalyzeIssueRequestToJSON(
  githubAnalyzeIssueRequest: GithubAnalyzeIssueRequest,
): string {
  return JSON.stringify(
    GithubAnalyzeIssueRequest$outboundSchema.parse(githubAnalyzeIssueRequest),
  );
}
