/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GroupChatsCreateSessionRequest = {
  id: string;
};

/** @internal */
export type GroupChatsCreateSessionRequest$Outbound = {
  id: string;
};

/** @internal */
export const GroupChatsCreateSessionRequest$outboundSchema: z.ZodType<
  GroupChatsCreateSessionRequest$Outbound,
  z.ZodTypeDef,
  GroupChatsCreateSessionRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GroupChatsCreateSessionRequest$ {
  /** @deprecated use `GroupChatsCreateSessionRequest$outboundSchema` instead. */
  export const outboundSchema = GroupChatsCreateSessionRequest$outboundSchema;
  /** @deprecated use `GroupChatsCreateSessionRequest$Outbound` instead. */
  export type Outbound = GroupChatsCreateSessionRequest$Outbound;
}

export function groupChatsCreateSessionRequestToJSON(
  groupChatsCreateSessionRequest: GroupChatsCreateSessionRequest,
): string {
  return JSON.stringify(
    GroupChatsCreateSessionRequest$outboundSchema.parse(
      groupChatsCreateSessionRequest,
    ),
  );
}
