/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GroupChatsDeletePictureRequest = {
  id: string;
  filename: string;
};

/** @internal */
export type GroupChatsDeletePictureRequest$Outbound = {
  id: string;
  filename: string;
};

/** @internal */
export const GroupChatsDeletePictureRequest$outboundSchema: z.ZodType<
  GroupChatsDeletePictureRequest$Outbound,
  z.ZodTypeDef,
  GroupChatsDeletePictureRequest
> = z.object({
  id: z.string(),
  filename: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GroupChatsDeletePictureRequest$ {
  /** @deprecated use `GroupChatsDeletePictureRequest$outboundSchema` instead. */
  export const outboundSchema = GroupChatsDeletePictureRequest$outboundSchema;
  /** @deprecated use `GroupChatsDeletePictureRequest$Outbound` instead. */
  export type Outbound = GroupChatsDeletePictureRequest$Outbound;
}

export function groupChatsDeletePictureRequestToJSON(
  groupChatsDeletePictureRequest: GroupChatsDeletePictureRequest,
): string {
  return JSON.stringify(
    GroupChatsDeletePictureRequest$outboundSchema.parse(
      groupChatsDeletePictureRequest,
    ),
  );
}
