/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GroupChatsGetSessionRequest = {
  id: string;
  sessionId: string;
};

/** @internal */
export type GroupChatsGetSessionRequest$Outbound = {
  id: string;
  sessionId: string;
};

/** @internal */
export const GroupChatsGetSessionRequest$outboundSchema: z.ZodType<
  GroupChatsGetSessionRequest$Outbound,
  z.ZodTypeDef,
  GroupChatsGetSessionRequest
> = z.object({
  id: z.string(),
  sessionId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GroupChatsGetSessionRequest$ {
  /** @deprecated use `GroupChatsGetSessionRequest$outboundSchema` instead. */
  export const outboundSchema = GroupChatsGetSessionRequest$outboundSchema;
  /** @deprecated use `GroupChatsGetSessionRequest$Outbound` instead. */
  export type Outbound = GroupChatsGetSessionRequest$Outbound;
}

export function groupChatsGetSessionRequestToJSON(
  groupChatsGetSessionRequest: GroupChatsGetSessionRequest,
): string {
  return JSON.stringify(
    GroupChatsGetSessionRequest$outboundSchema.parse(
      groupChatsGetSessionRequest,
    ),
  );
}
