/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GroupChatsCreatePictureRequest = {
  id: string;
};

/** @internal */
export type GroupChatsCreatePictureRequest$Outbound = {
  id: string;
};

/** @internal */
export const GroupChatsCreatePictureRequest$outboundSchema: z.ZodType<
  GroupChatsCreatePictureRequest$Outbound,
  z.ZodTypeDef,
  GroupChatsCreatePictureRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GroupChatsCreatePictureRequest$ {
  /** @deprecated use `GroupChatsCreatePictureRequest$outboundSchema` instead. */
  export const outboundSchema = GroupChatsCreatePictureRequest$outboundSchema;
  /** @deprecated use `GroupChatsCreatePictureRequest$Outbound` instead. */
  export type Outbound = GroupChatsCreatePictureRequest$Outbound;
}

export function groupChatsCreatePictureRequestToJSON(
  groupChatsCreatePictureRequest: GroupChatsCreatePictureRequest,
): string {
  return JSON.stringify(
    GroupChatsCreatePictureRequest$outboundSchema.parse(
      groupChatsCreatePictureRequest,
    ),
  );
}
