/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GroupChatsCreateFileRequest = {
  id: string;
};

/** @internal */
export type GroupChatsCreateFileRequest$Outbound = {
  id: string;
};

/** @internal */
export const GroupChatsCreateFileRequest$outboundSchema: z.ZodType<
  GroupChatsCreateFileRequest$Outbound,
  z.ZodTypeDef,
  GroupChatsCreateFileRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GroupChatsCreateFileRequest$ {
  /** @deprecated use `GroupChatsCreateFileRequest$outboundSchema` instead. */
  export const outboundSchema = GroupChatsCreateFileRequest$outboundSchema;
  /** @deprecated use `GroupChatsCreateFileRequest$Outbound` instead. */
  export type Outbound = GroupChatsCreateFileRequest$Outbound;
}

export function groupChatsCreateFileRequestToJSON(
  groupChatsCreateFileRequest: GroupChatsCreateFileRequest,
): string {
  return JSON.stringify(
    GroupChatsCreateFileRequest$outboundSchema.parse(
      groupChatsCreateFileRequest,
    ),
  );
}
