/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IdeasPromoteRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Task slug
   */
  slug?: string | undefined;
  /**
   * Task priority
   */
  priority?: string | undefined;
  /**
   * Task assignee
   */
  assignee?: string | undefined;
  /**
   * Custom branch name
   */
  branch?: string | undefined;
  /**
   * Task description override
   */
  description?: string | undefined;
  /**
   * Agent configuration
   */
  agent?: string | undefined;
  /**
   * Executor type
   */
  executor?: string | undefined;
  /**
   * Model to use
   */
  model?: string | undefined;
  /**
   * Auto-start task
   */
  start?: boolean | undefined;
  /**
   * Run in worktree
   */
  worktree?: boolean | undefined;
};

export type IdeasPromoteRequest = {
  /**
   * Idea ID
   */
  id: string;
  requestBody: IdeasPromoteRequestBody;
};

/**
 * Default Response
 */
export type IdeasPromoteIdeasResponseResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type IdeasPromoteIdeasResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type IdeasPromoteResponseBody = {
  success?: boolean | undefined;
  ideaId?: string | undefined;
  ideaTitle?: string | undefined;
  taskId?: string | undefined;
  taskDir?: string | undefined;
  priority?: string | undefined;
  status?: string | undefined;
  worktree?: boolean | undefined;
};

export type IdeasPromoteResponse =
  | IdeasPromoteResponseBody
  | IdeasPromoteIdeasResponseBody
  | IdeasPromoteIdeasResponseResponseBody;

/** @internal */
export type IdeasPromoteRequestBody$Outbound = {
  workspace_path: string;
  slug?: string | undefined;
  priority?: string | undefined;
  assignee?: string | undefined;
  branch?: string | undefined;
  description?: string | undefined;
  agent?: string | undefined;
  executor?: string | undefined;
  model?: string | undefined;
  start?: boolean | undefined;
  worktree?: boolean | undefined;
};

/** @internal */
export const IdeasPromoteRequestBody$outboundSchema: z.ZodType<
  IdeasPromoteRequestBody$Outbound,
  z.ZodTypeDef,
  IdeasPromoteRequestBody
> = z.object({
  workspacePath: z.string(),
  slug: z.string().optional(),
  priority: z.string().optional(),
  assignee: z.string().optional(),
  branch: z.string().optional(),
  description: z.string().optional(),
  agent: z.string().optional(),
  executor: z.string().optional(),
  model: z.string().optional(),
  start: z.boolean().optional(),
  worktree: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasPromoteRequestBody$ {
  /** @deprecated use `IdeasPromoteRequestBody$outboundSchema` instead. */
  export const outboundSchema = IdeasPromoteRequestBody$outboundSchema;
  /** @deprecated use `IdeasPromoteRequestBody$Outbound` instead. */
  export type Outbound = IdeasPromoteRequestBody$Outbound;
}

export function ideasPromoteRequestBodyToJSON(
  ideasPromoteRequestBody: IdeasPromoteRequestBody,
): string {
  return JSON.stringify(
    IdeasPromoteRequestBody$outboundSchema.parse(ideasPromoteRequestBody),
  );
}

/** @internal */
export type IdeasPromoteRequest$Outbound = {
  id: string;
  RequestBody: IdeasPromoteRequestBody$Outbound;
};

/** @internal */
export const IdeasPromoteRequest$outboundSchema: z.ZodType<
  IdeasPromoteRequest$Outbound,
  z.ZodTypeDef,
  IdeasPromoteRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => IdeasPromoteRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasPromoteRequest$ {
  /** @deprecated use `IdeasPromoteRequest$outboundSchema` instead. */
  export const outboundSchema = IdeasPromoteRequest$outboundSchema;
  /** @deprecated use `IdeasPromoteRequest$Outbound` instead. */
  export type Outbound = IdeasPromoteRequest$Outbound;
}

export function ideasPromoteRequestToJSON(
  ideasPromoteRequest: IdeasPromoteRequest,
): string {
  return JSON.stringify(
    IdeasPromoteRequest$outboundSchema.parse(ideasPromoteRequest),
  );
}

/** @internal */
export const IdeasPromoteIdeasResponseResponseBody$inboundSchema: z.ZodType<
  IdeasPromoteIdeasResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasPromoteIdeasResponseResponseBody$ {
  /** @deprecated use `IdeasPromoteIdeasResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    IdeasPromoteIdeasResponseResponseBody$inboundSchema;
}

export function ideasPromoteIdeasResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeasPromoteIdeasResponseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IdeasPromoteIdeasResponseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasPromoteIdeasResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeasPromoteIdeasResponseBody$inboundSchema: z.ZodType<
  IdeasPromoteIdeasResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasPromoteIdeasResponseBody$ {
  /** @deprecated use `IdeasPromoteIdeasResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeasPromoteIdeasResponseBody$inboundSchema;
}

export function ideasPromoteIdeasResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeasPromoteIdeasResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasPromoteIdeasResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasPromoteIdeasResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeasPromoteResponseBody$inboundSchema: z.ZodType<
  IdeasPromoteResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  idea_id: z.string().optional(),
  idea_title: z.string().optional(),
  task_id: z.string().optional(),
  task_dir: z.string().optional(),
  priority: z.string().optional(),
  status: z.string().optional(),
  worktree: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "idea_id": "ideaId",
    "idea_title": "ideaTitle",
    "task_id": "taskId",
    "task_dir": "taskDir",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasPromoteResponseBody$ {
  /** @deprecated use `IdeasPromoteResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeasPromoteResponseBody$inboundSchema;
}

export function ideasPromoteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeasPromoteResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasPromoteResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasPromoteResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeasPromoteResponse$inboundSchema: z.ZodType<
  IdeasPromoteResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => IdeasPromoteResponseBody$inboundSchema),
  z.lazy(() => IdeasPromoteIdeasResponseBody$inboundSchema),
  z.lazy(() => IdeasPromoteIdeasResponseResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasPromoteResponse$ {
  /** @deprecated use `IdeasPromoteResponse$inboundSchema` instead. */
  export const inboundSchema = IdeasPromoteResponse$inboundSchema;
}

export function ideasPromoteResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdeasPromoteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasPromoteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasPromoteResponse' from JSON`,
  );
}
