/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IdeasGetRequest = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Idea ID
   */
  id: string;
};

/**
 * Default Response
 */
export type IdeasGetIdeasResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
};

export type Idea = {};

/**
 * Default Response
 */
export type IdeasGetResponseBody = {
  success?: boolean | undefined;
  idea?: Idea | undefined;
  sessionDir?: string | null | undefined;
  filePath?: string | null | undefined;
};

export type IdeasGetResponse = IdeasGetResponseBody | IdeasGetIdeasResponseBody;

/** @internal */
export type IdeasGetRequest$Outbound = {
  workspace_path: string;
  id: string;
};

/** @internal */
export const IdeasGetRequest$outboundSchema: z.ZodType<
  IdeasGetRequest$Outbound,
  z.ZodTypeDef,
  IdeasGetRequest
> = z.object({
  workspacePath: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasGetRequest$ {
  /** @deprecated use `IdeasGetRequest$outboundSchema` instead. */
  export const outboundSchema = IdeasGetRequest$outboundSchema;
  /** @deprecated use `IdeasGetRequest$Outbound` instead. */
  export type Outbound = IdeasGetRequest$Outbound;
}

export function ideasGetRequestToJSON(
  ideasGetRequest: IdeasGetRequest,
): string {
  return JSON.stringify(IdeasGetRequest$outboundSchema.parse(ideasGetRequest));
}

/** @internal */
export const IdeasGetIdeasResponseBody$inboundSchema: z.ZodType<
  IdeasGetIdeasResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasGetIdeasResponseBody$ {
  /** @deprecated use `IdeasGetIdeasResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeasGetIdeasResponseBody$inboundSchema;
}

export function ideasGetIdeasResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeasGetIdeasResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasGetIdeasResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasGetIdeasResponseBody' from JSON`,
  );
}

/** @internal */
export const Idea$inboundSchema: z.ZodType<Idea, z.ZodTypeDef, unknown> = z
  .object({});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Idea$ {
  /** @deprecated use `Idea$inboundSchema` instead. */
  export const inboundSchema = Idea$inboundSchema;
}

export function ideaFromJSON(
  jsonString: string,
): SafeParseResult<Idea, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Idea$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Idea' from JSON`,
  );
}

/** @internal */
export const IdeasGetResponseBody$inboundSchema: z.ZodType<
  IdeasGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  idea: z.lazy(() => Idea$inboundSchema).optional(),
  session_dir: z.nullable(z.string()).optional(),
  file_path: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "session_dir": "sessionDir",
    "file_path": "filePath",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasGetResponseBody$ {
  /** @deprecated use `IdeasGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeasGetResponseBody$inboundSchema;
}

export function ideasGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeasGetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasGetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasGetResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeasGetResponse$inboundSchema: z.ZodType<
  IdeasGetResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => IdeasGetResponseBody$inboundSchema),
  z.lazy(() => IdeasGetIdeasResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasGetResponse$ {
  /** @deprecated use `IdeasGetResponse$inboundSchema` instead. */
  export const inboundSchema = IdeasGetResponse$inboundSchema;
}

export function ideasGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdeasGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasGetResponse' from JSON`,
  );
}
