/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IdeasDeleteRequest = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Idea ID
   */
  id: string;
};

/**
 * Default Response
 */
export type IdeasDeleteIdeasResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type IdeasDeleteResponseBody = {
  success?: boolean | undefined;
  removed?: Array<string> | undefined;
  count?: number | undefined;
};

export type IdeasDeleteResponse =
  | IdeasDeleteResponseBody
  | IdeasDeleteIdeasResponseBody;

/** @internal */
export type IdeasDeleteRequest$Outbound = {
  workspace_path: string;
  id: string;
};

/** @internal */
export const IdeasDeleteRequest$outboundSchema: z.ZodType<
  IdeasDeleteRequest$Outbound,
  z.ZodTypeDef,
  IdeasDeleteRequest
> = z.object({
  workspacePath: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasDeleteRequest$ {
  /** @deprecated use `IdeasDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = IdeasDeleteRequest$outboundSchema;
  /** @deprecated use `IdeasDeleteRequest$Outbound` instead. */
  export type Outbound = IdeasDeleteRequest$Outbound;
}

export function ideasDeleteRequestToJSON(
  ideasDeleteRequest: IdeasDeleteRequest,
): string {
  return JSON.stringify(
    IdeasDeleteRequest$outboundSchema.parse(ideasDeleteRequest),
  );
}

/** @internal */
export const IdeasDeleteIdeasResponseBody$inboundSchema: z.ZodType<
  IdeasDeleteIdeasResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasDeleteIdeasResponseBody$ {
  /** @deprecated use `IdeasDeleteIdeasResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeasDeleteIdeasResponseBody$inboundSchema;
}

export function ideasDeleteIdeasResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeasDeleteIdeasResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasDeleteIdeasResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasDeleteIdeasResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeasDeleteResponseBody$inboundSchema: z.ZodType<
  IdeasDeleteResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  removed: z.array(z.string()).optional(),
  count: z.number().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasDeleteResponseBody$ {
  /** @deprecated use `IdeasDeleteResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeasDeleteResponseBody$inboundSchema;
}

export function ideasDeleteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeasDeleteResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasDeleteResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasDeleteResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeasDeleteResponse$inboundSchema: z.ZodType<
  IdeasDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => IdeasDeleteResponseBody$inboundSchema),
  z.lazy(() => IdeasDeleteIdeasResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasDeleteResponse$ {
  /** @deprecated use `IdeasDeleteResponse$inboundSchema` instead. */
  export const inboundSchema = IdeasDeleteResponse$inboundSchema;
}

export function ideasDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdeasDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasDeleteResponse' from JSON`,
  );
}
