/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IdeasDelete2Request = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Remove all ideas of this type
   */
  type?: string | undefined;
  /**
   * Set to 'true' to remove all ideas
   */
  all?: string | undefined;
};

/**
 * Default Response
 */
export type IdeasDelete2IdeasResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type IdeasDelete2ResponseBody = {
  success?: boolean | undefined;
  removed?: Array<string> | undefined;
  count?: number | undefined;
};

export type IdeasDelete2Response =
  | IdeasDelete2ResponseBody
  | IdeasDelete2IdeasResponseBody;

/** @internal */
export type IdeasDelete2Request$Outbound = {
  workspace_path: string;
  type?: string | undefined;
  all?: string | undefined;
};

/** @internal */
export const IdeasDelete2Request$outboundSchema: z.ZodType<
  IdeasDelete2Request$Outbound,
  z.ZodTypeDef,
  IdeasDelete2Request
> = z.object({
  workspacePath: z.string(),
  type: z.string().optional(),
  all: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasDelete2Request$ {
  /** @deprecated use `IdeasDelete2Request$outboundSchema` instead. */
  export const outboundSchema = IdeasDelete2Request$outboundSchema;
  /** @deprecated use `IdeasDelete2Request$Outbound` instead. */
  export type Outbound = IdeasDelete2Request$Outbound;
}

export function ideasDelete2RequestToJSON(
  ideasDelete2Request: IdeasDelete2Request,
): string {
  return JSON.stringify(
    IdeasDelete2Request$outboundSchema.parse(ideasDelete2Request),
  );
}

/** @internal */
export const IdeasDelete2IdeasResponseBody$inboundSchema: z.ZodType<
  IdeasDelete2IdeasResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasDelete2IdeasResponseBody$ {
  /** @deprecated use `IdeasDelete2IdeasResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeasDelete2IdeasResponseBody$inboundSchema;
}

export function ideasDelete2IdeasResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeasDelete2IdeasResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasDelete2IdeasResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasDelete2IdeasResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeasDelete2ResponseBody$inboundSchema: z.ZodType<
  IdeasDelete2ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  removed: z.array(z.string()).optional(),
  count: z.number().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasDelete2ResponseBody$ {
  /** @deprecated use `IdeasDelete2ResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeasDelete2ResponseBody$inboundSchema;
}

export function ideasDelete2ResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeasDelete2ResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasDelete2ResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasDelete2ResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeasDelete2Response$inboundSchema: z.ZodType<
  IdeasDelete2Response,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => IdeasDelete2ResponseBody$inboundSchema),
  z.lazy(() => IdeasDelete2IdeasResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeasDelete2Response$ {
  /** @deprecated use `IdeasDelete2Response$inboundSchema` instead. */
  export const inboundSchema = IdeasDelete2Response$inboundSchema;
}

export function ideasDelete2ResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdeasDelete2Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeasDelete2Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeasDelete2Response' from JSON`,
  );
}
