/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IdeaTypesListRequest = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type IdeaTypesListIdeasResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
};

export const IdeaTypesListSource = {
  Builtin: "builtin",
  Custom: "custom",
} as const;
export type IdeaTypesListSource = ClosedEnum<typeof IdeaTypesListSource>;

export type Types = {
  name?: string | undefined;
  description?: string | undefined;
  maxIdeas?: number | null | undefined;
  source?: IdeaTypesListSource | undefined;
  promptPath?: string | undefined;
};

/**
 * Default Response
 */
export type IdeaTypesListResponseBody = {
  success?: boolean | undefined;
  types?: Array<Types> | undefined;
  count?: number | undefined;
};

export type IdeaTypesListResponse =
  | IdeaTypesListResponseBody
  | IdeaTypesListIdeasResponseBody;

/** @internal */
export type IdeaTypesListRequest$Outbound = {
  workspace_path: string;
};

/** @internal */
export const IdeaTypesListRequest$outboundSchema: z.ZodType<
  IdeaTypesListRequest$Outbound,
  z.ZodTypeDef,
  IdeaTypesListRequest
> = z.object({
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeaTypesListRequest$ {
  /** @deprecated use `IdeaTypesListRequest$outboundSchema` instead. */
  export const outboundSchema = IdeaTypesListRequest$outboundSchema;
  /** @deprecated use `IdeaTypesListRequest$Outbound` instead. */
  export type Outbound = IdeaTypesListRequest$Outbound;
}

export function ideaTypesListRequestToJSON(
  ideaTypesListRequest: IdeaTypesListRequest,
): string {
  return JSON.stringify(
    IdeaTypesListRequest$outboundSchema.parse(ideaTypesListRequest),
  );
}

/** @internal */
export const IdeaTypesListIdeasResponseBody$inboundSchema: z.ZodType<
  IdeaTypesListIdeasResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeaTypesListIdeasResponseBody$ {
  /** @deprecated use `IdeaTypesListIdeasResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeaTypesListIdeasResponseBody$inboundSchema;
}

export function ideaTypesListIdeasResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeaTypesListIdeasResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeaTypesListIdeasResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeaTypesListIdeasResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeaTypesListSource$inboundSchema: z.ZodNativeEnum<
  typeof IdeaTypesListSource
> = z.nativeEnum(IdeaTypesListSource);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeaTypesListSource$ {
  /** @deprecated use `IdeaTypesListSource$inboundSchema` instead. */
  export const inboundSchema = IdeaTypesListSource$inboundSchema;
}

/** @internal */
export const Types$inboundSchema: z.ZodType<Types, z.ZodTypeDef, unknown> = z
  .object({
    name: z.string().optional(),
    description: z.string().optional(),
    max_ideas: z.nullable(z.number()).optional(),
    source: IdeaTypesListSource$inboundSchema.optional(),
    prompt_path: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "max_ideas": "maxIdeas",
      "prompt_path": "promptPath",
    });
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Types$ {
  /** @deprecated use `Types$inboundSchema` instead. */
  export const inboundSchema = Types$inboundSchema;
}

export function typesFromJSON(
  jsonString: string,
): SafeParseResult<Types, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Types$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Types' from JSON`,
  );
}

/** @internal */
export const IdeaTypesListResponseBody$inboundSchema: z.ZodType<
  IdeaTypesListResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  types: z.array(z.lazy(() => Types$inboundSchema)).optional(),
  count: z.number().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeaTypesListResponseBody$ {
  /** @deprecated use `IdeaTypesListResponseBody$inboundSchema` instead. */
  export const inboundSchema = IdeaTypesListResponseBody$inboundSchema;
}

export function ideaTypesListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<IdeaTypesListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeaTypesListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeaTypesListResponseBody' from JSON`,
  );
}

/** @internal */
export const IdeaTypesListResponse$inboundSchema: z.ZodType<
  IdeaTypesListResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => IdeaTypesListResponseBody$inboundSchema),
  z.lazy(() => IdeaTypesListIdeasResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IdeaTypesListResponse$ {
  /** @deprecated use `IdeaTypesListResponse$inboundSchema` instead. */
  export const inboundSchema = IdeaTypesListResponse$inboundSchema;
}

export function ideaTypesListResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdeaTypesListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdeaTypesListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdeaTypesListResponse' from JSON`,
  );
}
