/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type LogsExportSessionRequest = {
  sessionId: string;
};

/** @internal */
export type LogsExportSessionRequest$Outbound = {
  sessionId: string;
};

/** @internal */
export const LogsExportSessionRequest$outboundSchema: z.ZodType<
  LogsExportSessionRequest$Outbound,
  z.ZodTypeDef,
  LogsExportSessionRequest
> = z.object({
  sessionId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LogsExportSessionRequest$ {
  /** @deprecated use `LogsExportSessionRequest$outboundSchema` instead. */
  export const outboundSchema = LogsExportSessionRequest$outboundSchema;
  /** @deprecated use `LogsExportSessionRequest$Outbound` instead. */
  export type Outbound = LogsExportSessionRequest$Outbound;
}

export function logsExportSessionRequestToJSON(
  logsExportSessionRequest: LogsExportSessionRequest,
): string {
  return JSON.stringify(
    LogsExportSessionRequest$outboundSchema.parse(logsExportSessionRequest),
  );
}
