/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type McpCreateAgentServerRequest = {
  agentId: string;
};

/** @internal */
export type McpCreateAgentServerRequest$Outbound = {
  agentId: string;
};

/** @internal */
export const McpCreateAgentServerRequest$outboundSchema: z.ZodType<
  McpCreateAgentServerRequest$Outbound,
  z.ZodTypeDef,
  McpCreateAgentServerRequest
> = z.object({
  agentId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace McpCreateAgentServerRequest$ {
  /** @deprecated use `McpCreateAgentServerRequest$outboundSchema` instead. */
  export const outboundSchema = McpCreateAgentServerRequest$outboundSchema;
  /** @deprecated use `McpCreateAgentServerRequest$Outbound` instead. */
  export type Outbound = McpCreateAgentServerRequest$Outbound;
}

export function mcpCreateAgentServerRequestToJSON(
  mcpCreateAgentServerRequest: McpCreateAgentServerRequest,
): string {
  return JSON.stringify(
    McpCreateAgentServerRequest$outboundSchema.parse(
      mcpCreateAgentServerRequest,
    ),
  );
}
