/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type McpDeleteInspectorSessionRequest = {
  sessionId: string;
};

/** @internal */
export type McpDeleteInspectorSessionRequest$Outbound = {
  sessionId: string;
};

/** @internal */
export const McpDeleteInspectorSessionRequest$outboundSchema: z.ZodType<
  McpDeleteInspectorSessionRequest$Outbound,
  z.ZodTypeDef,
  McpDeleteInspectorSessionRequest
> = z.object({
  sessionId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace McpDeleteInspectorSessionRequest$ {
  /** @deprecated use `McpDeleteInspectorSessionRequest$outboundSchema` instead. */
  export const outboundSchema = McpDeleteInspectorSessionRequest$outboundSchema;
  /** @deprecated use `McpDeleteInspectorSessionRequest$Outbound` instead. */
  export type Outbound = McpDeleteInspectorSessionRequest$Outbound;
}

export function mcpDeleteInspectorSessionRequestToJSON(
  mcpDeleteInspectorSessionRequest: McpDeleteInspectorSessionRequest,
): string {
  return JSON.stringify(
    McpDeleteInspectorSessionRequest$outboundSchema.parse(
      mcpDeleteInspectorSessionRequest,
    ),
  );
}
