/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type McpGetAgentServerRequest = {
  agentId: string;
  name: string;
};

/** @internal */
export type McpGetAgentServerRequest$Outbound = {
  agentId: string;
  name: string;
};

/** @internal */
export const McpGetAgentServerRequest$outboundSchema: z.ZodType<
  McpGetAgentServerRequest$Outbound,
  z.ZodTypeDef,
  McpGetAgentServerRequest
> = z.object({
  agentId: z.string(),
  name: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace McpGetAgentServerRequest$ {
  /** @deprecated use `McpGetAgentServerRequest$outboundSchema` instead. */
  export const outboundSchema = McpGetAgentServerRequest$outboundSchema;
  /** @deprecated use `McpGetAgentServerRequest$Outbound` instead. */
  export type Outbound = McpGetAgentServerRequest$Outbound;
}

export function mcpGetAgentServerRequestToJSON(
  mcpGetAgentServerRequest: McpGetAgentServerRequest,
): string {
  return JSON.stringify(
    McpGetAgentServerRequest$outboundSchema.parse(mcpGetAgentServerRequest),
  );
}
