/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type McpMarketGetCommentsRequest = {
  id: string;
};

/** @internal */
export type McpMarketGetCommentsRequest$Outbound = {
  id: string;
};

/** @internal */
export const McpMarketGetCommentsRequest$outboundSchema: z.ZodType<
  McpMarketGetCommentsRequest$Outbound,
  z.ZodTypeDef,
  McpMarketGetCommentsRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace McpMarketGetCommentsRequest$ {
  /** @deprecated use `McpMarketGetCommentsRequest$outboundSchema` instead. */
  export const outboundSchema = McpMarketGetCommentsRequest$outboundSchema;
  /** @deprecated use `McpMarketGetCommentsRequest$Outbound` instead. */
  export type Outbound = McpMarketGetCommentsRequest$Outbound;
}

export function mcpMarketGetCommentsRequestToJSON(
  mcpMarketGetCommentsRequest: McpMarketGetCommentsRequest,
): string {
  return JSON.stringify(
    McpMarketGetCommentsRequest$outboundSchema.parse(
      mcpMarketGetCommentsRequest,
    ),
  );
}
