/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type McpMarketDownloadRequest = {
  id: string;
};

/** @internal */
export type McpMarketDownloadRequest$Outbound = {
  id: string;
};

/** @internal */
export const McpMarketDownloadRequest$outboundSchema: z.ZodType<
  McpMarketDownloadRequest$Outbound,
  z.ZodTypeDef,
  McpMarketDownloadRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace McpMarketDownloadRequest$ {
  /** @deprecated use `McpMarketDownloadRequest$outboundSchema` instead. */
  export const outboundSchema = McpMarketDownloadRequest$outboundSchema;
  /** @deprecated use `McpMarketDownloadRequest$Outbound` instead. */
  export type Outbound = McpMarketDownloadRequest$Outbound;
}

export function mcpMarketDownloadRequestToJSON(
  mcpMarketDownloadRequest: McpMarketDownloadRequest,
): string {
  return JSON.stringify(
    McpMarketDownloadRequest$outboundSchema.parse(mcpMarketDownloadRequest),
  );
}
