/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type McpUpdateAgentServerRequest = {
  agentId: string;
  name: string;
};

/** @internal */
export type McpUpdateAgentServerRequest$Outbound = {
  agentId: string;
  name: string;
};

/** @internal */
export const McpUpdateAgentServerRequest$outboundSchema: z.ZodType<
  McpUpdateAgentServerRequest$Outbound,
  z.ZodTypeDef,
  McpUpdateAgentServerRequest
> = z.object({
  agentId: z.string(),
  name: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace McpUpdateAgentServerRequest$ {
  /** @deprecated use `McpUpdateAgentServerRequest$outboundSchema` instead. */
  export const outboundSchema = McpUpdateAgentServerRequest$outboundSchema;
  /** @deprecated use `McpUpdateAgentServerRequest$Outbound` instead. */
  export type Outbound = McpUpdateAgentServerRequest$Outbound;
}

export function mcpUpdateAgentServerRequestToJSON(
  mcpUpdateAgentServerRequest: McpUpdateAgentServerRequest,
): string {
  return JSON.stringify(
    McpUpdateAgentServerRequest$outboundSchema.parse(
      mcpUpdateAgentServerRequest,
    ),
  );
}
