/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ModelsUpdateConfigRequest = {
  id: string;
};

/** @internal */
export type ModelsUpdateConfigRequest$Outbound = {
  id: string;
};

/** @internal */
export const ModelsUpdateConfigRequest$outboundSchema: z.ZodType<
  ModelsUpdateConfigRequest$Outbound,
  z.ZodTypeDef,
  ModelsUpdateConfigRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelsUpdateConfigRequest$ {
  /** @deprecated use `ModelsUpdateConfigRequest$outboundSchema` instead. */
  export const outboundSchema = ModelsUpdateConfigRequest$outboundSchema;
  /** @deprecated use `ModelsUpdateConfigRequest$Outbound` instead. */
  export type Outbound = ModelsUpdateConfigRequest$Outbound;
}

export function modelsUpdateConfigRequestToJSON(
  modelsUpdateConfigRequest: ModelsUpdateConfigRequest,
): string {
  return JSON.stringify(
    ModelsUpdateConfigRequest$outboundSchema.parse(modelsUpdateConfigRequest),
  );
}
