/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ModelsGetRequest = {
  /**
   * Model ID or alias
   */
  id: string;
};

/**
 * Default Response
 */
export type ModelsGetModelsResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type ModelsGetResponseBody = {
  id?: string | undefined;
  name?: string | undefined;
  providerType?: string | undefined;
  providerId?: string | undefined;
  providerName?: string | undefined;
  description?: string | undefined;
  contextWindow?: number | undefined;
  maxOutputTokens?: number | undefined;
  isDefault?: boolean | undefined;
  enabled?: boolean | undefined;
  isAvailable?: boolean | undefined;
  config?: { [k: string]: any } | null | undefined;
};

export type ModelsGetResponse =
  | ModelsGetResponseBody
  | ModelsGetModelsResponseBody;

/** @internal */
export type ModelsGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const ModelsGetRequest$outboundSchema: z.ZodType<
  ModelsGetRequest$Outbound,
  z.ZodTypeDef,
  ModelsGetRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelsGetRequest$ {
  /** @deprecated use `ModelsGetRequest$outboundSchema` instead. */
  export const outboundSchema = ModelsGetRequest$outboundSchema;
  /** @deprecated use `ModelsGetRequest$Outbound` instead. */
  export type Outbound = ModelsGetRequest$Outbound;
}

export function modelsGetRequestToJSON(
  modelsGetRequest: ModelsGetRequest,
): string {
  return JSON.stringify(
    ModelsGetRequest$outboundSchema.parse(modelsGetRequest),
  );
}

/** @internal */
export const ModelsGetModelsResponseBody$inboundSchema: z.ZodType<
  ModelsGetModelsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelsGetModelsResponseBody$ {
  /** @deprecated use `ModelsGetModelsResponseBody$inboundSchema` instead. */
  export const inboundSchema = ModelsGetModelsResponseBody$inboundSchema;
}

export function modelsGetModelsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ModelsGetModelsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsGetModelsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsGetModelsResponseBody' from JSON`,
  );
}

/** @internal */
export const ModelsGetResponseBody$inboundSchema: z.ZodType<
  ModelsGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  provider_type: z.string().optional(),
  provider_id: z.string().optional(),
  provider_name: z.string().optional(),
  description: z.string().optional(),
  context_window: z.number().optional(),
  max_output_tokens: z.number().optional(),
  is_default: z.boolean().optional(),
  enabled: z.boolean().optional(),
  is_available: z.boolean().optional(),
  config: z.nullable(z.record(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    "provider_type": "providerType",
    "provider_id": "providerId",
    "provider_name": "providerName",
    "context_window": "contextWindow",
    "max_output_tokens": "maxOutputTokens",
    "is_default": "isDefault",
    "is_available": "isAvailable",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelsGetResponseBody$ {
  /** @deprecated use `ModelsGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = ModelsGetResponseBody$inboundSchema;
}

export function modelsGetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ModelsGetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsGetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsGetResponseBody' from JSON`,
  );
}

/** @internal */
export const ModelsGetResponse$inboundSchema: z.ZodType<
  ModelsGetResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ModelsGetResponseBody$inboundSchema),
  z.lazy(() => ModelsGetModelsResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelsGetResponse$ {
  /** @deprecated use `ModelsGetResponse$inboundSchema` instead. */
  export const inboundSchema = ModelsGetResponse$inboundSchema;
}

export function modelsGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<ModelsGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsGetResponse' from JSON`,
  );
}
