/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PageViewRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Page uid (required)
   */
  uid: string;
};

/**
 * Default Response
 */
export type PageViewPageResponseResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
  details?: any | undefined;
};

/**
 * Default Response
 */
export type PageViewPageResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
  details?: any | undefined;
};

export const PageViewPageType = {
  Lucide: "lucide",
  Emoji: "emoji",
  Image: "image",
} as const;
export type PageViewPageType = ClosedEnum<typeof PageViewPageType>;

export type PageViewIcon = {
  type?: PageViewPageType | undefined;
  value?: string | undefined;
};

export const PageViewPageWidth = {
  Default: "default",
  Wide: "wide",
  Full: "full",
} as const;
export type PageViewPageWidth = ClosedEnum<typeof PageViewPageWidth>;

/**
 * Page type
 */
export const PageViewType = {
  Static: "static",
  Markdown: "markdown",
  Server: "server",
  Proxy: "proxy",
} as const;
/**
 * Page type
 */
export type PageViewType = ClosedEnum<typeof PageViewType>;

export const PageViewPermission = {
  Read: "read",
  Write: "write",
} as const;
export type PageViewPermission = ClosedEnum<typeof PageViewPermission>;

export type Page = {
  uid?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  icon?: PageViewIcon | null | undefined;
  cover?: string | null | undefined;
  pageWidth?: PageViewPageWidth | null | undefined;
  showToc?: boolean | null | undefined;
  /**
   * Page type
   */
  type?: PageViewType | undefined;
  /**
   * Page permissions
   */
  permission?: Array<PageViewPermission> | undefined;
  path?: string | undefined;
  skillContent?: string | null | undefined;
  updatedAt?: string | null | undefined;
  file?: string | null | undefined;
  command?: string | null | undefined;
  port?: number | null | undefined;
  readyPattern?: string | null | undefined;
  timeout?: number | null | undefined;
  url?: string | null | undefined;
  headers?: { [k: string]: string } | null | undefined;
};

/**
 * Default Response
 */
export type PageViewResponseBody = {
  success?: boolean | undefined;
  page?: Page | null | undefined;
  error?: string | null | undefined;
};

export type PageViewResponse =
  | PageViewResponseBody
  | PageViewPageResponseBody
  | PageViewPageResponseResponseBody;

/** @internal */
export type PageViewRequestBody$Outbound = {
  workspace_path: string;
  uid: string;
};

/** @internal */
export const PageViewRequestBody$outboundSchema: z.ZodType<
  PageViewRequestBody$Outbound,
  z.ZodTypeDef,
  PageViewRequestBody
> = z.object({
  workspacePath: z.string(),
  uid: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewRequestBody$ {
  /** @deprecated use `PageViewRequestBody$outboundSchema` instead. */
  export const outboundSchema = PageViewRequestBody$outboundSchema;
  /** @deprecated use `PageViewRequestBody$Outbound` instead. */
  export type Outbound = PageViewRequestBody$Outbound;
}

export function pageViewRequestBodyToJSON(
  pageViewRequestBody: PageViewRequestBody,
): string {
  return JSON.stringify(
    PageViewRequestBody$outboundSchema.parse(pageViewRequestBody),
  );
}

/** @internal */
export const PageViewPageResponseResponseBody$inboundSchema: z.ZodType<
  PageViewPageResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
  details: z.any().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewPageResponseResponseBody$ {
  /** @deprecated use `PageViewPageResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema = PageViewPageResponseResponseBody$inboundSchema;
}

export function pageViewPageResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PageViewPageResponseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageViewPageResponseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageViewPageResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PageViewPageResponseBody$inboundSchema: z.ZodType<
  PageViewPageResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
  details: z.any().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewPageResponseBody$ {
  /** @deprecated use `PageViewPageResponseBody$inboundSchema` instead. */
  export const inboundSchema = PageViewPageResponseBody$inboundSchema;
}

export function pageViewPageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PageViewPageResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageViewPageResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageViewPageResponseBody' from JSON`,
  );
}

/** @internal */
export const PageViewPageType$inboundSchema: z.ZodNativeEnum<
  typeof PageViewPageType
> = z.nativeEnum(PageViewPageType);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewPageType$ {
  /** @deprecated use `PageViewPageType$inboundSchema` instead. */
  export const inboundSchema = PageViewPageType$inboundSchema;
}

/** @internal */
export const PageViewIcon$inboundSchema: z.ZodType<
  PageViewIcon,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PageViewPageType$inboundSchema.optional(),
  value: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewIcon$ {
  /** @deprecated use `PageViewIcon$inboundSchema` instead. */
  export const inboundSchema = PageViewIcon$inboundSchema;
}

export function pageViewIconFromJSON(
  jsonString: string,
): SafeParseResult<PageViewIcon, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageViewIcon$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageViewIcon' from JSON`,
  );
}

/** @internal */
export const PageViewPageWidth$inboundSchema: z.ZodNativeEnum<
  typeof PageViewPageWidth
> = z.nativeEnum(PageViewPageWidth);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewPageWidth$ {
  /** @deprecated use `PageViewPageWidth$inboundSchema` instead. */
  export const inboundSchema = PageViewPageWidth$inboundSchema;
}

/** @internal */
export const PageViewType$inboundSchema: z.ZodNativeEnum<typeof PageViewType> =
  z.nativeEnum(PageViewType);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewType$ {
  /** @deprecated use `PageViewType$inboundSchema` instead. */
  export const inboundSchema = PageViewType$inboundSchema;
}

/** @internal */
export const PageViewPermission$inboundSchema: z.ZodNativeEnum<
  typeof PageViewPermission
> = z.nativeEnum(PageViewPermission);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewPermission$ {
  /** @deprecated use `PageViewPermission$inboundSchema` instead. */
  export const inboundSchema = PageViewPermission$inboundSchema;
}

/** @internal */
export const Page$inboundSchema: z.ZodType<Page, z.ZodTypeDef, unknown> = z
  .object({
    uid: z.string().optional(),
    name: z.string().optional(),
    description: z.nullable(z.string()).optional(),
    icon: z.nullable(z.lazy(() => PageViewIcon$inboundSchema)).optional(),
    cover: z.nullable(z.string()).optional(),
    page_width: z.nullable(PageViewPageWidth$inboundSchema).optional(),
    show_toc: z.nullable(z.boolean()).optional(),
    type: PageViewType$inboundSchema.optional(),
    permission: z.array(PageViewPermission$inboundSchema).optional(),
    path: z.string().optional(),
    skill_content: z.nullable(z.string()).optional(),
    updated_at: z.nullable(z.string()).optional(),
    file: z.nullable(z.string()).optional(),
    command: z.nullable(z.string()).optional(),
    port: z.nullable(z.number()).optional(),
    ready_pattern: z.nullable(z.string()).optional(),
    timeout: z.nullable(z.number()).optional(),
    url: z.nullable(z.string()).optional(),
    headers: z.nullable(z.record(z.string())).optional(),
  }).transform((v) => {
    return remap$(v, {
      "page_width": "pageWidth",
      "show_toc": "showToc",
      "skill_content": "skillContent",
      "updated_at": "updatedAt",
      "ready_pattern": "readyPattern",
    });
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Page$ {
  /** @deprecated use `Page$inboundSchema` instead. */
  export const inboundSchema = Page$inboundSchema;
}

export function pageFromJSON(
  jsonString: string,
): SafeParseResult<Page, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Page$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Page' from JSON`,
  );
}

/** @internal */
export const PageViewResponseBody$inboundSchema: z.ZodType<
  PageViewResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  page: z.nullable(z.lazy(() => Page$inboundSchema)).optional(),
  error: z.nullable(z.string()).optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewResponseBody$ {
  /** @deprecated use `PageViewResponseBody$inboundSchema` instead. */
  export const inboundSchema = PageViewResponseBody$inboundSchema;
}

export function pageViewResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PageViewResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageViewResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageViewResponseBody' from JSON`,
  );
}

/** @internal */
export const PageViewResponse$inboundSchema: z.ZodType<
  PageViewResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PageViewResponseBody$inboundSchema),
  z.lazy(() => PageViewPageResponseBody$inboundSchema),
  z.lazy(() => PageViewPageResponseResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageViewResponse$ {
  /** @deprecated use `PageViewResponse$inboundSchema` instead. */
  export const inboundSchema = PageViewResponse$inboundSchema;
}

export function pageViewResponseFromJSON(
  jsonString: string,
): SafeParseResult<PageViewResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageViewResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageViewResponse' from JSON`,
  );
}
