/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PageDuplicateRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Source page uid to duplicate
   */
  uid: string;
};

/**
 * Default Response
 */
export type PageDuplicatePageResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
  details?: any | undefined;
};

export const PageDuplicatePageType = {
  Lucide: "lucide",
  Emoji: "emoji",
  Image: "image",
} as const;
export type PageDuplicatePageType = ClosedEnum<typeof PageDuplicatePageType>;

export type PageDuplicateIcon = {
  type?: PageDuplicatePageType | undefined;
  value?: string | undefined;
};

export const PageDuplicatePageWidth = {
  Default: "default",
  Wide: "wide",
  Full: "full",
} as const;
export type PageDuplicatePageWidth = ClosedEnum<typeof PageDuplicatePageWidth>;

/**
 * Page type
 */
export const PageDuplicateType = {
  Static: "static",
  Markdown: "markdown",
  Server: "server",
  Proxy: "proxy",
} as const;
/**
 * Page type
 */
export type PageDuplicateType = ClosedEnum<typeof PageDuplicateType>;

export const PageDuplicatePermission = {
  Read: "read",
  Write: "write",
} as const;
export type PageDuplicatePermission = ClosedEnum<
  typeof PageDuplicatePermission
>;

export type PageDuplicatePage = {
  uid?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  icon?: PageDuplicateIcon | null | undefined;
  cover?: string | null | undefined;
  pageWidth?: PageDuplicatePageWidth | null | undefined;
  showToc?: boolean | null | undefined;
  /**
   * Page type
   */
  type?: PageDuplicateType | undefined;
  /**
   * Page permissions
   */
  permission?: Array<PageDuplicatePermission> | undefined;
  path?: string | undefined;
  skillContent?: string | null | undefined;
  updatedAt?: string | null | undefined;
  file?: string | null | undefined;
  command?: string | null | undefined;
  port?: number | null | undefined;
  readyPattern?: string | null | undefined;
  timeout?: number | null | undefined;
  url?: string | null | undefined;
  headers?: { [k: string]: string } | null | undefined;
};

/**
 * Default Response
 */
export type PageDuplicateResponseBody = {
  success?: boolean | undefined;
  error?: string | null | undefined;
  page?: PageDuplicatePage | undefined;
};

export type PageDuplicateResponse =
  | PageDuplicateResponseBody
  | PageDuplicatePageResponseBody;

/** @internal */
export type PageDuplicateRequestBody$Outbound = {
  workspace_path: string;
  uid: string;
};

/** @internal */
export const PageDuplicateRequestBody$outboundSchema: z.ZodType<
  PageDuplicateRequestBody$Outbound,
  z.ZodTypeDef,
  PageDuplicateRequestBody
> = z.object({
  workspacePath: z.string(),
  uid: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicateRequestBody$ {
  /** @deprecated use `PageDuplicateRequestBody$outboundSchema` instead. */
  export const outboundSchema = PageDuplicateRequestBody$outboundSchema;
  /** @deprecated use `PageDuplicateRequestBody$Outbound` instead. */
  export type Outbound = PageDuplicateRequestBody$Outbound;
}

export function pageDuplicateRequestBodyToJSON(
  pageDuplicateRequestBody: PageDuplicateRequestBody,
): string {
  return JSON.stringify(
    PageDuplicateRequestBody$outboundSchema.parse(pageDuplicateRequestBody),
  );
}

/** @internal */
export const PageDuplicatePageResponseBody$inboundSchema: z.ZodType<
  PageDuplicatePageResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
  details: z.any().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicatePageResponseBody$ {
  /** @deprecated use `PageDuplicatePageResponseBody$inboundSchema` instead. */
  export const inboundSchema = PageDuplicatePageResponseBody$inboundSchema;
}

export function pageDuplicatePageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PageDuplicatePageResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageDuplicatePageResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageDuplicatePageResponseBody' from JSON`,
  );
}

/** @internal */
export const PageDuplicatePageType$inboundSchema: z.ZodNativeEnum<
  typeof PageDuplicatePageType
> = z.nativeEnum(PageDuplicatePageType);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicatePageType$ {
  /** @deprecated use `PageDuplicatePageType$inboundSchema` instead. */
  export const inboundSchema = PageDuplicatePageType$inboundSchema;
}

/** @internal */
export const PageDuplicateIcon$inboundSchema: z.ZodType<
  PageDuplicateIcon,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PageDuplicatePageType$inboundSchema.optional(),
  value: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicateIcon$ {
  /** @deprecated use `PageDuplicateIcon$inboundSchema` instead. */
  export const inboundSchema = PageDuplicateIcon$inboundSchema;
}

export function pageDuplicateIconFromJSON(
  jsonString: string,
): SafeParseResult<PageDuplicateIcon, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageDuplicateIcon$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageDuplicateIcon' from JSON`,
  );
}

/** @internal */
export const PageDuplicatePageWidth$inboundSchema: z.ZodNativeEnum<
  typeof PageDuplicatePageWidth
> = z.nativeEnum(PageDuplicatePageWidth);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicatePageWidth$ {
  /** @deprecated use `PageDuplicatePageWidth$inboundSchema` instead. */
  export const inboundSchema = PageDuplicatePageWidth$inboundSchema;
}

/** @internal */
export const PageDuplicateType$inboundSchema: z.ZodNativeEnum<
  typeof PageDuplicateType
> = z.nativeEnum(PageDuplicateType);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicateType$ {
  /** @deprecated use `PageDuplicateType$inboundSchema` instead. */
  export const inboundSchema = PageDuplicateType$inboundSchema;
}

/** @internal */
export const PageDuplicatePermission$inboundSchema: z.ZodNativeEnum<
  typeof PageDuplicatePermission
> = z.nativeEnum(PageDuplicatePermission);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicatePermission$ {
  /** @deprecated use `PageDuplicatePermission$inboundSchema` instead. */
  export const inboundSchema = PageDuplicatePermission$inboundSchema;
}

/** @internal */
export const PageDuplicatePage$inboundSchema: z.ZodType<
  PageDuplicatePage,
  z.ZodTypeDef,
  unknown
> = z.object({
  uid: z.string().optional(),
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  icon: z.nullable(z.lazy(() => PageDuplicateIcon$inboundSchema)).optional(),
  cover: z.nullable(z.string()).optional(),
  page_width: z.nullable(PageDuplicatePageWidth$inboundSchema).optional(),
  show_toc: z.nullable(z.boolean()).optional(),
  type: PageDuplicateType$inboundSchema.optional(),
  permission: z.array(PageDuplicatePermission$inboundSchema).optional(),
  path: z.string().optional(),
  skill_content: z.nullable(z.string()).optional(),
  updated_at: z.nullable(z.string()).optional(),
  file: z.nullable(z.string()).optional(),
  command: z.nullable(z.string()).optional(),
  port: z.nullable(z.number()).optional(),
  ready_pattern: z.nullable(z.string()).optional(),
  timeout: z.nullable(z.number()).optional(),
  url: z.nullable(z.string()).optional(),
  headers: z.nullable(z.record(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "page_width": "pageWidth",
    "show_toc": "showToc",
    "skill_content": "skillContent",
    "updated_at": "updatedAt",
    "ready_pattern": "readyPattern",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicatePage$ {
  /** @deprecated use `PageDuplicatePage$inboundSchema` instead. */
  export const inboundSchema = PageDuplicatePage$inboundSchema;
}

export function pageDuplicatePageFromJSON(
  jsonString: string,
): SafeParseResult<PageDuplicatePage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageDuplicatePage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageDuplicatePage' from JSON`,
  );
}

/** @internal */
export const PageDuplicateResponseBody$inboundSchema: z.ZodType<
  PageDuplicateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.nullable(z.string()).optional(),
  page: z.lazy(() => PageDuplicatePage$inboundSchema).optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicateResponseBody$ {
  /** @deprecated use `PageDuplicateResponseBody$inboundSchema` instead. */
  export const inboundSchema = PageDuplicateResponseBody$inboundSchema;
}

export function pageDuplicateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PageDuplicateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageDuplicateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageDuplicateResponseBody' from JSON`,
  );
}

/** @internal */
export const PageDuplicateResponse$inboundSchema: z.ZodType<
  PageDuplicateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PageDuplicateResponseBody$inboundSchema),
  z.lazy(() => PageDuplicatePageResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageDuplicateResponse$ {
  /** @deprecated use `PageDuplicateResponse$inboundSchema` instead. */
  export const inboundSchema = PageDuplicateResponse$inboundSchema;
}

export function pageDuplicateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PageDuplicateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageDuplicateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageDuplicateResponse' from JSON`,
  );
}
