/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PageCreateApplyTemplateRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Page uid (required)
   */
  uid: string;
  /**
   * Page template id (required)
   */
  templateId: string;
};

/**
 * Default Response
 */
export type PageCreateApplyTemplatePageResponseResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
  details?: any | undefined;
};

/**
 * Default Response
 */
export type PageCreateApplyTemplatePageResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
  details?: any | undefined;
};

export const PageCreateApplyTemplatePageType = {
  Lucide: "lucide",
  Emoji: "emoji",
  Image: "image",
} as const;
export type PageCreateApplyTemplatePageType = ClosedEnum<
  typeof PageCreateApplyTemplatePageType
>;

export type PageCreateApplyTemplateIcon = {
  type?: PageCreateApplyTemplatePageType | undefined;
  value?: string | undefined;
};

export const PageCreateApplyTemplatePageWidth = {
  Default: "default",
  Wide: "wide",
  Full: "full",
} as const;
export type PageCreateApplyTemplatePageWidth = ClosedEnum<
  typeof PageCreateApplyTemplatePageWidth
>;

/**
 * Page type
 */
export const PageCreateApplyTemplateType = {
  Static: "static",
  Markdown: "markdown",
  Server: "server",
  Proxy: "proxy",
} as const;
/**
 * Page type
 */
export type PageCreateApplyTemplateType = ClosedEnum<
  typeof PageCreateApplyTemplateType
>;

export const PageCreateApplyTemplatePermission = {
  Read: "read",
  Write: "write",
} as const;
export type PageCreateApplyTemplatePermission = ClosedEnum<
  typeof PageCreateApplyTemplatePermission
>;

export type PageCreateApplyTemplatePage = {
  uid?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  icon?: PageCreateApplyTemplateIcon | null | undefined;
  cover?: string | null | undefined;
  pageWidth?: PageCreateApplyTemplatePageWidth | null | undefined;
  showToc?: boolean | null | undefined;
  /**
   * Page type
   */
  type?: PageCreateApplyTemplateType | undefined;
  /**
   * Page permissions
   */
  permission?: Array<PageCreateApplyTemplatePermission> | undefined;
  path?: string | undefined;
  skillContent?: string | null | undefined;
  updatedAt?: string | null | undefined;
  file?: string | null | undefined;
  command?: string | null | undefined;
  port?: number | null | undefined;
  readyPattern?: string | null | undefined;
  timeout?: number | null | undefined;
  url?: string | null | undefined;
  headers?: { [k: string]: string } | null | undefined;
};

/**
 * Default Response
 */
export type PageCreateApplyTemplateResponseBody = {
  success?: boolean | undefined;
  page?: PageCreateApplyTemplatePage | null | undefined;
  error?: string | null | undefined;
};

export type PageCreateApplyTemplateResponse =
  | PageCreateApplyTemplateResponseBody
  | PageCreateApplyTemplatePageResponseBody
  | PageCreateApplyTemplatePageResponseResponseBody;

/** @internal */
export type PageCreateApplyTemplateRequestBody$Outbound = {
  workspace_path: string;
  uid: string;
  template_id: string;
};

/** @internal */
export const PageCreateApplyTemplateRequestBody$outboundSchema: z.ZodType<
  PageCreateApplyTemplateRequestBody$Outbound,
  z.ZodTypeDef,
  PageCreateApplyTemplateRequestBody
> = z.object({
  workspacePath: z.string(),
  uid: z.string(),
  templateId: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
    templateId: "template_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplateRequestBody$ {
  /** @deprecated use `PageCreateApplyTemplateRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PageCreateApplyTemplateRequestBody$outboundSchema;
  /** @deprecated use `PageCreateApplyTemplateRequestBody$Outbound` instead. */
  export type Outbound = PageCreateApplyTemplateRequestBody$Outbound;
}

export function pageCreateApplyTemplateRequestBodyToJSON(
  pageCreateApplyTemplateRequestBody: PageCreateApplyTemplateRequestBody,
): string {
  return JSON.stringify(
    PageCreateApplyTemplateRequestBody$outboundSchema.parse(
      pageCreateApplyTemplateRequestBody,
    ),
  );
}

/** @internal */
export const PageCreateApplyTemplatePageResponseResponseBody$inboundSchema:
  z.ZodType<
    PageCreateApplyTemplatePageResponseResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    success: z.boolean().optional(),
    error: z.string().optional(),
    details: z.any().optional(),
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplatePageResponseResponseBody$ {
  /** @deprecated use `PageCreateApplyTemplatePageResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PageCreateApplyTemplatePageResponseResponseBody$inboundSchema;
}

export function pageCreateApplyTemplatePageResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PageCreateApplyTemplatePageResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PageCreateApplyTemplatePageResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PageCreateApplyTemplatePageResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PageCreateApplyTemplatePageResponseBody$inboundSchema: z.ZodType<
  PageCreateApplyTemplatePageResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
  details: z.any().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplatePageResponseBody$ {
  /** @deprecated use `PageCreateApplyTemplatePageResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PageCreateApplyTemplatePageResponseBody$inboundSchema;
}

export function pageCreateApplyTemplatePageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PageCreateApplyTemplatePageResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PageCreateApplyTemplatePageResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PageCreateApplyTemplatePageResponseBody' from JSON`,
  );
}

/** @internal */
export const PageCreateApplyTemplatePageType$inboundSchema: z.ZodNativeEnum<
  typeof PageCreateApplyTemplatePageType
> = z.nativeEnum(PageCreateApplyTemplatePageType);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplatePageType$ {
  /** @deprecated use `PageCreateApplyTemplatePageType$inboundSchema` instead. */
  export const inboundSchema = PageCreateApplyTemplatePageType$inboundSchema;
}

/** @internal */
export const PageCreateApplyTemplateIcon$inboundSchema: z.ZodType<
  PageCreateApplyTemplateIcon,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PageCreateApplyTemplatePageType$inboundSchema.optional(),
  value: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplateIcon$ {
  /** @deprecated use `PageCreateApplyTemplateIcon$inboundSchema` instead. */
  export const inboundSchema = PageCreateApplyTemplateIcon$inboundSchema;
}

export function pageCreateApplyTemplateIconFromJSON(
  jsonString: string,
): SafeParseResult<PageCreateApplyTemplateIcon, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageCreateApplyTemplateIcon$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageCreateApplyTemplateIcon' from JSON`,
  );
}

/** @internal */
export const PageCreateApplyTemplatePageWidth$inboundSchema: z.ZodNativeEnum<
  typeof PageCreateApplyTemplatePageWidth
> = z.nativeEnum(PageCreateApplyTemplatePageWidth);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplatePageWidth$ {
  /** @deprecated use `PageCreateApplyTemplatePageWidth$inboundSchema` instead. */
  export const inboundSchema = PageCreateApplyTemplatePageWidth$inboundSchema;
}

/** @internal */
export const PageCreateApplyTemplateType$inboundSchema: z.ZodNativeEnum<
  typeof PageCreateApplyTemplateType
> = z.nativeEnum(PageCreateApplyTemplateType);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplateType$ {
  /** @deprecated use `PageCreateApplyTemplateType$inboundSchema` instead. */
  export const inboundSchema = PageCreateApplyTemplateType$inboundSchema;
}

/** @internal */
export const PageCreateApplyTemplatePermission$inboundSchema: z.ZodNativeEnum<
  typeof PageCreateApplyTemplatePermission
> = z.nativeEnum(PageCreateApplyTemplatePermission);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplatePermission$ {
  /** @deprecated use `PageCreateApplyTemplatePermission$inboundSchema` instead. */
  export const inboundSchema = PageCreateApplyTemplatePermission$inboundSchema;
}

/** @internal */
export const PageCreateApplyTemplatePage$inboundSchema: z.ZodType<
  PageCreateApplyTemplatePage,
  z.ZodTypeDef,
  unknown
> = z.object({
  uid: z.string().optional(),
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  icon: z.nullable(z.lazy(() => PageCreateApplyTemplateIcon$inboundSchema))
    .optional(),
  cover: z.nullable(z.string()).optional(),
  page_width: z.nullable(PageCreateApplyTemplatePageWidth$inboundSchema)
    .optional(),
  show_toc: z.nullable(z.boolean()).optional(),
  type: PageCreateApplyTemplateType$inboundSchema.optional(),
  permission: z.array(PageCreateApplyTemplatePermission$inboundSchema)
    .optional(),
  path: z.string().optional(),
  skill_content: z.nullable(z.string()).optional(),
  updated_at: z.nullable(z.string()).optional(),
  file: z.nullable(z.string()).optional(),
  command: z.nullable(z.string()).optional(),
  port: z.nullable(z.number()).optional(),
  ready_pattern: z.nullable(z.string()).optional(),
  timeout: z.nullable(z.number()).optional(),
  url: z.nullable(z.string()).optional(),
  headers: z.nullable(z.record(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "page_width": "pageWidth",
    "show_toc": "showToc",
    "skill_content": "skillContent",
    "updated_at": "updatedAt",
    "ready_pattern": "readyPattern",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplatePage$ {
  /** @deprecated use `PageCreateApplyTemplatePage$inboundSchema` instead. */
  export const inboundSchema = PageCreateApplyTemplatePage$inboundSchema;
}

export function pageCreateApplyTemplatePageFromJSON(
  jsonString: string,
): SafeParseResult<PageCreateApplyTemplatePage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageCreateApplyTemplatePage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageCreateApplyTemplatePage' from JSON`,
  );
}

/** @internal */
export const PageCreateApplyTemplateResponseBody$inboundSchema: z.ZodType<
  PageCreateApplyTemplateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  page: z.nullable(z.lazy(() => PageCreateApplyTemplatePage$inboundSchema))
    .optional(),
  error: z.nullable(z.string()).optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplateResponseBody$ {
  /** @deprecated use `PageCreateApplyTemplateResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PageCreateApplyTemplateResponseBody$inboundSchema;
}

export function pageCreateApplyTemplateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PageCreateApplyTemplateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PageCreateApplyTemplateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageCreateApplyTemplateResponseBody' from JSON`,
  );
}

/** @internal */
export const PageCreateApplyTemplateResponse$inboundSchema: z.ZodType<
  PageCreateApplyTemplateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PageCreateApplyTemplateResponseBody$inboundSchema),
  z.lazy(() => PageCreateApplyTemplatePageResponseBody$inboundSchema),
  z.lazy(() => PageCreateApplyTemplatePageResponseResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PageCreateApplyTemplateResponse$ {
  /** @deprecated use `PageCreateApplyTemplateResponse$inboundSchema` instead. */
  export const inboundSchema = PageCreateApplyTemplateResponse$inboundSchema;
}

export function pageCreateApplyTemplateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PageCreateApplyTemplateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PageCreateApplyTemplateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PageCreateApplyTemplateResponse' from JSON`,
  );
}
