/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PatchApiAgentIdRequest = {
  id: string;
};

/** @internal */
export type PatchApiAgentIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const PatchApiAgentIdRequest$outboundSchema: z.ZodType<
  PatchApiAgentIdRequest$Outbound,
  z.ZodTypeDef,
  PatchApiAgentIdRequest
> = z.object({
  id: z.string(),
});

export function patchApiAgentIdRequestToJSON(
  patchApiAgentIdRequest: PatchApiAgentIdRequest,
): string {
  return JSON.stringify(
    PatchApiAgentIdRequest$outboundSchema.parse(patchApiAgentIdRequest),
  );
}
