/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PatchApiKanbanTasksTaskIdCommentsCommentIdRequest = {
  commentId: string;
  taskId: string;
};

/** @internal */
export type PatchApiKanbanTasksTaskIdCommentsCommentIdRequest$Outbound = {
  commentId: string;
  taskId: string;
};

/** @internal */
export const PatchApiKanbanTasksTaskIdCommentsCommentIdRequest$outboundSchema:
  z.ZodType<
    PatchApiKanbanTasksTaskIdCommentsCommentIdRequest$Outbound,
    z.ZodTypeDef,
    PatchApiKanbanTasksTaskIdCommentsCommentIdRequest
  > = z.object({
    commentId: z.string(),
    taskId: z.string(),
  });

export function patchApiKanbanTasksTaskIdCommentsCommentIdRequestToJSON(
  patchApiKanbanTasksTaskIdCommentsCommentIdRequest:
    PatchApiKanbanTasksTaskIdCommentsCommentIdRequest,
): string {
  return JSON.stringify(
    PatchApiKanbanTasksTaskIdCommentsCommentIdRequest$outboundSchema.parse(
      patchApiKanbanTasksTaskIdCommentsCommentIdRequest,
    ),
  );
}
