/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PatchApiSessionsIdRequest = {
  id: string;
};

/** @internal */
export type PatchApiSessionsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const PatchApiSessionsIdRequest$outboundSchema: z.ZodType<
  PatchApiSessionsIdRequest$Outbound,
  z.ZodTypeDef,
  PatchApiSessionsIdRequest
> = z.object({
  id: z.string(),
});

export function patchApiSessionsIdRequestToJSON(
  patchApiSessionsIdRequest: PatchApiSessionsIdRequest,
): string {
  return JSON.stringify(
    PatchApiSessionsIdRequest$outboundSchema.parse(patchApiSessionsIdRequest),
  );
}
