/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PetExportRequest = {
  id: string;
};

/** @internal */
export type PetExportRequest$Outbound = {
  id: string;
};

/** @internal */
export const PetExportRequest$outboundSchema: z.ZodType<
  PetExportRequest$Outbound,
  z.ZodTypeDef,
  PetExportRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PetExportRequest$ {
  /** @deprecated use `PetExportRequest$outboundSchema` instead. */
  export const outboundSchema = PetExportRequest$outboundSchema;
  /** @deprecated use `PetExportRequest$Outbound` instead. */
  export type Outbound = PetExportRequest$Outbound;
}

export function petExportRequestToJSON(
  petExportRequest: PetExportRequest,
): string {
  return JSON.stringify(
    PetExportRequest$outboundSchema.parse(petExportRequest),
  );
}
