/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PetGetPreviewRequest = {
  id: string;
};

/** @internal */
export type PetGetPreviewRequest$Outbound = {
  id: string;
};

/** @internal */
export const PetGetPreviewRequest$outboundSchema: z.ZodType<
  PetGetPreviewRequest$Outbound,
  z.ZodTypeDef,
  PetGetPreviewRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PetGetPreviewRequest$ {
  /** @deprecated use `PetGetPreviewRequest$outboundSchema` instead. */
  export const outboundSchema = PetGetPreviewRequest$outboundSchema;
  /** @deprecated use `PetGetPreviewRequest$Outbound` instead. */
  export type Outbound = PetGetPreviewRequest$Outbound;
}

export function petGetPreviewRequestToJSON(
  petGetPreviewRequest: PetGetPreviewRequest,
): string {
  return JSON.stringify(
    PetGetPreviewRequest$outboundSchema.parse(petGetPreviewRequest),
  );
}
