/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PetRemoveSourceRequest = {
  name: string;
};

/** @internal */
export type PetRemoveSourceRequest$Outbound = {
  name: string;
};

/** @internal */
export const PetRemoveSourceRequest$outboundSchema: z.ZodType<
  PetRemoveSourceRequest$Outbound,
  z.ZodTypeDef,
  PetRemoveSourceRequest
> = z.object({
  name: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PetRemoveSourceRequest$ {
  /** @deprecated use `PetRemoveSourceRequest$outboundSchema` instead. */
  export const outboundSchema = PetRemoveSourceRequest$outboundSchema;
  /** @deprecated use `PetRemoveSourceRequest$Outbound` instead. */
  export type Outbound = PetRemoveSourceRequest$Outbound;
}

export function petRemoveSourceRequestToJSON(
  petRemoveSourceRequest: PetRemoveSourceRequest,
): string {
  return JSON.stringify(
    PetRemoveSourceRequest$outboundSchema.parse(petRemoveSourceRequest),
  );
}
