/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiTaskValidateContextRequestBody = {
  /**
   * Task ID or directory
   */
  taskId: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiTaskValidateContextTasksResponseResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskValidateContextTasksResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskValidateContextResponseBody = {
  allValid?: boolean | undefined;
  missingCount?: number | undefined;
  missingFiles?: Array<string> | undefined;
  success?: boolean | undefined;
  taskId?: string | undefined;
  validCount?: number | undefined;
};

export type PostApiTaskValidateContextResponse =
  | PostApiTaskValidateContextResponseBody
  | PostApiTaskValidateContextTasksResponseBody
  | PostApiTaskValidateContextTasksResponseResponseBody;

/** @internal */
export type PostApiTaskValidateContextRequestBody$Outbound = {
  task_id: string;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskValidateContextRequestBody$outboundSchema: z.ZodType<
  PostApiTaskValidateContextRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskValidateContextRequestBody
> = z.object({
  taskId: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskValidateContextRequestBodyToJSON(
  postApiTaskValidateContextRequestBody: PostApiTaskValidateContextRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskValidateContextRequestBody$outboundSchema.parse(
      postApiTaskValidateContextRequestBody,
    ),
  );
}

/** @internal */
export const PostApiTaskValidateContextTasksResponseResponseBody$inboundSchema:
  z.ZodType<
    PostApiTaskValidateContextTasksResponseResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
  });

export function postApiTaskValidateContextTasksResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiTaskValidateContextTasksResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskValidateContextTasksResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiTaskValidateContextTasksResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskValidateContextTasksResponseBody$inboundSchema:
  z.ZodType<
    PostApiTaskValidateContextTasksResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
  });

export function postApiTaskValidateContextTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiTaskValidateContextTasksResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskValidateContextTasksResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiTaskValidateContextTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskValidateContextResponseBody$inboundSchema: z.ZodType<
  PostApiTaskValidateContextResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  all_valid: z.boolean().optional(),
  missing_count: z.number().optional(),
  missing_files: z.array(z.string()).optional(),
  success: z.boolean().optional(),
  task_id: z.string().optional(),
  valid_count: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "all_valid": "allValid",
    "missing_count": "missingCount",
    "missing_files": "missingFiles",
    "task_id": "taskId",
    "valid_count": "validCount",
  });
});

export function postApiTaskValidateContextResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskValidateContextResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskValidateContextResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskValidateContextResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskValidateContextResponse$inboundSchema: z.ZodType<
  PostApiTaskValidateContextResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiTaskValidateContextResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskValidateContextTasksResponseBody$inboundSchema),
  z.lazy(() =>
    PostApiTaskValidateContextTasksResponseResponseBody$inboundSchema
  ),
]);

export function postApiTaskValidateContextResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskValidateContextResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskValidateContextResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskValidateContextResponse' from JSON`,
  );
}
