/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PostApiPageCreateType = {
  Lucide: "lucide",
  Emoji: "emoji",
  Image: "image",
} as const;
export type PostApiPageCreateType = ClosedEnum<typeof PostApiPageCreateType>;

/**
 * Page icon data
 */
export type Icon = {
  type?: PostApiPageCreateType | undefined;
  value?: string | undefined;
};

/**
 * Page type (required)
 */
export const Type = {
  Static: "static",
  Markdown: "markdown",
  Server: "server",
  Proxy: "proxy",
} as const;
/**
 * Page type (required)
 */
export type Type = ClosedEnum<typeof Type>;

export type PostApiPageCreateRequestBody = {
  /**
   * Start command for server pages
   */
  command?: string | undefined;
  /**
   * Page description
   */
  description?: string | undefined;
  /**
   * Entry file for static pages
   */
  file?: string | undefined;
  /**
   * Headers for proxy pages
   */
  headers?: { [k: string]: string } | undefined;
  /**
   * Page icon data
   */
  icon?: Icon | null | undefined;
  /**
   * Page name (required)
   */
  name: string;
  /**
   * Parent page uid for creating subpages
   */
  parentUid?: string | undefined;
  /**
   * Port for server pages
   */
  port?: number | undefined;
  /**
   * Ready pattern for server pages
   */
  readyPattern?: string | undefined;
  /**
   * Page slug (optional, used to generate uid)
   */
  slug?: string | undefined;
  /**
   * Timeout for server pages
   */
  timeout?: number | undefined;
  /**
   * Page type (required)
   */
  type: Type;
  /**
   * URL for proxy pages
   */
  url?: string | undefined;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiPageCreatePageResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

export const PostApiPageCreatePageResponseType = {
  Lucide: "lucide",
  Emoji: "emoji",
  Image: "image",
} as const;
export type PostApiPageCreatePageResponseType = ClosedEnum<
  typeof PostApiPageCreatePageResponseType
>;

export type PostApiPageCreateIcon = {
  type?: PostApiPageCreatePageResponseType | undefined;
  value?: string | undefined;
};

export const PostApiPageCreatePageWidth = {
  Default: "default",
  Wide: "wide",
  Full: "full",
} as const;
export type PostApiPageCreatePageWidth = ClosedEnum<
  typeof PostApiPageCreatePageWidth
>;

export const Permission = {
  Read: "read",
  Write: "write",
} as const;
export type Permission = ClosedEnum<typeof Permission>;

/**
 * Page type
 */
export const PostApiPageCreatePageType = {
  Static: "static",
  Markdown: "markdown",
  Server: "server",
  Proxy: "proxy",
} as const;
/**
 * Page type
 */
export type PostApiPageCreatePageType = ClosedEnum<
  typeof PostApiPageCreatePageType
>;

export type Page = {
  command?: string | null | undefined;
  cover?: string | null | undefined;
  description?: string | null | undefined;
  file?: string | null | undefined;
  headers?: { [k: string]: string } | null | undefined;
  icon?: PostApiPageCreateIcon | null | undefined;
  name?: string | undefined;
  pageWidth?: PostApiPageCreatePageWidth | null | undefined;
  path?: string | undefined;
  /**
   * Page permissions
   */
  permission?: Array<Permission> | undefined;
  port?: number | null | undefined;
  readyPattern?: string | null | undefined;
  showToc?: boolean | null | undefined;
  skillContent?: string | null | undefined;
  timeout?: number | null | undefined;
  /**
   * Page type
   */
  type?: PostApiPageCreatePageType | undefined;
  uid?: string | undefined;
  updatedAt?: string | null | undefined;
  url?: string | null | undefined;
};

/**
 * Default Response
 */
export type PostApiPageCreateResponseBody = {
  error?: string | null | undefined;
  page?: Page | null | undefined;
  success?: boolean | undefined;
};

export type PostApiPageCreateResponse =
  | PostApiPageCreateResponseBody
  | PostApiPageCreatePageResponseBody;

/** @internal */
export const PostApiPageCreateType$outboundSchema: z.ZodNativeEnum<
  typeof PostApiPageCreateType
> = z.nativeEnum(PostApiPageCreateType);

/** @internal */
export type Icon$Outbound = {
  type?: string | undefined;
  value?: string | undefined;
};

/** @internal */
export const Icon$outboundSchema: z.ZodType<Icon$Outbound, z.ZodTypeDef, Icon> =
  z.object({
    type: PostApiPageCreateType$outboundSchema.optional(),
    value: z.string().optional(),
  });

export function iconToJSON(icon: Icon): string {
  return JSON.stringify(Icon$outboundSchema.parse(icon));
}

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export type PostApiPageCreateRequestBody$Outbound = {
  command?: string | undefined;
  description?: string | undefined;
  file?: string | undefined;
  headers?: { [k: string]: string } | undefined;
  icon?: Icon$Outbound | null | undefined;
  name: string;
  parent_uid?: string | undefined;
  port?: number | undefined;
  ready_pattern?: string | undefined;
  slug?: string | undefined;
  timeout?: number | undefined;
  type: string;
  url?: string | undefined;
  workspace_path: string;
};

/** @internal */
export const PostApiPageCreateRequestBody$outboundSchema: z.ZodType<
  PostApiPageCreateRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiPageCreateRequestBody
> = z.object({
  command: z.string().optional(),
  description: z.string().optional(),
  file: z.string().optional(),
  headers: z.record(z.string()).optional(),
  icon: z.nullable(z.lazy(() => Icon$outboundSchema)).optional(),
  name: z.string(),
  parentUid: z.string().optional(),
  port: z.number().optional(),
  readyPattern: z.string().optional(),
  slug: z.string().optional(),
  timeout: z.number().optional(),
  type: Type$outboundSchema,
  url: z.string().optional(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    parentUid: "parent_uid",
    readyPattern: "ready_pattern",
    workspacePath: "workspace_path",
  });
});

export function postApiPageCreateRequestBodyToJSON(
  postApiPageCreateRequestBody: PostApiPageCreateRequestBody,
): string {
  return JSON.stringify(
    PostApiPageCreateRequestBody$outboundSchema.parse(
      postApiPageCreateRequestBody,
    ),
  );
}

/** @internal */
export const PostApiPageCreatePageResponseBody$inboundSchema: z.ZodType<
  PostApiPageCreatePageResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiPageCreatePageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageCreatePageResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageCreatePageResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageCreatePageResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiPageCreatePageResponseType$inboundSchema: z.ZodNativeEnum<
  typeof PostApiPageCreatePageResponseType
> = z.nativeEnum(PostApiPageCreatePageResponseType);

/** @internal */
export const PostApiPageCreateIcon$inboundSchema: z.ZodType<
  PostApiPageCreateIcon,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PostApiPageCreatePageResponseType$inboundSchema.optional(),
  value: z.string().optional(),
});

export function postApiPageCreateIconFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageCreateIcon, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageCreateIcon$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageCreateIcon' from JSON`,
  );
}

/** @internal */
export const PostApiPageCreatePageWidth$inboundSchema: z.ZodNativeEnum<
  typeof PostApiPageCreatePageWidth
> = z.nativeEnum(PostApiPageCreatePageWidth);

/** @internal */
export const Permission$inboundSchema: z.ZodNativeEnum<typeof Permission> = z
  .nativeEnum(Permission);

/** @internal */
export const PostApiPageCreatePageType$inboundSchema: z.ZodNativeEnum<
  typeof PostApiPageCreatePageType
> = z.nativeEnum(PostApiPageCreatePageType);

/** @internal */
export const Page$inboundSchema: z.ZodType<Page, z.ZodTypeDef, unknown> = z
  .object({
    command: z.nullable(z.string()).optional(),
    cover: z.nullable(z.string()).optional(),
    description: z.nullable(z.string()).optional(),
    file: z.nullable(z.string()).optional(),
    headers: z.nullable(z.record(z.string())).optional(),
    icon: z.nullable(z.lazy(() => PostApiPageCreateIcon$inboundSchema))
      .optional(),
    name: z.string().optional(),
    page_width: z.nullable(PostApiPageCreatePageWidth$inboundSchema).optional(),
    path: z.string().optional(),
    permission: z.array(Permission$inboundSchema).optional(),
    port: z.nullable(z.number()).optional(),
    ready_pattern: z.nullable(z.string()).optional(),
    show_toc: z.nullable(z.boolean()).optional(),
    skill_content: z.nullable(z.string()).optional(),
    timeout: z.nullable(z.number()).optional(),
    type: PostApiPageCreatePageType$inboundSchema.optional(),
    uid: z.string().optional(),
    updated_at: z.nullable(z.string()).optional(),
    url: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "page_width": "pageWidth",
      "ready_pattern": "readyPattern",
      "show_toc": "showToc",
      "skill_content": "skillContent",
      "updated_at": "updatedAt",
    });
  });

export function pageFromJSON(
  jsonString: string,
): SafeParseResult<Page, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Page$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Page' from JSON`,
  );
}

/** @internal */
export const PostApiPageCreateResponseBody$inboundSchema: z.ZodType<
  PostApiPageCreateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.nullable(z.string()).optional(),
  page: z.nullable(z.lazy(() => Page$inboundSchema)).optional(),
  success: z.boolean().optional(),
});

export function postApiPageCreateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageCreateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageCreateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageCreateResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiPageCreateResponse$inboundSchema: z.ZodType<
  PostApiPageCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiPageCreateResponseBody$inboundSchema),
  z.lazy(() => PostApiPageCreatePageResponseBody$inboundSchema),
]);

export function postApiPageCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageCreateResponse' from JSON`,
  );
}
