/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiTaskBatchEnqueueRequestBody = {
  /**
   * Agent ID to use for all tasks
   */
  agentId?: string | undefined;
  /**
   * Task directories or IDs to enqueue
   */
  taskDirs: Array<string>;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

export type Results = {
  error?: string | undefined;
  queueTaskId?: string | undefined;
  success?: boolean | undefined;
  taskDir?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskBatchEnqueueResponseBody = {
  failed?: number | undefined;
  queued?: number | undefined;
  results?: Array<Results> | undefined;
  success?: boolean | undefined;
};

/** @internal */
export type PostApiTaskBatchEnqueueRequestBody$Outbound = {
  agent_id?: string | undefined;
  task_dirs: Array<string>;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskBatchEnqueueRequestBody$outboundSchema: z.ZodType<
  PostApiTaskBatchEnqueueRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskBatchEnqueueRequestBody
> = z.object({
  agentId: z.string().optional(),
  taskDirs: z.array(z.string()),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    agentId: "agent_id",
    taskDirs: "task_dirs",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskBatchEnqueueRequestBodyToJSON(
  postApiTaskBatchEnqueueRequestBody: PostApiTaskBatchEnqueueRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskBatchEnqueueRequestBody$outboundSchema.parse(
      postApiTaskBatchEnqueueRequestBody,
    ),
  );
}

/** @internal */
export const Results$inboundSchema: z.ZodType<Results, z.ZodTypeDef, unknown> =
  z.object({
    error: z.string().optional(),
    queue_task_id: z.string().optional(),
    success: z.boolean().optional(),
    task_dir: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "queue_task_id": "queueTaskId",
      "task_dir": "taskDir",
    });
  });

export function resultsFromJSON(
  jsonString: string,
): SafeParseResult<Results, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Results$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Results' from JSON`,
  );
}

/** @internal */
export const PostApiTaskBatchEnqueueResponseBody$inboundSchema: z.ZodType<
  PostApiTaskBatchEnqueueResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  failed: z.number().optional(),
  queued: z.number().optional(),
  results: z.array(z.lazy(() => Results$inboundSchema)).optional(),
  success: z.boolean().optional(),
});

export function postApiTaskBatchEnqueueResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskBatchEnqueueResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskBatchEnqueueResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskBatchEnqueueResponseBody' from JSON`,
  );
}
