/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiRewardTypesRequestBody = {
  /**
   * Reward type description (required)
   */
  description: string;
  /**
   * Reward type name (required)
   */
  name: string;
  /**
   * Prompt content (optional)
   */
  promptContent?: string | undefined;
  /**
   * Default weight (optional)
   */
  weightDefault?: number | undefined;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiRewardTypesRewardResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

export const PostApiRewardTypesSource = {
  Builtin: "builtin",
  Custom: "custom",
} as const;
export type PostApiRewardTypesSource = ClosedEnum<
  typeof PostApiRewardTypesSource
>;

export type PostApiRewardTypesRewardType = {
  description?: string | undefined;
  name?: string | undefined;
  promptPath?: string | undefined;
  source?: PostApiRewardTypesSource | undefined;
  weightDefault?: number | null | undefined;
};

/**
 * Default Response
 */
export type PostApiRewardTypesResponseBody = {
  filePath?: string | undefined;
  rewardType?: PostApiRewardTypesRewardType | undefined;
  success?: boolean | undefined;
};

export type PostApiRewardTypesResponse =
  | PostApiRewardTypesResponseBody
  | PostApiRewardTypesRewardResponseBody;

/** @internal */
export type PostApiRewardTypesRequestBody$Outbound = {
  description: string;
  name: string;
  prompt_content?: string | undefined;
  weight_default?: number | undefined;
  workspace_path: string;
};

/** @internal */
export const PostApiRewardTypesRequestBody$outboundSchema: z.ZodType<
  PostApiRewardTypesRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiRewardTypesRequestBody
> = z.object({
  description: z.string(),
  name: z.string(),
  promptContent: z.string().optional(),
  weightDefault: z.number().optional(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    promptContent: "prompt_content",
    weightDefault: "weight_default",
    workspacePath: "workspace_path",
  });
});

export function postApiRewardTypesRequestBodyToJSON(
  postApiRewardTypesRequestBody: PostApiRewardTypesRequestBody,
): string {
  return JSON.stringify(
    PostApiRewardTypesRequestBody$outboundSchema.parse(
      postApiRewardTypesRequestBody,
    ),
  );
}

/** @internal */
export const PostApiRewardTypesRewardResponseBody$inboundSchema: z.ZodType<
  PostApiRewardTypesRewardResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiRewardTypesRewardResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRewardTypesRewardResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiRewardTypesRewardResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRewardTypesRewardResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiRewardTypesSource$inboundSchema: z.ZodNativeEnum<
  typeof PostApiRewardTypesSource
> = z.nativeEnum(PostApiRewardTypesSource);

/** @internal */
export const PostApiRewardTypesRewardType$inboundSchema: z.ZodType<
  PostApiRewardTypesRewardType,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().optional(),
  name: z.string().optional(),
  prompt_path: z.string().optional(),
  source: PostApiRewardTypesSource$inboundSchema.optional(),
  weight_default: z.nullable(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    "prompt_path": "promptPath",
    "weight_default": "weightDefault",
  });
});

export function postApiRewardTypesRewardTypeFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRewardTypesRewardType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiRewardTypesRewardType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRewardTypesRewardType' from JSON`,
  );
}

/** @internal */
export const PostApiRewardTypesResponseBody$inboundSchema: z.ZodType<
  PostApiRewardTypesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  file_path: z.string().optional(),
  reward_type: z.lazy(() => PostApiRewardTypesRewardType$inboundSchema)
    .optional(),
  success: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "file_path": "filePath",
    "reward_type": "rewardType",
  });
});

export function postApiRewardTypesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRewardTypesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiRewardTypesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRewardTypesResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiRewardTypesResponse$inboundSchema: z.ZodType<
  PostApiRewardTypesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiRewardTypesResponseBody$inboundSchema),
  z.lazy(() => PostApiRewardTypesRewardResponseBody$inboundSchema),
]);

export function postApiRewardTypesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRewardTypesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiRewardTypesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRewardTypesResponse' from JSON`,
  );
}
