/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiCronIdRunRequest = {
  id: string;
};

/** @internal */
export type PostApiCronIdRunRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostApiCronIdRunRequest$outboundSchema: z.ZodType<
  PostApiCronIdRunRequest$Outbound,
  z.ZodTypeDef,
  PostApiCronIdRunRequest
> = z.object({
  id: z.string(),
});

export function postApiCronIdRunRequestToJSON(
  postApiCronIdRunRequest: PostApiCronIdRunRequest,
): string {
  return JSON.stringify(
    PostApiCronIdRunRequest$outboundSchema.parse(postApiCronIdRunRequest),
  );
}
