/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiPageUpdateContentRequestBody = {
  /**
   * New markdown content (required)
   */
  content: string;
  /**
   * Page uid (required)
   */
  uid: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiPageUpdateContentPageResponseResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

/**
 * Default Response
 */
export type PostApiPageUpdateContentPageResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

/**
 * Default Response
 */
export type PostApiPageUpdateContentResponseBody = {
  error?: string | null | undefined;
  success?: boolean | undefined;
  uid?: string | null | undefined;
};

export type PostApiPageUpdateContentResponse =
  | PostApiPageUpdateContentResponseBody
  | PostApiPageUpdateContentPageResponseBody
  | PostApiPageUpdateContentPageResponseResponseBody;

/** @internal */
export type PostApiPageUpdateContentRequestBody$Outbound = {
  content: string;
  uid: string;
  workspace_path: string;
};

/** @internal */
export const PostApiPageUpdateContentRequestBody$outboundSchema: z.ZodType<
  PostApiPageUpdateContentRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiPageUpdateContentRequestBody
> = z.object({
  content: z.string(),
  uid: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});

export function postApiPageUpdateContentRequestBodyToJSON(
  postApiPageUpdateContentRequestBody: PostApiPageUpdateContentRequestBody,
): string {
  return JSON.stringify(
    PostApiPageUpdateContentRequestBody$outboundSchema.parse(
      postApiPageUpdateContentRequestBody,
    ),
  );
}

/** @internal */
export const PostApiPageUpdateContentPageResponseResponseBody$inboundSchema:
  z.ZodType<
    PostApiPageUpdateContentPageResponseResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    success: z.boolean().optional(),
  });

export function postApiPageUpdateContentPageResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiPageUpdateContentPageResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiPageUpdateContentPageResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiPageUpdateContentPageResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiPageUpdateContentPageResponseBody$inboundSchema: z.ZodType<
  PostApiPageUpdateContentPageResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiPageUpdateContentPageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiPageUpdateContentPageResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiPageUpdateContentPageResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiPageUpdateContentPageResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiPageUpdateContentResponseBody$inboundSchema: z.ZodType<
  PostApiPageUpdateContentResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.nullable(z.string()).optional(),
  success: z.boolean().optional(),
  uid: z.nullable(z.string()).optional(),
});

export function postApiPageUpdateContentResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageUpdateContentResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiPageUpdateContentResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageUpdateContentResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiPageUpdateContentResponse$inboundSchema: z.ZodType<
  PostApiPageUpdateContentResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiPageUpdateContentResponseBody$inboundSchema),
  z.lazy(() => PostApiPageUpdateContentPageResponseBody$inboundSchema),
  z.lazy(() => PostApiPageUpdateContentPageResponseResponseBody$inboundSchema),
]);

export function postApiPageUpdateContentResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageUpdateContentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageUpdateContentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageUpdateContentResponse' from JSON`,
  );
}
