/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiPetSetIdRequest = {
  id: string;
};

/** @internal */
export type PostApiPetSetIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostApiPetSetIdRequest$outboundSchema: z.ZodType<
  PostApiPetSetIdRequest$Outbound,
  z.ZodTypeDef,
  PostApiPetSetIdRequest
> = z.object({
  id: z.string(),
});

export function postApiPetSetIdRequestToJSON(
  postApiPetSetIdRequest: PostApiPetSetIdRequest,
): string {
  return JSON.stringify(
    PostApiPetSetIdRequest$outboundSchema.parse(postApiPetSetIdRequest),
  );
}
