/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type PostApiGithubAutofixTasksTaskIdCancelRequest = {
  taskId: string;
};

/** @internal */
export type PostApiGithubAutofixTasksTaskIdCancelRequest$Outbound = {
  task_id: string;
};

/** @internal */
export const PostApiGithubAutofixTasksTaskIdCancelRequest$outboundSchema:
  z.ZodType<
    PostApiGithubAutofixTasksTaskIdCancelRequest$Outbound,
    z.ZodTypeDef,
    PostApiGithubAutofixTasksTaskIdCancelRequest
  > = z.object({
    taskId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      taskId: "task_id",
    });
  });

export function postApiGithubAutofixTasksTaskIdCancelRequestToJSON(
  postApiGithubAutofixTasksTaskIdCancelRequest:
    PostApiGithubAutofixTasksTaskIdCancelRequest,
): string {
  return JSON.stringify(
    PostApiGithubAutofixTasksTaskIdCancelRequest$outboundSchema.parse(
      postApiGithubAutofixTasksTaskIdCancelRequest,
    ),
  );
}
