/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiChannelsIdDefaultRequest = {
  id: string;
};

/** @internal */
export type PostApiChannelsIdDefaultRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostApiChannelsIdDefaultRequest$outboundSchema: z.ZodType<
  PostApiChannelsIdDefaultRequest$Outbound,
  z.ZodTypeDef,
  PostApiChannelsIdDefaultRequest
> = z.object({
  id: z.string(),
});

export function postApiChannelsIdDefaultRequestToJSON(
  postApiChannelsIdDefaultRequest: PostApiChannelsIdDefaultRequest,
): string {
  return JSON.stringify(
    PostApiChannelsIdDefaultRequest$outboundSchema.parse(
      postApiChannelsIdDefaultRequest,
    ),
  );
}
