/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Target = {
  Project: "project",
  Global: "global",
} as const;
export type Target = ClosedEnum<typeof Target>;

export type PostApiMcpInstallRequestBody = {
  /**
   * Force reinstall
   */
  force?: boolean | undefined;
  /**
   * Install spec (name, name@version, gh:user/repo, ./path)
   */
  spec: string;
  target?: Target | undefined;
};

/**
 * Default Response
 */
export type PostApiMcpInstallMcpResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

/**
 * Default Response
 */
export type PostApiMcpInstallResponseBody = {
  message?: string | undefined;
  name?: string | undefined;
  path?: string | undefined;
  source?: string | undefined;
  success?: boolean | undefined;
  target?: string | undefined;
  version?: string | undefined;
};

export type PostApiMcpInstallResponse =
  | PostApiMcpInstallResponseBody
  | PostApiMcpInstallMcpResponseBody;

/** @internal */
export const Target$outboundSchema: z.ZodNativeEnum<typeof Target> = z
  .nativeEnum(Target);

/** @internal */
export type PostApiMcpInstallRequestBody$Outbound = {
  force: boolean;
  spec: string;
  target: string;
};

/** @internal */
export const PostApiMcpInstallRequestBody$outboundSchema: z.ZodType<
  PostApiMcpInstallRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiMcpInstallRequestBody
> = z.object({
  force: z.boolean().default(false),
  spec: z.string(),
  target: Target$outboundSchema.default("project"),
});

export function postApiMcpInstallRequestBodyToJSON(
  postApiMcpInstallRequestBody: PostApiMcpInstallRequestBody,
): string {
  return JSON.stringify(
    PostApiMcpInstallRequestBody$outboundSchema.parse(
      postApiMcpInstallRequestBody,
    ),
  );
}

/** @internal */
export const PostApiMcpInstallMcpResponseBody$inboundSchema: z.ZodType<
  PostApiMcpInstallMcpResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiMcpInstallMcpResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiMcpInstallMcpResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiMcpInstallMcpResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiMcpInstallMcpResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiMcpInstallResponseBody$inboundSchema: z.ZodType<
  PostApiMcpInstallResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  name: z.string().optional(),
  path: z.string().optional(),
  source: z.string().optional(),
  success: z.boolean().optional(),
  target: z.string().optional(),
  version: z.string().optional(),
});

export function postApiMcpInstallResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiMcpInstallResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiMcpInstallResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiMcpInstallResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiMcpInstallResponse$inboundSchema: z.ZodType<
  PostApiMcpInstallResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiMcpInstallResponseBody$inboundSchema),
  z.lazy(() => PostApiMcpInstallMcpResponseBody$inboundSchema),
]);

export function postApiMcpInstallResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiMcpInstallResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiMcpInstallResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiMcpInstallResponse' from JSON`,
  );
}
