/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type PostApiTaskCreateRequestBody = {
  /**
   * Associated agent ID
   */
  agent?: string | undefined;
  /**
   * Assignee developer name
   */
  assignee?: string | undefined;
  /**
   * Custom branch name
   */
  branch?: string | undefined;
  /**
   * Task description
   */
  description?: string | undefined;
  /**
   * Executor type
   */
  executor?: string | undefined;
  /**
   * Model to use
   */
  model?: string | undefined;
  /**
   * Priority (urgent/high/medium/low/none)
   */
  priority?: string | undefined;
  /**
   * Task slug (auto-generated from title if not provided)
   */
  slug?: string | undefined;
  /**
   * Auto-start task after creation
   */
  start?: boolean | undefined;
  /**
   * Task title (required)
   */
  title: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Run in git worktree
   */
  worktree?: boolean | undefined;
};

/** @internal */
export type PostApiTaskCreateRequestBody$Outbound = {
  agent?: string | undefined;
  assignee?: string | undefined;
  branch?: string | undefined;
  description?: string | undefined;
  executor?: string | undefined;
  model?: string | undefined;
  priority: string;
  slug?: string | undefined;
  start?: boolean | undefined;
  title: string;
  workspace_path: string;
  worktree?: boolean | undefined;
};

/** @internal */
export const PostApiTaskCreateRequestBody$outboundSchema: z.ZodType<
  PostApiTaskCreateRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskCreateRequestBody
> = z.object({
  agent: z.string().optional(),
  assignee: z.string().optional(),
  branch: z.string().optional(),
  description: z.string().optional(),
  executor: z.string().optional(),
  model: z.string().optional(),
  priority: z.string().default("medium"),
  slug: z.string().optional(),
  start: z.boolean().optional(),
  title: z.string(),
  workspacePath: z.string(),
  worktree: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});

export function postApiTaskCreateRequestBodyToJSON(
  postApiTaskCreateRequestBody: PostApiTaskCreateRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskCreateRequestBody$outboundSchema.parse(
      postApiTaskCreateRequestBody,
    ),
  );
}
