/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiPageDuplicateRequestBody = {
  /**
   * Source page uid to duplicate
   */
  uid: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiPageDuplicatePageResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

export const PostApiPageDuplicatePageType = {
  Lucide: "lucide",
  Emoji: "emoji",
  Image: "image",
} as const;
export type PostApiPageDuplicatePageType = ClosedEnum<
  typeof PostApiPageDuplicatePageType
>;

export type PostApiPageDuplicateIcon = {
  type?: PostApiPageDuplicatePageType | undefined;
  value?: string | undefined;
};

export const PostApiPageDuplicatePageWidth = {
  Default: "default",
  Wide: "wide",
  Full: "full",
} as const;
export type PostApiPageDuplicatePageWidth = ClosedEnum<
  typeof PostApiPageDuplicatePageWidth
>;

export const PostApiPageDuplicatePermission = {
  Read: "read",
  Write: "write",
} as const;
export type PostApiPageDuplicatePermission = ClosedEnum<
  typeof PostApiPageDuplicatePermission
>;

/**
 * Page type
 */
export const PostApiPageDuplicateType = {
  Static: "static",
  Markdown: "markdown",
  Server: "server",
  Proxy: "proxy",
} as const;
/**
 * Page type
 */
export type PostApiPageDuplicateType = ClosedEnum<
  typeof PostApiPageDuplicateType
>;

export type PostApiPageDuplicatePage = {
  command?: string | null | undefined;
  cover?: string | null | undefined;
  description?: string | null | undefined;
  file?: string | null | undefined;
  headers?: { [k: string]: string } | null | undefined;
  icon?: PostApiPageDuplicateIcon | null | undefined;
  name?: string | undefined;
  pageWidth?: PostApiPageDuplicatePageWidth | null | undefined;
  path?: string | undefined;
  /**
   * Page permissions
   */
  permission?: Array<PostApiPageDuplicatePermission> | undefined;
  port?: number | null | undefined;
  readyPattern?: string | null | undefined;
  showToc?: boolean | null | undefined;
  skillContent?: string | null | undefined;
  timeout?: number | null | undefined;
  /**
   * Page type
   */
  type?: PostApiPageDuplicateType | undefined;
  uid?: string | undefined;
  updatedAt?: string | null | undefined;
  url?: string | null | undefined;
};

/**
 * Default Response
 */
export type PostApiPageDuplicateResponseBody = {
  error?: string | null | undefined;
  page?: PostApiPageDuplicatePage | undefined;
  success?: boolean | undefined;
};

export type PostApiPageDuplicateResponse =
  | PostApiPageDuplicateResponseBody
  | PostApiPageDuplicatePageResponseBody;

/** @internal */
export type PostApiPageDuplicateRequestBody$Outbound = {
  uid: string;
  workspace_path: string;
};

/** @internal */
export const PostApiPageDuplicateRequestBody$outboundSchema: z.ZodType<
  PostApiPageDuplicateRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiPageDuplicateRequestBody
> = z.object({
  uid: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});

export function postApiPageDuplicateRequestBodyToJSON(
  postApiPageDuplicateRequestBody: PostApiPageDuplicateRequestBody,
): string {
  return JSON.stringify(
    PostApiPageDuplicateRequestBody$outboundSchema.parse(
      postApiPageDuplicateRequestBody,
    ),
  );
}

/** @internal */
export const PostApiPageDuplicatePageResponseBody$inboundSchema: z.ZodType<
  PostApiPageDuplicatePageResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiPageDuplicatePageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageDuplicatePageResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiPageDuplicatePageResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageDuplicatePageResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiPageDuplicatePageType$inboundSchema: z.ZodNativeEnum<
  typeof PostApiPageDuplicatePageType
> = z.nativeEnum(PostApiPageDuplicatePageType);

/** @internal */
export const PostApiPageDuplicateIcon$inboundSchema: z.ZodType<
  PostApiPageDuplicateIcon,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PostApiPageDuplicatePageType$inboundSchema.optional(),
  value: z.string().optional(),
});

export function postApiPageDuplicateIconFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageDuplicateIcon, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageDuplicateIcon$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageDuplicateIcon' from JSON`,
  );
}

/** @internal */
export const PostApiPageDuplicatePageWidth$inboundSchema: z.ZodNativeEnum<
  typeof PostApiPageDuplicatePageWidth
> = z.nativeEnum(PostApiPageDuplicatePageWidth);

/** @internal */
export const PostApiPageDuplicatePermission$inboundSchema: z.ZodNativeEnum<
  typeof PostApiPageDuplicatePermission
> = z.nativeEnum(PostApiPageDuplicatePermission);

/** @internal */
export const PostApiPageDuplicateType$inboundSchema: z.ZodNativeEnum<
  typeof PostApiPageDuplicateType
> = z.nativeEnum(PostApiPageDuplicateType);

/** @internal */
export const PostApiPageDuplicatePage$inboundSchema: z.ZodType<
  PostApiPageDuplicatePage,
  z.ZodTypeDef,
  unknown
> = z.object({
  command: z.nullable(z.string()).optional(),
  cover: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  file: z.nullable(z.string()).optional(),
  headers: z.nullable(z.record(z.string())).optional(),
  icon: z.nullable(z.lazy(() => PostApiPageDuplicateIcon$inboundSchema))
    .optional(),
  name: z.string().optional(),
  page_width: z.nullable(PostApiPageDuplicatePageWidth$inboundSchema)
    .optional(),
  path: z.string().optional(),
  permission: z.array(PostApiPageDuplicatePermission$inboundSchema).optional(),
  port: z.nullable(z.number()).optional(),
  ready_pattern: z.nullable(z.string()).optional(),
  show_toc: z.nullable(z.boolean()).optional(),
  skill_content: z.nullable(z.string()).optional(),
  timeout: z.nullable(z.number()).optional(),
  type: PostApiPageDuplicateType$inboundSchema.optional(),
  uid: z.string().optional(),
  updated_at: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "page_width": "pageWidth",
    "ready_pattern": "readyPattern",
    "show_toc": "showToc",
    "skill_content": "skillContent",
    "updated_at": "updatedAt",
  });
});

export function postApiPageDuplicatePageFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageDuplicatePage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageDuplicatePage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageDuplicatePage' from JSON`,
  );
}

/** @internal */
export const PostApiPageDuplicateResponseBody$inboundSchema: z.ZodType<
  PostApiPageDuplicateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.nullable(z.string()).optional(),
  page: z.lazy(() => PostApiPageDuplicatePage$inboundSchema).optional(),
  success: z.boolean().optional(),
});

export function postApiPageDuplicateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageDuplicateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageDuplicateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageDuplicateResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiPageDuplicateResponse$inboundSchema: z.ZodType<
  PostApiPageDuplicateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiPageDuplicateResponseBody$inboundSchema),
  z.lazy(() => PostApiPageDuplicatePageResponseBody$inboundSchema),
]);

export function postApiPageDuplicateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageDuplicateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageDuplicateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageDuplicateResponse' from JSON`,
  );
}
