/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type PostApiTaskCreateWorktreeRequestBody = {
  /**
   * Skip prd.md validation
   */
  skipPrd?: boolean | undefined;
  /**
   * Task ID or directory (required)
   */
  taskId: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/** @internal */
export type PostApiTaskCreateWorktreeRequestBody$Outbound = {
  skip_prd?: boolean | undefined;
  task_id: string;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskCreateWorktreeRequestBody$outboundSchema: z.ZodType<
  PostApiTaskCreateWorktreeRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskCreateWorktreeRequestBody
> = z.object({
  skipPrd: z.boolean().optional(),
  taskId: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    skipPrd: "skip_prd",
    taskId: "task_id",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskCreateWorktreeRequestBodyToJSON(
  postApiTaskCreateWorktreeRequestBody: PostApiTaskCreateWorktreeRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskCreateWorktreeRequestBody$outboundSchema.parse(
      postApiTaskCreateWorktreeRequestBody,
    ),
  );
}
