/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiPageServeRequestBody = {
  /**
   * File path within the page (optional)
   */
  path?: string | undefined;
  /**
   * Page uid (required)
   */
  uid: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiPageServePageResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

/**
 * Default Response
 */
export type PostApiPageServeResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

export type PostApiPageServeResponse =
  | ReadableStream<Uint8Array>
  | PostApiPageServeResponseBody
  | PostApiPageServePageResponseBody;

/** @internal */
export type PostApiPageServeRequestBody$Outbound = {
  path?: string | undefined;
  uid: string;
  workspace_path: string;
};

/** @internal */
export const PostApiPageServeRequestBody$outboundSchema: z.ZodType<
  PostApiPageServeRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiPageServeRequestBody
> = z.object({
  path: z.string().optional(),
  uid: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});

export function postApiPageServeRequestBodyToJSON(
  postApiPageServeRequestBody: PostApiPageServeRequestBody,
): string {
  return JSON.stringify(
    PostApiPageServeRequestBody$outboundSchema.parse(
      postApiPageServeRequestBody,
    ),
  );
}

/** @internal */
export const PostApiPageServePageResponseBody$inboundSchema: z.ZodType<
  PostApiPageServePageResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiPageServePageResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageServePageResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageServePageResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageServePageResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiPageServeResponseBody$inboundSchema: z.ZodType<
  PostApiPageServeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiPageServeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageServeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageServeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageServeResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiPageServeResponse$inboundSchema: z.ZodType<
  PostApiPageServeResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.instanceof(ReadableStream<Uint8Array>),
  z.lazy(() => PostApiPageServeResponseBody$inboundSchema),
  z.lazy(() => PostApiPageServePageResponseBody$inboundSchema),
]);

export function postApiPageServeResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiPageServeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiPageServeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiPageServeResponse' from JSON`,
  );
}
