/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiTaskPauseRequestBody = {
  /**
   * Task ID or directory (required)
   */
  taskId: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiTaskPauseTasksResponseResponseBody = {
  code?: string | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskPauseTasksResponseBody = {
  code?: string | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskPauseResponseBody = {
  previousStatus?: string | undefined;
  status?: string | undefined;
  success?: boolean | undefined;
  taskId?: string | undefined;
};

export type PostApiTaskPauseResponse =
  | PostApiTaskPauseResponseBody
  | PostApiTaskPauseTasksResponseBody
  | PostApiTaskPauseTasksResponseResponseBody;

/** @internal */
export type PostApiTaskPauseRequestBody$Outbound = {
  task_id: string;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskPauseRequestBody$outboundSchema: z.ZodType<
  PostApiTaskPauseRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskPauseRequestBody
> = z.object({
  taskId: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskPauseRequestBodyToJSON(
  postApiTaskPauseRequestBody: PostApiTaskPauseRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskPauseRequestBody$outboundSchema.parse(
      postApiTaskPauseRequestBody,
    ),
  );
}

/** @internal */
export const PostApiTaskPauseTasksResponseResponseBody$inboundSchema: z.ZodType<
  PostApiTaskPauseTasksResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  error: z.string().optional(),
});

export function postApiTaskPauseTasksResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiTaskPauseTasksResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskPauseTasksResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiTaskPauseTasksResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskPauseTasksResponseBody$inboundSchema: z.ZodType<
  PostApiTaskPauseTasksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  error: z.string().optional(),
});

export function postApiTaskPauseTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskPauseTasksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskPauseTasksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskPauseTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskPauseResponseBody$inboundSchema: z.ZodType<
  PostApiTaskPauseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  previous_status: z.string().optional(),
  status: z.string().optional(),
  success: z.boolean().optional(),
  task_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "previous_status": "previousStatus",
    "task_id": "taskId",
  });
});

export function postApiTaskPauseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskPauseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskPauseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskPauseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskPauseResponse$inboundSchema: z.ZodType<
  PostApiTaskPauseResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiTaskPauseResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskPauseTasksResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskPauseTasksResponseResponseBody$inboundSchema),
]);

export function postApiTaskPauseResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskPauseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskPauseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskPauseResponse' from JSON`,
  );
}
