/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiIdeasGenerateRequestBody = {
  /**
   * Append to existing ideas
   */
  append?: boolean | undefined;
  /**
   * Maximum ideas per type
   */
  maxIdeas?: number | undefined;
  /**
   * AI model to use
   */
  model?: string | undefined;
  /**
   * Output directory
   */
  output?: string | undefined;
  /**
   * Force regenerate all types
   */
  override?: boolean | undefined;
  /**
   * Idea types to generate
   */
  types: Array<string>;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiIdeasGenerateIdeasResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

export type ByType = {};

export type PostApiIdeasGenerateIdeas = {};

/**
 * Default Response
 */
export type PostApiIdeasGenerateResponseBody = {
  byType?: ByType | undefined;
  errors?: Array<string> | undefined;
  ideas?: Array<PostApiIdeasGenerateIdeas> | undefined;
  sessionDir?: string | undefined;
  sessionId?: string | undefined;
  success?: boolean | undefined;
  totalIdeas?: number | undefined;
};

export type PostApiIdeasGenerateResponse =
  | PostApiIdeasGenerateResponseBody
  | PostApiIdeasGenerateIdeasResponseBody;

/** @internal */
export type PostApiIdeasGenerateRequestBody$Outbound = {
  append?: boolean | undefined;
  max_ideas?: number | undefined;
  model?: string | undefined;
  output?: string | undefined;
  override?: boolean | undefined;
  types: Array<string>;
  workspace_path: string;
};

/** @internal */
export const PostApiIdeasGenerateRequestBody$outboundSchema: z.ZodType<
  PostApiIdeasGenerateRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiIdeasGenerateRequestBody
> = z.object({
  append: z.boolean().optional(),
  maxIdeas: z.number().optional(),
  model: z.string().optional(),
  output: z.string().optional(),
  override: z.boolean().optional(),
  types: z.array(z.string()),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    maxIdeas: "max_ideas",
    workspacePath: "workspace_path",
  });
});

export function postApiIdeasGenerateRequestBodyToJSON(
  postApiIdeasGenerateRequestBody: PostApiIdeasGenerateRequestBody,
): string {
  return JSON.stringify(
    PostApiIdeasGenerateRequestBody$outboundSchema.parse(
      postApiIdeasGenerateRequestBody,
    ),
  );
}

/** @internal */
export const PostApiIdeasGenerateIdeasResponseBody$inboundSchema: z.ZodType<
  PostApiIdeasGenerateIdeasResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiIdeasGenerateIdeasResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiIdeasGenerateIdeasResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiIdeasGenerateIdeasResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiIdeasGenerateIdeasResponseBody' from JSON`,
  );
}

/** @internal */
export const ByType$inboundSchema: z.ZodType<ByType, z.ZodTypeDef, unknown> = z
  .object({});

export function byTypeFromJSON(
  jsonString: string,
): SafeParseResult<ByType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ByType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ByType' from JSON`,
  );
}

/** @internal */
export const PostApiIdeasGenerateIdeas$inboundSchema: z.ZodType<
  PostApiIdeasGenerateIdeas,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function postApiIdeasGenerateIdeasFromJSON(
  jsonString: string,
): SafeParseResult<PostApiIdeasGenerateIdeas, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiIdeasGenerateIdeas$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiIdeasGenerateIdeas' from JSON`,
  );
}

/** @internal */
export const PostApiIdeasGenerateResponseBody$inboundSchema: z.ZodType<
  PostApiIdeasGenerateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  by_type: z.lazy(() => ByType$inboundSchema).optional(),
  errors: z.array(z.string()).optional(),
  ideas: z.array(z.lazy(() => PostApiIdeasGenerateIdeas$inboundSchema))
    .optional(),
  session_dir: z.string().optional(),
  session_id: z.string().optional(),
  success: z.boolean().optional(),
  total_ideas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "by_type": "byType",
    "session_dir": "sessionDir",
    "session_id": "sessionId",
    "total_ideas": "totalIdeas",
  });
});

export function postApiIdeasGenerateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiIdeasGenerateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiIdeasGenerateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiIdeasGenerateResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiIdeasGenerateResponse$inboundSchema: z.ZodType<
  PostApiIdeasGenerateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiIdeasGenerateResponseBody$inboundSchema),
  z.lazy(() => PostApiIdeasGenerateIdeasResponseBody$inboundSchema),
]);

export function postApiIdeasGenerateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiIdeasGenerateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiIdeasGenerateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiIdeasGenerateResponse' from JSON`,
  );
}
