/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type PostApiTaskValidateCheckPhasePassedRequestBody = {
  /**
   * Agent output text (for completion markers validation)
   */
  output?: string | undefined;
  /**
   * File containing agent output
   */
  outputFile?: string | undefined;
  /**
   * Task ID or directory (required)
   */
  taskId: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/** @internal */
export type PostApiTaskValidateCheckPhasePassedRequestBody$Outbound = {
  output?: string | undefined;
  output_file?: string | undefined;
  task_id: string;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskValidateCheckPhasePassedRequestBody$outboundSchema:
  z.ZodType<
    PostApiTaskValidateCheckPhasePassedRequestBody$Outbound,
    z.ZodTypeDef,
    PostApiTaskValidateCheckPhasePassedRequestBody
  > = z.object({
    output: z.string().optional(),
    outputFile: z.string().optional(),
    taskId: z.string(),
    workspacePath: z.string(),
  }).transform((v) => {
    return remap$(v, {
      outputFile: "output_file",
      taskId: "task_id",
      workspacePath: "workspace_path",
    });
  });

export function postApiTaskValidateCheckPhasePassedRequestBodyToJSON(
  postApiTaskValidateCheckPhasePassedRequestBody:
    PostApiTaskValidateCheckPhasePassedRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskValidateCheckPhasePassedRequestBody$outboundSchema.parse(
      postApiTaskValidateCheckPhasePassedRequestBody,
    ),
  );
}
