/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiTaskEventsRequestBody = {
  /**
   * Get events after this sequence number
   */
  since?: number | undefined;
  /**
   * Task directory path or ID (required)
   */
  taskDir: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiTaskEventsTasksResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskEventsResponseBody = {
  count?: number | undefined;
  events?: Array<any> | undefined;
  nextSequence?: number | undefined;
  taskId?: string | undefined;
};

export type PostApiTaskEventsResponse =
  | PostApiTaskEventsResponseBody
  | PostApiTaskEventsTasksResponseBody;

/** @internal */
export type PostApiTaskEventsRequestBody$Outbound = {
  since?: number | undefined;
  task_dir: string;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskEventsRequestBody$outboundSchema: z.ZodType<
  PostApiTaskEventsRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskEventsRequestBody
> = z.object({
  since: z.number().optional(),
  taskDir: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskDir: "task_dir",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskEventsRequestBodyToJSON(
  postApiTaskEventsRequestBody: PostApiTaskEventsRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskEventsRequestBody$outboundSchema.parse(
      postApiTaskEventsRequestBody,
    ),
  );
}

/** @internal */
export const PostApiTaskEventsTasksResponseBody$inboundSchema: z.ZodType<
  PostApiTaskEventsTasksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});

export function postApiTaskEventsTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskEventsTasksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskEventsTasksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskEventsTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskEventsResponseBody$inboundSchema: z.ZodType<
  PostApiTaskEventsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().optional(),
  events: z.array(z.any()).optional(),
  next_sequence: z.number().optional(),
  task_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "next_sequence": "nextSequence",
    "task_id": "taskId",
  });
});

export function postApiTaskEventsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskEventsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskEventsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskEventsResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskEventsResponse$inboundSchema: z.ZodType<
  PostApiTaskEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiTaskEventsResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskEventsTasksResponseBody$inboundSchema),
]);

export function postApiTaskEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskEventsResponse' from JSON`,
  );
}
