/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiCommandQueueItemsIdRetryRequest = {
  id: string;
};

/** @internal */
export type PostApiCommandQueueItemsIdRetryRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostApiCommandQueueItemsIdRetryRequest$outboundSchema: z.ZodType<
  PostApiCommandQueueItemsIdRetryRequest$Outbound,
  z.ZodTypeDef,
  PostApiCommandQueueItemsIdRetryRequest
> = z.object({
  id: z.string(),
});

export function postApiCommandQueueItemsIdRetryRequestToJSON(
  postApiCommandQueueItemsIdRetryRequest:
    PostApiCommandQueueItemsIdRetryRequest,
): string {
  return JSON.stringify(
    PostApiCommandQueueItemsIdRetryRequest$outboundSchema.parse(
      postApiCommandQueueItemsIdRetryRequest,
    ),
  );
}
