/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type PostApiTaskCreatePrRequestBody = {
  /**
   * Show what would be done without making changes
   */
  dryRun?: boolean | undefined;
};

export type PostApiTaskCreatePrRequest = {
  requestBody: PostApiTaskCreatePrRequestBody;
  /**
   * Task directory path
   */
  taskDir?: string | undefined;
  /**
   * Workspace path
   */
  workspacePath?: string | undefined;
};

/** @internal */
export type PostApiTaskCreatePrRequestBody$Outbound = {
  dry_run?: boolean | undefined;
};

/** @internal */
export const PostApiTaskCreatePrRequestBody$outboundSchema: z.ZodType<
  PostApiTaskCreatePrRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskCreatePrRequestBody
> = z.object({
  dryRun: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    dryRun: "dry_run",
  });
});

export function postApiTaskCreatePrRequestBodyToJSON(
  postApiTaskCreatePrRequestBody: PostApiTaskCreatePrRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskCreatePrRequestBody$outboundSchema.parse(
      postApiTaskCreatePrRequestBody,
    ),
  );
}

/** @internal */
export type PostApiTaskCreatePrRequest$Outbound = {
  RequestBody: PostApiTaskCreatePrRequestBody$Outbound;
  task_dir?: string | undefined;
  workspace_path?: string | undefined;
};

/** @internal */
export const PostApiTaskCreatePrRequest$outboundSchema: z.ZodType<
  PostApiTaskCreatePrRequest$Outbound,
  z.ZodTypeDef,
  PostApiTaskCreatePrRequest
> = z.object({
  requestBody: z.lazy(() => PostApiTaskCreatePrRequestBody$outboundSchema),
  taskDir: z.string().optional(),
  workspacePath: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
    taskDir: "task_dir",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskCreatePrRequestToJSON(
  postApiTaskCreatePrRequest: PostApiTaskCreatePrRequest,
): string {
  return JSON.stringify(
    PostApiTaskCreatePrRequest$outboundSchema.parse(postApiTaskCreatePrRequest),
  );
}
