/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiRewardSelectRequestBody = {
  /**
   * KL penalty coefficient (default: 0.05)
   */
  klCoef?: number | undefined;
  /**
   * Maximum diff lines for KL normalization (default: 500)
   */
  maxDiff?: number | undefined;
  /**
   * Task names to compare (must have computed rewards)
   */
  tasks: Array<string>;
  /**
   * Minimum adjusted reward threshold (default: 0.6)
   */
  threshold?: number | undefined;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiRewardSelectRewardResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

export type Candidates = {
  adjustedReward?: number | undefined;
  advantage?: number | undefined;
  diffLines?: number | undefined;
  klPenalty?: number | undefined;
  ppoScore?: number | undefined;
  reward?: number | undefined;
  task?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiRewardSelectResponseBody = {
  baseline?: number | undefined;
  candidates?: Array<Candidates> | undefined;
  rejected?: Array<string> | undefined;
  selected?: string | null | undefined;
  success?: boolean | undefined;
  threshold?: number | undefined;
};

export type PostApiRewardSelectResponse =
  | PostApiRewardSelectResponseBody
  | PostApiRewardSelectRewardResponseBody;

/** @internal */
export type PostApiRewardSelectRequestBody$Outbound = {
  kl_coef?: number | undefined;
  max_diff?: number | undefined;
  tasks: Array<string>;
  threshold?: number | undefined;
  workspace_path: string;
};

/** @internal */
export const PostApiRewardSelectRequestBody$outboundSchema: z.ZodType<
  PostApiRewardSelectRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiRewardSelectRequestBody
> = z.object({
  klCoef: z.number().optional(),
  maxDiff: z.number().optional(),
  tasks: z.array(z.string()),
  threshold: z.number().optional(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    klCoef: "kl_coef",
    maxDiff: "max_diff",
    workspacePath: "workspace_path",
  });
});

export function postApiRewardSelectRequestBodyToJSON(
  postApiRewardSelectRequestBody: PostApiRewardSelectRequestBody,
): string {
  return JSON.stringify(
    PostApiRewardSelectRequestBody$outboundSchema.parse(
      postApiRewardSelectRequestBody,
    ),
  );
}

/** @internal */
export const PostApiRewardSelectRewardResponseBody$inboundSchema: z.ZodType<
  PostApiRewardSelectRewardResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiRewardSelectRewardResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRewardSelectRewardResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiRewardSelectRewardResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRewardSelectRewardResponseBody' from JSON`,
  );
}

/** @internal */
export const Candidates$inboundSchema: z.ZodType<
  Candidates,
  z.ZodTypeDef,
  unknown
> = z.object({
  adjusted_reward: z.number().optional(),
  advantage: z.number().optional(),
  diff_lines: z.number().optional(),
  kl_penalty: z.number().optional(),
  ppo_score: z.number().optional(),
  reward: z.number().optional(),
  task: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "adjusted_reward": "adjustedReward",
    "diff_lines": "diffLines",
    "kl_penalty": "klPenalty",
    "ppo_score": "ppoScore",
  });
});

export function candidatesFromJSON(
  jsonString: string,
): SafeParseResult<Candidates, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Candidates$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Candidates' from JSON`,
  );
}

/** @internal */
export const PostApiRewardSelectResponseBody$inboundSchema: z.ZodType<
  PostApiRewardSelectResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  baseline: z.number().optional(),
  candidates: z.array(z.lazy(() => Candidates$inboundSchema)).optional(),
  rejected: z.array(z.string()).optional(),
  selected: z.nullable(z.string()).optional(),
  success: z.boolean().optional(),
  threshold: z.number().optional(),
});

export function postApiRewardSelectResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRewardSelectResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiRewardSelectResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRewardSelectResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiRewardSelectResponse$inboundSchema: z.ZodType<
  PostApiRewardSelectResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiRewardSelectResponseBody$inboundSchema),
  z.lazy(() => PostApiRewardSelectRewardResponseBody$inboundSchema),
]);

export function postApiRewardSelectResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRewardSelectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiRewardSelectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRewardSelectResponse' from JSON`,
  );
}
