/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiAccountsIdTestRequest = {
  id: string;
};

/** @internal */
export type PostApiAccountsIdTestRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostApiAccountsIdTestRequest$outboundSchema: z.ZodType<
  PostApiAccountsIdTestRequest$Outbound,
  z.ZodTypeDef,
  PostApiAccountsIdTestRequest
> = z.object({
  id: z.string(),
});

export function postApiAccountsIdTestRequestToJSON(
  postApiAccountsIdTestRequest: PostApiAccountsIdTestRequest,
): string {
  return JSON.stringify(
    PostApiAccountsIdTestRequest$outboundSchema.parse(
      postApiAccountsIdTestRequest,
    ),
  );
}
