/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiTaskSetBaseRequestBody = {
  /**
   * Base branch name (PR target)
   */
  baseBranch: string;
  /**
   * Task ID or directory
   */
  taskId: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiTaskSetBaseTasksResponseResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskSetBaseTasksResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskSetBaseResponseBody = {
  baseBranch?: string | undefined;
  success?: boolean | undefined;
  taskId?: string | undefined;
};

export type PostApiTaskSetBaseResponse =
  | PostApiTaskSetBaseResponseBody
  | PostApiTaskSetBaseTasksResponseBody
  | PostApiTaskSetBaseTasksResponseResponseBody;

/** @internal */
export type PostApiTaskSetBaseRequestBody$Outbound = {
  base_branch: string;
  task_id: string;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskSetBaseRequestBody$outboundSchema: z.ZodType<
  PostApiTaskSetBaseRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskSetBaseRequestBody
> = z.object({
  baseBranch: z.string(),
  taskId: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    baseBranch: "base_branch",
    taskId: "task_id",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskSetBaseRequestBodyToJSON(
  postApiTaskSetBaseRequestBody: PostApiTaskSetBaseRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskSetBaseRequestBody$outboundSchema.parse(
      postApiTaskSetBaseRequestBody,
    ),
  );
}

/** @internal */
export const PostApiTaskSetBaseTasksResponseResponseBody$inboundSchema:
  z.ZodType<
    PostApiTaskSetBaseTasksResponseResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
  });

export function postApiTaskSetBaseTasksResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiTaskSetBaseTasksResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskSetBaseTasksResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiTaskSetBaseTasksResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskSetBaseTasksResponseBody$inboundSchema: z.ZodType<
  PostApiTaskSetBaseTasksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});

export function postApiTaskSetBaseTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskSetBaseTasksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskSetBaseTasksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskSetBaseTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskSetBaseResponseBody$inboundSchema: z.ZodType<
  PostApiTaskSetBaseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  base_branch: z.string().optional(),
  success: z.boolean().optional(),
  task_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "base_branch": "baseBranch",
    "task_id": "taskId",
  });
});

export function postApiTaskSetBaseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskSetBaseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskSetBaseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskSetBaseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskSetBaseResponse$inboundSchema: z.ZodType<
  PostApiTaskSetBaseResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiTaskSetBaseResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskSetBaseTasksResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskSetBaseTasksResponseResponseBody$inboundSchema),
]);

export function postApiTaskSetBaseResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskSetBaseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskSetBaseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskSetBaseResponse' from JSON`,
  );
}
