/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Attachments = {
  data?: string | undefined;
  name?: string | undefined;
  type?: string | undefined;
};

export type PostApiTaskExecuteRequestBody = {
  /**
   * Path to agent config
   */
  agentConfigPath?: string | undefined;
  /**
   * Agent ID to use
   */
  agentId?: string | undefined;
  attachments?: Array<Attachments> | undefined;
  /**
   * Working directory
   */
  cwd?: string | undefined;
  /**
   * User prompt
   */
  input?: string | undefined;
  /**
   * Maximum retry attempts
   */
  maxRetries?: number | undefined;
  /**
   * Resume from existing session
   */
  resumeSession?: string | undefined;
  /**
   * Task directory path or ID (required)
   */
  taskDir: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiTaskExecuteTasksResponseResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskExecuteTasksResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskExecuteResponseBody = {
  position?: number | undefined;
  status?: string | undefined;
  success?: boolean | undefined;
  /**
   * Queue task ID
   */
  taskId?: string | undefined;
};

export type PostApiTaskExecuteResponse =
  | PostApiTaskExecuteResponseBody
  | PostApiTaskExecuteTasksResponseBody
  | PostApiTaskExecuteTasksResponseResponseBody;

/** @internal */
export type Attachments$Outbound = {
  data?: string | undefined;
  name?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const Attachments$outboundSchema: z.ZodType<
  Attachments$Outbound,
  z.ZodTypeDef,
  Attachments
> = z.object({
  data: z.string().optional(),
  name: z.string().optional(),
  type: z.string().optional(),
});

export function attachmentsToJSON(attachments: Attachments): string {
  return JSON.stringify(Attachments$outboundSchema.parse(attachments));
}

/** @internal */
export type PostApiTaskExecuteRequestBody$Outbound = {
  agent_config_path?: string | undefined;
  agent_id?: string | undefined;
  attachments?: Array<Attachments$Outbound> | undefined;
  cwd?: string | undefined;
  input?: string | undefined;
  max_retries?: number | undefined;
  resume_session?: string | undefined;
  task_dir: string;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskExecuteRequestBody$outboundSchema: z.ZodType<
  PostApiTaskExecuteRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskExecuteRequestBody
> = z.object({
  agentConfigPath: z.string().optional(),
  agentId: z.string().optional(),
  attachments: z.array(z.lazy(() => Attachments$outboundSchema)).optional(),
  cwd: z.string().optional(),
  input: z.string().optional(),
  maxRetries: z.number().optional(),
  resumeSession: z.string().optional(),
  taskDir: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    agentConfigPath: "agent_config_path",
    agentId: "agent_id",
    maxRetries: "max_retries",
    resumeSession: "resume_session",
    taskDir: "task_dir",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskExecuteRequestBodyToJSON(
  postApiTaskExecuteRequestBody: PostApiTaskExecuteRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskExecuteRequestBody$outboundSchema.parse(
      postApiTaskExecuteRequestBody,
    ),
  );
}

/** @internal */
export const PostApiTaskExecuteTasksResponseResponseBody$inboundSchema:
  z.ZodType<
    PostApiTaskExecuteTasksResponseResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
  });

export function postApiTaskExecuteTasksResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiTaskExecuteTasksResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskExecuteTasksResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiTaskExecuteTasksResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskExecuteTasksResponseBody$inboundSchema: z.ZodType<
  PostApiTaskExecuteTasksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});

export function postApiTaskExecuteTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskExecuteTasksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskExecuteTasksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskExecuteTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskExecuteResponseBody$inboundSchema: z.ZodType<
  PostApiTaskExecuteResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  position: z.number().optional(),
  status: z.string().optional(),
  success: z.boolean().optional(),
  task_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "task_id": "taskId",
  });
});

export function postApiTaskExecuteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskExecuteResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskExecuteResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskExecuteResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskExecuteResponse$inboundSchema: z.ZodType<
  PostApiTaskExecuteResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiTaskExecuteResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskExecuteTasksResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskExecuteTasksResponseResponseBody$inboundSchema),
]);

export function postApiTaskExecuteResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskExecuteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskExecuteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskExecuteResponse' from JSON`,
  );
}
