/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiIdeasIdPromoteRequestBody = {
  /**
   * Agent configuration
   */
  agent?: string | undefined;
  /**
   * Task assignee
   */
  assignee?: string | undefined;
  /**
   * Custom branch name
   */
  branch?: string | undefined;
  /**
   * Task description override
   */
  description?: string | undefined;
  /**
   * Executor type
   */
  executor?: string | undefined;
  /**
   * Model to use
   */
  model?: string | undefined;
  /**
   * Task priority
   */
  priority?: string | undefined;
  /**
   * Task slug
   */
  slug?: string | undefined;
  /**
   * Auto-start task
   */
  start?: boolean | undefined;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Run in worktree
   */
  worktree?: boolean | undefined;
};

export type PostApiIdeasIdPromoteRequest = {
  requestBody: PostApiIdeasIdPromoteRequestBody;
  /**
   * Idea ID
   */
  id: string;
};

/**
 * Default Response
 */
export type PostApiIdeasIdPromoteIdeasResponseResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

/**
 * Default Response
 */
export type PostApiIdeasIdPromoteIdeasResponseBody = {
  error?: string | undefined;
  success?: boolean | undefined;
};

/**
 * Default Response
 */
export type PostApiIdeasIdPromoteResponseBody = {
  ideaId?: string | undefined;
  ideaTitle?: string | undefined;
  priority?: string | undefined;
  status?: string | undefined;
  success?: boolean | undefined;
  taskDir?: string | undefined;
  taskId?: string | undefined;
  worktree?: boolean | undefined;
};

export type PostApiIdeasIdPromoteResponse =
  | PostApiIdeasIdPromoteResponseBody
  | PostApiIdeasIdPromoteIdeasResponseBody
  | PostApiIdeasIdPromoteIdeasResponseResponseBody;

/** @internal */
export type PostApiIdeasIdPromoteRequestBody$Outbound = {
  agent?: string | undefined;
  assignee?: string | undefined;
  branch?: string | undefined;
  description?: string | undefined;
  executor?: string | undefined;
  model?: string | undefined;
  priority?: string | undefined;
  slug?: string | undefined;
  start?: boolean | undefined;
  workspace_path: string;
  worktree?: boolean | undefined;
};

/** @internal */
export const PostApiIdeasIdPromoteRequestBody$outboundSchema: z.ZodType<
  PostApiIdeasIdPromoteRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiIdeasIdPromoteRequestBody
> = z.object({
  agent: z.string().optional(),
  assignee: z.string().optional(),
  branch: z.string().optional(),
  description: z.string().optional(),
  executor: z.string().optional(),
  model: z.string().optional(),
  priority: z.string().optional(),
  slug: z.string().optional(),
  start: z.boolean().optional(),
  workspacePath: z.string(),
  worktree: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});

export function postApiIdeasIdPromoteRequestBodyToJSON(
  postApiIdeasIdPromoteRequestBody: PostApiIdeasIdPromoteRequestBody,
): string {
  return JSON.stringify(
    PostApiIdeasIdPromoteRequestBody$outboundSchema.parse(
      postApiIdeasIdPromoteRequestBody,
    ),
  );
}

/** @internal */
export type PostApiIdeasIdPromoteRequest$Outbound = {
  RequestBody: PostApiIdeasIdPromoteRequestBody$Outbound;
  id: string;
};

/** @internal */
export const PostApiIdeasIdPromoteRequest$outboundSchema: z.ZodType<
  PostApiIdeasIdPromoteRequest$Outbound,
  z.ZodTypeDef,
  PostApiIdeasIdPromoteRequest
> = z.object({
  requestBody: z.lazy(() => PostApiIdeasIdPromoteRequestBody$outboundSchema),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function postApiIdeasIdPromoteRequestToJSON(
  postApiIdeasIdPromoteRequest: PostApiIdeasIdPromoteRequest,
): string {
  return JSON.stringify(
    PostApiIdeasIdPromoteRequest$outboundSchema.parse(
      postApiIdeasIdPromoteRequest,
    ),
  );
}

/** @internal */
export const PostApiIdeasIdPromoteIdeasResponseResponseBody$inboundSchema:
  z.ZodType<
    PostApiIdeasIdPromoteIdeasResponseResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    success: z.boolean().optional(),
  });

export function postApiIdeasIdPromoteIdeasResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiIdeasIdPromoteIdeasResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiIdeasIdPromoteIdeasResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiIdeasIdPromoteIdeasResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiIdeasIdPromoteIdeasResponseBody$inboundSchema: z.ZodType<
  PostApiIdeasIdPromoteIdeasResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  success: z.boolean().optional(),
});

export function postApiIdeasIdPromoteIdeasResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiIdeasIdPromoteIdeasResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiIdeasIdPromoteIdeasResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiIdeasIdPromoteIdeasResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiIdeasIdPromoteResponseBody$inboundSchema: z.ZodType<
  PostApiIdeasIdPromoteResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  idea_id: z.string().optional(),
  idea_title: z.string().optional(),
  priority: z.string().optional(),
  status: z.string().optional(),
  success: z.boolean().optional(),
  task_dir: z.string().optional(),
  task_id: z.string().optional(),
  worktree: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "idea_id": "ideaId",
    "idea_title": "ideaTitle",
    "task_dir": "taskDir",
    "task_id": "taskId",
  });
});

export function postApiIdeasIdPromoteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiIdeasIdPromoteResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiIdeasIdPromoteResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiIdeasIdPromoteResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiIdeasIdPromoteResponse$inboundSchema: z.ZodType<
  PostApiIdeasIdPromoteResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiIdeasIdPromoteResponseBody$inboundSchema),
  z.lazy(() => PostApiIdeasIdPromoteIdeasResponseBody$inboundSchema),
  z.lazy(() => PostApiIdeasIdPromoteIdeasResponseResponseBody$inboundSchema),
]);

export function postApiIdeasIdPromoteResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiIdeasIdPromoteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiIdeasIdPromoteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiIdeasIdPromoteResponse' from JSON`,
  );
}
