/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiGroupChatsIdPicturesRequest = {
  id: string;
};

/** @internal */
export type PostApiGroupChatsIdPicturesRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostApiGroupChatsIdPicturesRequest$outboundSchema: z.ZodType<
  PostApiGroupChatsIdPicturesRequest$Outbound,
  z.ZodTypeDef,
  PostApiGroupChatsIdPicturesRequest
> = z.object({
  id: z.string(),
});

export function postApiGroupChatsIdPicturesRequestToJSON(
  postApiGroupChatsIdPicturesRequest: PostApiGroupChatsIdPicturesRequest,
): string {
  return JSON.stringify(
    PostApiGroupChatsIdPicturesRequest$outboundSchema.parse(
      postApiGroupChatsIdPicturesRequest,
    ),
  );
}
