/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type PostApiTaskStatusRequestBody = {
  /**
   * Filter by assignee
   */
  assignee?: string | undefined;
  /**
   * Show detailed status
   */
  detail?: boolean | undefined;
  /**
   * List worktrees and agents
   */
  list?: boolean | undefined;
  /**
   * Show agent registry
   */
  registry?: boolean | undefined;
  /**
   * Show only running tasks
   */
  running?: boolean | undefined;
  /**
   * Filter by status
   */
  status?: string | undefined;
};

export type PostApiTaskStatusRequest = {
  requestBody: PostApiTaskStatusRequestBody;
  /**
   * Specific task directory
   */
  taskDir?: string | undefined;
  /**
   * Workspace path
   */
  workspacePath?: string | undefined;
};

/** @internal */
export type PostApiTaskStatusRequestBody$Outbound = {
  assignee?: string | undefined;
  detail?: boolean | undefined;
  list?: boolean | undefined;
  registry?: boolean | undefined;
  running?: boolean | undefined;
  status?: string | undefined;
};

/** @internal */
export const PostApiTaskStatusRequestBody$outboundSchema: z.ZodType<
  PostApiTaskStatusRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskStatusRequestBody
> = z.object({
  assignee: z.string().optional(),
  detail: z.boolean().optional(),
  list: z.boolean().optional(),
  registry: z.boolean().optional(),
  running: z.boolean().optional(),
  status: z.string().optional(),
});

export function postApiTaskStatusRequestBodyToJSON(
  postApiTaskStatusRequestBody: PostApiTaskStatusRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskStatusRequestBody$outboundSchema.parse(
      postApiTaskStatusRequestBody,
    ),
  );
}

/** @internal */
export type PostApiTaskStatusRequest$Outbound = {
  RequestBody: PostApiTaskStatusRequestBody$Outbound;
  task_dir?: string | undefined;
  workspace_path?: string | undefined;
};

/** @internal */
export const PostApiTaskStatusRequest$outboundSchema: z.ZodType<
  PostApiTaskStatusRequest$Outbound,
  z.ZodTypeDef,
  PostApiTaskStatusRequest
> = z.object({
  requestBody: z.lazy(() => PostApiTaskStatusRequestBody$outboundSchema),
  taskDir: z.string().optional(),
  workspacePath: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
    taskDir: "task_dir",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskStatusRequestToJSON(
  postApiTaskStatusRequest: PostApiTaskStatusRequest,
): string {
  return JSON.stringify(
    PostApiTaskStatusRequest$outboundSchema.parse(postApiTaskStatusRequest),
  );
}
