/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiTaskRetryRequestBody = {
  /**
   * Task ID or directory (required)
   */
  taskId: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiTaskRetryTasksResponseResponseBody = {
  code?: string | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskRetryTasksResponseBody = {
  code?: string | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskRetryResponseBody = {
  previousStatus?: string | undefined;
  status?: string | undefined;
  success?: boolean | undefined;
  taskId?: string | undefined;
};

export type PostApiTaskRetryResponse =
  | PostApiTaskRetryResponseBody
  | PostApiTaskRetryTasksResponseBody
  | PostApiTaskRetryTasksResponseResponseBody;

/** @internal */
export type PostApiTaskRetryRequestBody$Outbound = {
  task_id: string;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskRetryRequestBody$outboundSchema: z.ZodType<
  PostApiTaskRetryRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskRetryRequestBody
> = z.object({
  taskId: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskRetryRequestBodyToJSON(
  postApiTaskRetryRequestBody: PostApiTaskRetryRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskRetryRequestBody$outboundSchema.parse(
      postApiTaskRetryRequestBody,
    ),
  );
}

/** @internal */
export const PostApiTaskRetryTasksResponseResponseBody$inboundSchema: z.ZodType<
  PostApiTaskRetryTasksResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  error: z.string().optional(),
});

export function postApiTaskRetryTasksResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PostApiTaskRetryTasksResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskRetryTasksResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostApiTaskRetryTasksResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskRetryTasksResponseBody$inboundSchema: z.ZodType<
  PostApiTaskRetryTasksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string().optional(),
  error: z.string().optional(),
});

export function postApiTaskRetryTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskRetryTasksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskRetryTasksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskRetryTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskRetryResponseBody$inboundSchema: z.ZodType<
  PostApiTaskRetryResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  previous_status: z.string().optional(),
  status: z.string().optional(),
  success: z.boolean().optional(),
  task_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "previous_status": "previousStatus",
    "task_id": "taskId",
  });
});

export function postApiTaskRetryResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskRetryResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskRetryResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskRetryResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskRetryResponse$inboundSchema: z.ZodType<
  PostApiTaskRetryResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiTaskRetryResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskRetryTasksResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskRetryTasksResponseResponseBody$inboundSchema),
]);

export function postApiTaskRetryResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskRetryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskRetryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskRetryResponse' from JSON`,
  );
}
