/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiTaskRunningRequestBody = {
  /**
   * Task directory path or ID (required)
   */
  taskDir: string;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type PostApiTaskRunningTasksResponseBody = {
  error?: string | undefined;
};

export type PostApiTaskRunningData = {
  queueStatus?: string | undefined;
  queueTaskId?: string | undefined;
  running?: boolean | undefined;
  status?: string | undefined;
  taskId?: string | undefined;
};

/**
 * Default Response
 */
export type PostApiTaskRunningResponseBody = {
  data?: PostApiTaskRunningData | undefined;
  success?: boolean | undefined;
};

export type PostApiTaskRunningResponse =
  | PostApiTaskRunningResponseBody
  | PostApiTaskRunningTasksResponseBody;

/** @internal */
export type PostApiTaskRunningRequestBody$Outbound = {
  task_dir: string;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskRunningRequestBody$outboundSchema: z.ZodType<
  PostApiTaskRunningRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskRunningRequestBody
> = z.object({
  taskDir: z.string(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskDir: "task_dir",
    workspacePath: "workspace_path",
  });
});

export function postApiTaskRunningRequestBodyToJSON(
  postApiTaskRunningRequestBody: PostApiTaskRunningRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskRunningRequestBody$outboundSchema.parse(
      postApiTaskRunningRequestBody,
    ),
  );
}

/** @internal */
export const PostApiTaskRunningTasksResponseBody$inboundSchema: z.ZodType<
  PostApiTaskRunningTasksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});

export function postApiTaskRunningTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskRunningTasksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiTaskRunningTasksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskRunningTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskRunningData$inboundSchema: z.ZodType<
  PostApiTaskRunningData,
  z.ZodTypeDef,
  unknown
> = z.object({
  queue_status: z.string().optional(),
  queue_task_id: z.string().optional(),
  running: z.boolean().optional(),
  status: z.string().optional(),
  task_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "queue_status": "queueStatus",
    "queue_task_id": "queueTaskId",
    "task_id": "taskId",
  });
});

export function postApiTaskRunningDataFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskRunningData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskRunningData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskRunningData' from JSON`,
  );
}

/** @internal */
export const PostApiTaskRunningResponseBody$inboundSchema: z.ZodType<
  PostApiTaskRunningResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PostApiTaskRunningData$inboundSchema).optional(),
  success: z.boolean().optional(),
});

export function postApiTaskRunningResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskRunningResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskRunningResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskRunningResponseBody' from JSON`,
  );
}

/** @internal */
export const PostApiTaskRunningResponse$inboundSchema: z.ZodType<
  PostApiTaskRunningResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostApiTaskRunningResponseBody$inboundSchema),
  z.lazy(() => PostApiTaskRunningTasksResponseBody$inboundSchema),
]);

export function postApiTaskRunningResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiTaskRunningResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiTaskRunningResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiTaskRunningResponse' from JSON`,
  );
}
