/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiGroupChatsIdFilesRequest = {
  id: string;
};

/** @internal */
export type PostApiGroupChatsIdFilesRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostApiGroupChatsIdFilesRequest$outboundSchema: z.ZodType<
  PostApiGroupChatsIdFilesRequest$Outbound,
  z.ZodTypeDef,
  PostApiGroupChatsIdFilesRequest
> = z.object({
  id: z.string(),
});

export function postApiGroupChatsIdFilesRequestToJSON(
  postApiGroupChatsIdFilesRequest: PostApiGroupChatsIdFilesRequest,
): string {
  return JSON.stringify(
    PostApiGroupChatsIdFilesRequest$outboundSchema.parse(
      postApiGroupChatsIdFilesRequest,
    ),
  );
}
