/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type PostApiTaskListRequestBody = {
  /**
   * Show only my tasks
   */
  mine?: boolean | undefined;
  /**
   * Filter by status
   */
  status?: string | undefined;
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/** @internal */
export type PostApiTaskListRequestBody$Outbound = {
  mine?: boolean | undefined;
  status?: string | undefined;
  workspace_path: string;
};

/** @internal */
export const PostApiTaskListRequestBody$outboundSchema: z.ZodType<
  PostApiTaskListRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiTaskListRequestBody
> = z.object({
  mine: z.boolean().optional(),
  status: z.string().optional(),
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});

export function postApiTaskListRequestBodyToJSON(
  postApiTaskListRequestBody: PostApiTaskListRequestBody,
): string {
  return JSON.stringify(
    PostApiTaskListRequestBody$outboundSchema.parse(postApiTaskListRequestBody),
  );
}
