/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiMcpAgentsAgentIdServersNameDisableRequest = {
  agentId: string;
  name: string;
};

/** @internal */
export type PostApiMcpAgentsAgentIdServersNameDisableRequest$Outbound = {
  agentId: string;
  name: string;
};

/** @internal */
export const PostApiMcpAgentsAgentIdServersNameDisableRequest$outboundSchema:
  z.ZodType<
    PostApiMcpAgentsAgentIdServersNameDisableRequest$Outbound,
    z.ZodTypeDef,
    PostApiMcpAgentsAgentIdServersNameDisableRequest
  > = z.object({
    agentId: z.string(),
    name: z.string(),
  });

export function postApiMcpAgentsAgentIdServersNameDisableRequestToJSON(
  postApiMcpAgentsAgentIdServersNameDisableRequest:
    PostApiMcpAgentsAgentIdServersNameDisableRequest,
): string {
  return JSON.stringify(
    PostApiMcpAgentsAgentIdServersNameDisableRequest$outboundSchema.parse(
      postApiMcpAgentsAgentIdServersNameDisableRequest,
    ),
  );
}
