/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiChannelsIdWebhookRequest = {
  id: string;
};

/** @internal */
export type PostApiChannelsIdWebhookRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostApiChannelsIdWebhookRequest$outboundSchema: z.ZodType<
  PostApiChannelsIdWebhookRequest$Outbound,
  z.ZodTypeDef,
  PostApiChannelsIdWebhookRequest
> = z.object({
  id: z.string(),
});

export function postApiChannelsIdWebhookRequestToJSON(
  postApiChannelsIdWebhookRequest: PostApiChannelsIdWebhookRequest,
): string {
  return JSON.stringify(
    PostApiChannelsIdWebhookRequest$outboundSchema.parse(
      postApiChannelsIdWebhookRequest,
    ),
  );
}
