/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiAgentTasksTaskIdStopRequest = {
  taskId: string;
};

/** @internal */
export type PostApiAgentTasksTaskIdStopRequest$Outbound = {
  taskId: string;
};

/** @internal */
export const PostApiAgentTasksTaskIdStopRequest$outboundSchema: z.ZodType<
  PostApiAgentTasksTaskIdStopRequest$Outbound,
  z.ZodTypeDef,
  PostApiAgentTasksTaskIdStopRequest
> = z.object({
  taskId: z.string(),
});

export function postApiAgentTasksTaskIdStopRequestToJSON(
  postApiAgentTasksTaskIdStopRequest: PostApiAgentTasksTaskIdStopRequest,
): string {
  return JSON.stringify(
    PostApiAgentTasksTaskIdStopRequest$outboundSchema.parse(
      postApiAgentTasksTaskIdStopRequest,
    ),
  );
}
