/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostApiAgentIdPromoteRequest = {
  id: string;
};

/** @internal */
export type PostApiAgentIdPromoteRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostApiAgentIdPromoteRequest$outboundSchema: z.ZodType<
  PostApiAgentIdPromoteRequest$Outbound,
  z.ZodTypeDef,
  PostApiAgentIdPromoteRequest
> = z.object({
  id: z.string(),
});

export function postApiAgentIdPromoteRequestToJSON(
  postApiAgentIdPromoteRequest: PostApiAgentIdPromoteRequest,
): string {
  return JSON.stringify(
    PostApiAgentIdPromoteRequest$outboundSchema.parse(
      postApiAgentIdPromoteRequest,
    ),
  );
}
