/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type PreviewListStartSseRequest = {
  /**
   * Task identifier
   */
  taskId: string;
  /**
   * Working directory path
   */
  workDir: string;
  /**
   * Preferred port (optional)
   */
  port?: string | undefined;
  /**
   * Custom command to run (e.g., 'npm run serve')
   */
  command?: string | undefined;
  /**
   * Regex pattern to detect server ready in stdout/stderr
   */
  readyPattern?: string | undefined;
  /**
   * Startup timeout in milliseconds
   */
  timeout?: string | undefined;
};

/** @internal */
export type PreviewListStartSseRequest$Outbound = {
  task_id: string;
  work_dir: string;
  port?: string | undefined;
  command?: string | undefined;
  ready_pattern?: string | undefined;
  timeout?: string | undefined;
};

/** @internal */
export const PreviewListStartSseRequest$outboundSchema: z.ZodType<
  PreviewListStartSseRequest$Outbound,
  z.ZodTypeDef,
  PreviewListStartSseRequest
> = z.object({
  taskId: z.string(),
  workDir: z.string(),
  port: z.string().optional(),
  command: z.string().optional(),
  readyPattern: z.string().optional(),
  timeout: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
    workDir: "work_dir",
    readyPattern: "ready_pattern",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PreviewListStartSseRequest$ {
  /** @deprecated use `PreviewListStartSseRequest$outboundSchema` instead. */
  export const outboundSchema = PreviewListStartSseRequest$outboundSchema;
  /** @deprecated use `PreviewListStartSseRequest$Outbound` instead. */
  export type Outbound = PreviewListStartSseRequest$Outbound;
}

export function previewListStartSseRequestToJSON(
  previewListStartSseRequest: PreviewListStartSseRequest,
): string {
  return JSON.stringify(
    PreviewListStartSseRequest$outboundSchema.parse(previewListStartSseRequest),
  );
}
