/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PreviewListStatus = {
  Starting: "starting",
  Running: "running",
  Stopped: "stopped",
  Error: "error",
} as const;
export type PreviewListStatus = ClosedEnum<typeof PreviewListStatus>;

export type Previews = {
  id?: string | undefined;
  taskId?: string | undefined;
  status?: PreviewListStatus | undefined;
  url?: string | undefined;
  hostPort?: number | undefined;
  error?: string | undefined;
  startedAt?: Date | undefined;
  lastAccessedAt?: Date | undefined;
};

/**
 * Default Response
 */
export type PreviewListResponseBody = {
  previews?: Array<Previews> | undefined;
  count?: number | undefined;
};

/** @internal */
export const PreviewListStatus$inboundSchema: z.ZodNativeEnum<
  typeof PreviewListStatus
> = z.nativeEnum(PreviewListStatus);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PreviewListStatus$ {
  /** @deprecated use `PreviewListStatus$inboundSchema` instead. */
  export const inboundSchema = PreviewListStatus$inboundSchema;
}

/** @internal */
export const Previews$inboundSchema: z.ZodType<
  Previews,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  task_id: z.string().optional(),
  status: PreviewListStatus$inboundSchema.optional(),
  url: z.string().optional(),
  host_port: z.number().optional(),
  error: z.string().optional(),
  started_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  last_accessed_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "task_id": "taskId",
    "host_port": "hostPort",
    "started_at": "startedAt",
    "last_accessed_at": "lastAccessedAt",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Previews$ {
  /** @deprecated use `Previews$inboundSchema` instead. */
  export const inboundSchema = Previews$inboundSchema;
}

export function previewsFromJSON(
  jsonString: string,
): SafeParseResult<Previews, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Previews$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Previews' from JSON`,
  );
}

/** @internal */
export const PreviewListResponseBody$inboundSchema: z.ZodType<
  PreviewListResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  previews: z.array(z.lazy(() => Previews$inboundSchema)).optional(),
  count: z.number().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PreviewListResponseBody$ {
  /** @deprecated use `PreviewListResponseBody$inboundSchema` instead. */
  export const inboundSchema = PreviewListResponseBody$inboundSchema;
}

export function previewListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PreviewListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewListResponseBody' from JSON`,
  );
}
