/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ProvidersTestRequest = {
  id: string;
};

/** @internal */
export type ProvidersTestRequest$Outbound = {
  id: string;
};

/** @internal */
export const ProvidersTestRequest$outboundSchema: z.ZodType<
  ProvidersTestRequest$Outbound,
  z.ZodTypeDef,
  ProvidersTestRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProvidersTestRequest$ {
  /** @deprecated use `ProvidersTestRequest$outboundSchema` instead. */
  export const outboundSchema = ProvidersTestRequest$outboundSchema;
  /** @deprecated use `ProvidersTestRequest$Outbound` instead. */
  export type Outbound = ProvidersTestRequest$Outbound;
}

export function providersTestRequestToJSON(
  providersTestRequest: ProvidersTestRequest,
): string {
  return JSON.stringify(
    ProvidersTestRequest$outboundSchema.parse(providersTestRequest),
  );
}
