/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ProvidersGetModelsRequest = {
  id: string;
};

/** @internal */
export type ProvidersGetModelsRequest$Outbound = {
  id: string;
};

/** @internal */
export const ProvidersGetModelsRequest$outboundSchema: z.ZodType<
  ProvidersGetModelsRequest$Outbound,
  z.ZodTypeDef,
  ProvidersGetModelsRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProvidersGetModelsRequest$ {
  /** @deprecated use `ProvidersGetModelsRequest$outboundSchema` instead. */
  export const outboundSchema = ProvidersGetModelsRequest$outboundSchema;
  /** @deprecated use `ProvidersGetModelsRequest$Outbound` instead. */
  export type Outbound = ProvidersGetModelsRequest$Outbound;
}

export function providersGetModelsRequestToJSON(
  providersGetModelsRequest: ProvidersGetModelsRequest,
): string {
  return JSON.stringify(
    ProvidersGetModelsRequest$outboundSchema.parse(providersGetModelsRequest),
  );
}
