/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type QueueDeleteTaskRequest = {
  id: string;
};

/** @internal */
export type QueueDeleteTaskRequest$Outbound = {
  id: string;
};

/** @internal */
export const QueueDeleteTaskRequest$outboundSchema: z.ZodType<
  QueueDeleteTaskRequest$Outbound,
  z.ZodTypeDef,
  QueueDeleteTaskRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueueDeleteTaskRequest$ {
  /** @deprecated use `QueueDeleteTaskRequest$outboundSchema` instead. */
  export const outboundSchema = QueueDeleteTaskRequest$outboundSchema;
  /** @deprecated use `QueueDeleteTaskRequest$Outbound` instead. */
  export type Outbound = QueueDeleteTaskRequest$Outbound;
}

export function queueDeleteTaskRequestToJSON(
  queueDeleteTaskRequest: QueueDeleteTaskRequest,
): string {
  return JSON.stringify(
    QueueDeleteTaskRequest$outboundSchema.parse(queueDeleteTaskRequest),
  );
}
