/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type QueueGetTaskStreamRequest = {
  id: string;
};

/** @internal */
export type QueueGetTaskStreamRequest$Outbound = {
  id: string;
};

/** @internal */
export const QueueGetTaskStreamRequest$outboundSchema: z.ZodType<
  QueueGetTaskStreamRequest$Outbound,
  z.ZodTypeDef,
  QueueGetTaskStreamRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueueGetTaskStreamRequest$ {
  /** @deprecated use `QueueGetTaskStreamRequest$outboundSchema` instead. */
  export const outboundSchema = QueueGetTaskStreamRequest$outboundSchema;
  /** @deprecated use `QueueGetTaskStreamRequest$Outbound` instead. */
  export type Outbound = QueueGetTaskStreamRequest$Outbound;
}

export function queueGetTaskStreamRequestToJSON(
  queueGetTaskStreamRequest: QueueGetTaskStreamRequest,
): string {
  return JSON.stringify(
    QueueGetTaskStreamRequest$outboundSchema.parse(queueGetTaskStreamRequest),
  );
}
