/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type QueueGetTaskRunningRequest = {
  id: string;
};

/** @internal */
export type QueueGetTaskRunningRequest$Outbound = {
  id: string;
};

/** @internal */
export const QueueGetTaskRunningRequest$outboundSchema: z.ZodType<
  QueueGetTaskRunningRequest$Outbound,
  z.ZodTypeDef,
  QueueGetTaskRunningRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueueGetTaskRunningRequest$ {
  /** @deprecated use `QueueGetTaskRunningRequest$outboundSchema` instead. */
  export const outboundSchema = QueueGetTaskRunningRequest$outboundSchema;
  /** @deprecated use `QueueGetTaskRunningRequest$Outbound` instead. */
  export type Outbound = QueueGetTaskRunningRequest$Outbound;
}

export function queueGetTaskRunningRequestToJSON(
  queueGetTaskRunningRequest: QueueGetTaskRunningRequest,
): string {
  return JSON.stringify(
    QueueGetTaskRunningRequest$outboundSchema.parse(queueGetTaskRunningRequest),
  );
}
