/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RewardListTypesRequest = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
};

/**
 * Default Response
 */
export type RewardListTypesRewardResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
};

export const RewardListTypesSource = {
  Builtin: "builtin",
  Custom: "custom",
} as const;
export type RewardListTypesSource = ClosedEnum<typeof RewardListTypesSource>;

export type RewardListTypesTypes = {
  name?: string | undefined;
  description?: string | undefined;
  weightDefault?: number | null | undefined;
  source?: RewardListTypesSource | undefined;
  promptPath?: string | undefined;
};

/**
 * Default Response
 */
export type RewardListTypesResponseBody = {
  success?: boolean | undefined;
  types?: Array<RewardListTypesTypes> | undefined;
  count?: number | undefined;
};

export type RewardListTypesResponse =
  | RewardListTypesResponseBody
  | RewardListTypesRewardResponseBody;

/** @internal */
export type RewardListTypesRequest$Outbound = {
  workspace_path: string;
};

/** @internal */
export const RewardListTypesRequest$outboundSchema: z.ZodType<
  RewardListTypesRequest$Outbound,
  z.ZodTypeDef,
  RewardListTypesRequest
> = z.object({
  workspacePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardListTypesRequest$ {
  /** @deprecated use `RewardListTypesRequest$outboundSchema` instead. */
  export const outboundSchema = RewardListTypesRequest$outboundSchema;
  /** @deprecated use `RewardListTypesRequest$Outbound` instead. */
  export type Outbound = RewardListTypesRequest$Outbound;
}

export function rewardListTypesRequestToJSON(
  rewardListTypesRequest: RewardListTypesRequest,
): string {
  return JSON.stringify(
    RewardListTypesRequest$outboundSchema.parse(rewardListTypesRequest),
  );
}

/** @internal */
export const RewardListTypesRewardResponseBody$inboundSchema: z.ZodType<
  RewardListTypesRewardResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardListTypesRewardResponseBody$ {
  /** @deprecated use `RewardListTypesRewardResponseBody$inboundSchema` instead. */
  export const inboundSchema = RewardListTypesRewardResponseBody$inboundSchema;
}

export function rewardListTypesRewardResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RewardListTypesRewardResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RewardListTypesRewardResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RewardListTypesRewardResponseBody' from JSON`,
  );
}

/** @internal */
export const RewardListTypesSource$inboundSchema: z.ZodNativeEnum<
  typeof RewardListTypesSource
> = z.nativeEnum(RewardListTypesSource);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardListTypesSource$ {
  /** @deprecated use `RewardListTypesSource$inboundSchema` instead. */
  export const inboundSchema = RewardListTypesSource$inboundSchema;
}

/** @internal */
export const RewardListTypesTypes$inboundSchema: z.ZodType<
  RewardListTypesTypes,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  weight_default: z.nullable(z.number()).optional(),
  source: RewardListTypesSource$inboundSchema.optional(),
  prompt_path: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "weight_default": "weightDefault",
    "prompt_path": "promptPath",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardListTypesTypes$ {
  /** @deprecated use `RewardListTypesTypes$inboundSchema` instead. */
  export const inboundSchema = RewardListTypesTypes$inboundSchema;
}

export function rewardListTypesTypesFromJSON(
  jsonString: string,
): SafeParseResult<RewardListTypesTypes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RewardListTypesTypes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RewardListTypesTypes' from JSON`,
  );
}

/** @internal */
export const RewardListTypesResponseBody$inboundSchema: z.ZodType<
  RewardListTypesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  types: z.array(z.lazy(() => RewardListTypesTypes$inboundSchema)).optional(),
  count: z.number().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardListTypesResponseBody$ {
  /** @deprecated use `RewardListTypesResponseBody$inboundSchema` instead. */
  export const inboundSchema = RewardListTypesResponseBody$inboundSchema;
}

export function rewardListTypesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RewardListTypesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RewardListTypesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RewardListTypesResponseBody' from JSON`,
  );
}

/** @internal */
export const RewardListTypesResponse$inboundSchema: z.ZodType<
  RewardListTypesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => RewardListTypesResponseBody$inboundSchema),
  z.lazy(() => RewardListTypesRewardResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardListTypesResponse$ {
  /** @deprecated use `RewardListTypesResponse$inboundSchema` instead. */
  export const inboundSchema = RewardListTypesResponse$inboundSchema;
}

export function rewardListTypesResponseFromJSON(
  jsonString: string,
): SafeParseResult<RewardListTypesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RewardListTypesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RewardListTypesResponse' from JSON`,
  );
}
