/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RewardDeleteTypeRequest = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Reward type name
   */
  name: string;
};

/**
 * Default Response
 */
export type RewardDeleteTypeRewardResponseResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type RewardDeleteTypeRewardResponseBody = {
  success?: boolean | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type RewardDeleteTypeResponseBody = {
  success?: boolean | undefined;
  deletedType?: string | undefined;
};

export type RewardDeleteTypeResponse =
  | RewardDeleteTypeResponseBody
  | RewardDeleteTypeRewardResponseBody
  | RewardDeleteTypeRewardResponseResponseBody;

/** @internal */
export type RewardDeleteTypeRequest$Outbound = {
  workspace_path: string;
  name: string;
};

/** @internal */
export const RewardDeleteTypeRequest$outboundSchema: z.ZodType<
  RewardDeleteTypeRequest$Outbound,
  z.ZodTypeDef,
  RewardDeleteTypeRequest
> = z.object({
  workspacePath: z.string(),
  name: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardDeleteTypeRequest$ {
  /** @deprecated use `RewardDeleteTypeRequest$outboundSchema` instead. */
  export const outboundSchema = RewardDeleteTypeRequest$outboundSchema;
  /** @deprecated use `RewardDeleteTypeRequest$Outbound` instead. */
  export type Outbound = RewardDeleteTypeRequest$Outbound;
}

export function rewardDeleteTypeRequestToJSON(
  rewardDeleteTypeRequest: RewardDeleteTypeRequest,
): string {
  return JSON.stringify(
    RewardDeleteTypeRequest$outboundSchema.parse(rewardDeleteTypeRequest),
  );
}

/** @internal */
export const RewardDeleteTypeRewardResponseResponseBody$inboundSchema:
  z.ZodType<RewardDeleteTypeRewardResponseResponseBody, z.ZodTypeDef, unknown> =
    z.object({
      success: z.boolean().optional(),
      error: z.string().optional(),
    });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardDeleteTypeRewardResponseResponseBody$ {
  /** @deprecated use `RewardDeleteTypeRewardResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    RewardDeleteTypeRewardResponseResponseBody$inboundSchema;
}

export function rewardDeleteTypeRewardResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  RewardDeleteTypeRewardResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RewardDeleteTypeRewardResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RewardDeleteTypeRewardResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const RewardDeleteTypeRewardResponseBody$inboundSchema: z.ZodType<
  RewardDeleteTypeRewardResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardDeleteTypeRewardResponseBody$ {
  /** @deprecated use `RewardDeleteTypeRewardResponseBody$inboundSchema` instead. */
  export const inboundSchema = RewardDeleteTypeRewardResponseBody$inboundSchema;
}

export function rewardDeleteTypeRewardResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RewardDeleteTypeRewardResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RewardDeleteTypeRewardResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RewardDeleteTypeRewardResponseBody' from JSON`,
  );
}

/** @internal */
export const RewardDeleteTypeResponseBody$inboundSchema: z.ZodType<
  RewardDeleteTypeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  deleted_type: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "deleted_type": "deletedType",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardDeleteTypeResponseBody$ {
  /** @deprecated use `RewardDeleteTypeResponseBody$inboundSchema` instead. */
  export const inboundSchema = RewardDeleteTypeResponseBody$inboundSchema;
}

export function rewardDeleteTypeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RewardDeleteTypeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RewardDeleteTypeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RewardDeleteTypeResponseBody' from JSON`,
  );
}

/** @internal */
export const RewardDeleteTypeResponse$inboundSchema: z.ZodType<
  RewardDeleteTypeResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => RewardDeleteTypeResponseBody$inboundSchema),
  z.lazy(() => RewardDeleteTypeRewardResponseBody$inboundSchema),
  z.lazy(() => RewardDeleteTypeRewardResponseResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RewardDeleteTypeResponse$ {
  /** @deprecated use `RewardDeleteTypeResponse$inboundSchema` instead. */
  export const inboundSchema = RewardDeleteTypeResponse$inboundSchema;
}

export function rewardDeleteTypeResponseFromJSON(
  jsonString: string,
): SafeParseResult<RewardDeleteTypeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RewardDeleteTypeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RewardDeleteTypeResponse' from JSON`,
  );
}
