/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ServiceKeysCreateUsageRequest = {
  keyId: string;
};

/** @internal */
export type ServiceKeysCreateUsageRequest$Outbound = {
  keyId: string;
};

/** @internal */
export const ServiceKeysCreateUsageRequest$outboundSchema: z.ZodType<
  ServiceKeysCreateUsageRequest$Outbound,
  z.ZodTypeDef,
  ServiceKeysCreateUsageRequest
> = z.object({
  keyId: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServiceKeysCreateUsageRequest$ {
  /** @deprecated use `ServiceKeysCreateUsageRequest$outboundSchema` instead. */
  export const outboundSchema = ServiceKeysCreateUsageRequest$outboundSchema;
  /** @deprecated use `ServiceKeysCreateUsageRequest$Outbound` instead. */
  export type Outbound = ServiceKeysCreateUsageRequest$Outbound;
}

export function serviceKeysCreateUsageRequestToJSON(
  serviceKeysCreateUsageRequest: ServiceKeysCreateUsageRequest,
): string {
  return JSON.stringify(
    ServiceKeysCreateUsageRequest$outboundSchema.parse(
      serviceKeysCreateUsageRequest,
    ),
  );
}
