/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type SkillSearchClawhubRequest = {
  /**
   * Search query
   */
  query: string;
  /**
   * Maximum results
   */
  limit?: string | undefined;
  /**
   * Whether to include only non-suspicious packages
   */
  nonSuspiciousOnly?: string | undefined;
};

/** @internal */
export type SkillSearchClawhubRequest$Outbound = {
  query: string;
  limit?: string | undefined;
  non_suspicious_only?: string | undefined;
};

/** @internal */
export const SkillSearchClawhubRequest$outboundSchema: z.ZodType<
  SkillSearchClawhubRequest$Outbound,
  z.ZodTypeDef,
  SkillSearchClawhubRequest
> = z.object({
  query: z.string(),
  limit: z.string().optional(),
  nonSuspiciousOnly: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    nonSuspiciousOnly: "non_suspicious_only",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillSearchClawhubRequest$ {
  /** @deprecated use `SkillSearchClawhubRequest$outboundSchema` instead. */
  export const outboundSchema = SkillSearchClawhubRequest$outboundSchema;
  /** @deprecated use `SkillSearchClawhubRequest$Outbound` instead. */
  export type Outbound = SkillSearchClawhubRequest$Outbound;
}

export function skillSearchClawhubRequestToJSON(
  skillSearchClawhubRequest: SkillSearchClawhubRequest,
): string {
  return JSON.stringify(
    SkillSearchClawhubRequest$outboundSchema.parse(skillSearchClawhubRequest),
  );
}
