/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Filter by installation target
 */
export const SkillListQueryParamTarget = {
  Agent: "agent",
  Global: "global",
  Claude: "claude",
  Custom: "custom",
} as const;
/**
 * Filter by installation target
 */
export type SkillListQueryParamTarget = ClosedEnum<
  typeof SkillListQueryParamTarget
>;

export type SkillListRequest = {
  /**
   * Filter by installation target
   */
  target?: SkillListQueryParamTarget | undefined;
  /**
   * Agent ID (required when target is 'agent')
   */
  agentId?: string | undefined;
  /**
   * Custom path (required when target is 'custom')
   */
  customPath?: string | undefined;
};

/**
 * Default Response
 */
export type SkillListSkillResponseBody = {
  error?: string | undefined;
};

export type Skills = {
  name?: string | undefined;
  version?: string | undefined;
  path?: string | undefined;
  installedAt?: string | undefined;
};

/**
 * Default Response
 */
export type SkillListResponseBody = {
  skills?: Array<Skills> | undefined;
  count?: number | undefined;
};

export type SkillListResponse =
  | SkillListResponseBody
  | SkillListSkillResponseBody;

/** @internal */
export const SkillListQueryParamTarget$outboundSchema: z.ZodNativeEnum<
  typeof SkillListQueryParamTarget
> = z.nativeEnum(SkillListQueryParamTarget);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListQueryParamTarget$ {
  /** @deprecated use `SkillListQueryParamTarget$outboundSchema` instead. */
  export const outboundSchema = SkillListQueryParamTarget$outboundSchema;
}

/** @internal */
export type SkillListRequest$Outbound = {
  target?: string | undefined;
  agent_id?: string | undefined;
  custom_path?: string | undefined;
};

/** @internal */
export const SkillListRequest$outboundSchema: z.ZodType<
  SkillListRequest$Outbound,
  z.ZodTypeDef,
  SkillListRequest
> = z.object({
  target: SkillListQueryParamTarget$outboundSchema.optional(),
  agentId: z.string().optional(),
  customPath: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    agentId: "agent_id",
    customPath: "custom_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListRequest$ {
  /** @deprecated use `SkillListRequest$outboundSchema` instead. */
  export const outboundSchema = SkillListRequest$outboundSchema;
  /** @deprecated use `SkillListRequest$Outbound` instead. */
  export type Outbound = SkillListRequest$Outbound;
}

export function skillListRequestToJSON(
  skillListRequest: SkillListRequest,
): string {
  return JSON.stringify(
    SkillListRequest$outboundSchema.parse(skillListRequest),
  );
}

/** @internal */
export const SkillListSkillResponseBody$inboundSchema: z.ZodType<
  SkillListSkillResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListSkillResponseBody$ {
  /** @deprecated use `SkillListSkillResponseBody$inboundSchema` instead. */
  export const inboundSchema = SkillListSkillResponseBody$inboundSchema;
}

export function skillListSkillResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SkillListSkillResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillListSkillResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillListSkillResponseBody' from JSON`,
  );
}

/** @internal */
export const Skills$inboundSchema: z.ZodType<Skills, z.ZodTypeDef, unknown> = z
  .object({
    name: z.string().optional(),
    version: z.string().optional(),
    path: z.string().optional(),
    installed_at: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "installed_at": "installedAt",
    });
  });
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Skills$ {
  /** @deprecated use `Skills$inboundSchema` instead. */
  export const inboundSchema = Skills$inboundSchema;
}

export function skillsFromJSON(
  jsonString: string,
): SafeParseResult<Skills, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Skills$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Skills' from JSON`,
  );
}

/** @internal */
export const SkillListResponseBody$inboundSchema: z.ZodType<
  SkillListResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  skills: z.array(z.lazy(() => Skills$inboundSchema)).optional(),
  count: z.number().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListResponseBody$ {
  /** @deprecated use `SkillListResponseBody$inboundSchema` instead. */
  export const inboundSchema = SkillListResponseBody$inboundSchema;
}

export function skillListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SkillListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillListResponseBody' from JSON`,
  );
}

/** @internal */
export const SkillListResponse$inboundSchema: z.ZodType<
  SkillListResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => SkillListResponseBody$inboundSchema),
  z.lazy(() => SkillListSkillResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListResponse$ {
  /** @deprecated use `SkillListResponse$inboundSchema` instead. */
  export const inboundSchema = SkillListResponse$inboundSchema;
}

export function skillListResponseFromJSON(
  jsonString: string,
): SafeParseResult<SkillListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillListResponse' from JSON`,
  );
}
