/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SkillMarketCreateCommentRequest = {
  id: string;
};

/** @internal */
export type SkillMarketCreateCommentRequest$Outbound = {
  id: string;
};

/** @internal */
export const SkillMarketCreateCommentRequest$outboundSchema: z.ZodType<
  SkillMarketCreateCommentRequest$Outbound,
  z.ZodTypeDef,
  SkillMarketCreateCommentRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillMarketCreateCommentRequest$ {
  /** @deprecated use `SkillMarketCreateCommentRequest$outboundSchema` instead. */
  export const outboundSchema = SkillMarketCreateCommentRequest$outboundSchema;
  /** @deprecated use `SkillMarketCreateCommentRequest$Outbound` instead. */
  export type Outbound = SkillMarketCreateCommentRequest$Outbound;
}

export function skillMarketCreateCommentRequestToJSON(
  skillMarketCreateCommentRequest: SkillMarketCreateCommentRequest,
): string {
  return JSON.stringify(
    SkillMarketCreateCommentRequest$outboundSchema.parse(
      skillMarketCreateCommentRequest,
    ),
  );
}
