/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const SkillUninstallTarget = {
  Agent: "agent",
  Global: "global",
  Claude: "claude",
  Custom: "custom",
} as const;
export type SkillUninstallTarget = ClosedEnum<typeof SkillUninstallTarget>;

export type SkillUninstallRequestBody = {
  /**
   * Skill name
   */
  name: string;
  target?: SkillUninstallTarget | undefined;
  agentId?: string | undefined;
  customPath?: string | undefined;
};

/**
 * Default Response
 */
export type SkillUninstallSkillResponseResponseBody = {
  success?: boolean | undefined;
  message?: string | undefined;
  error?: string | undefined;
};

/**
 * Default Response
 */
export type SkillUninstallSkillResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type SkillUninstallResponseBody = {
  success?: boolean | undefined;
  name?: string | undefined;
  message?: string | undefined;
};

export type SkillUninstallResponse =
  | SkillUninstallResponseBody
  | SkillUninstallSkillResponseBody
  | SkillUninstallSkillResponseResponseBody;

/** @internal */
export const SkillUninstallTarget$outboundSchema: z.ZodNativeEnum<
  typeof SkillUninstallTarget
> = z.nativeEnum(SkillUninstallTarget);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillUninstallTarget$ {
  /** @deprecated use `SkillUninstallTarget$outboundSchema` instead. */
  export const outboundSchema = SkillUninstallTarget$outboundSchema;
}

/** @internal */
export type SkillUninstallRequestBody$Outbound = {
  name: string;
  target: string;
  agent_id?: string | undefined;
  custom_path?: string | undefined;
};

/** @internal */
export const SkillUninstallRequestBody$outboundSchema: z.ZodType<
  SkillUninstallRequestBody$Outbound,
  z.ZodTypeDef,
  SkillUninstallRequestBody
> = z.object({
  name: z.string(),
  target: SkillUninstallTarget$outboundSchema.default("global"),
  agentId: z.string().optional(),
  customPath: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    agentId: "agent_id",
    customPath: "custom_path",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillUninstallRequestBody$ {
  /** @deprecated use `SkillUninstallRequestBody$outboundSchema` instead. */
  export const outboundSchema = SkillUninstallRequestBody$outboundSchema;
  /** @deprecated use `SkillUninstallRequestBody$Outbound` instead. */
  export type Outbound = SkillUninstallRequestBody$Outbound;
}

export function skillUninstallRequestBodyToJSON(
  skillUninstallRequestBody: SkillUninstallRequestBody,
): string {
  return JSON.stringify(
    SkillUninstallRequestBody$outboundSchema.parse(skillUninstallRequestBody),
  );
}

/** @internal */
export const SkillUninstallSkillResponseResponseBody$inboundSchema: z.ZodType<
  SkillUninstallSkillResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  message: z.string().optional(),
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillUninstallSkillResponseResponseBody$ {
  /** @deprecated use `SkillUninstallSkillResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    SkillUninstallSkillResponseResponseBody$inboundSchema;
}

export function skillUninstallSkillResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  SkillUninstallSkillResponseResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SkillUninstallSkillResponseResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SkillUninstallSkillResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const SkillUninstallSkillResponseBody$inboundSchema: z.ZodType<
  SkillUninstallSkillResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillUninstallSkillResponseBody$ {
  /** @deprecated use `SkillUninstallSkillResponseBody$inboundSchema` instead. */
  export const inboundSchema = SkillUninstallSkillResponseBody$inboundSchema;
}

export function skillUninstallSkillResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SkillUninstallSkillResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillUninstallSkillResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillUninstallSkillResponseBody' from JSON`,
  );
}

/** @internal */
export const SkillUninstallResponseBody$inboundSchema: z.ZodType<
  SkillUninstallResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  name: z.string().optional(),
  message: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillUninstallResponseBody$ {
  /** @deprecated use `SkillUninstallResponseBody$inboundSchema` instead. */
  export const inboundSchema = SkillUninstallResponseBody$inboundSchema;
}

export function skillUninstallResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SkillUninstallResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillUninstallResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillUninstallResponseBody' from JSON`,
  );
}

/** @internal */
export const SkillUninstallResponse$inboundSchema: z.ZodType<
  SkillUninstallResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => SkillUninstallResponseBody$inboundSchema),
  z.lazy(() => SkillUninstallSkillResponseBody$inboundSchema),
  z.lazy(() => SkillUninstallSkillResponseResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillUninstallResponse$ {
  /** @deprecated use `SkillUninstallResponse$inboundSchema` instead. */
  export const inboundSchema = SkillUninstallResponse$inboundSchema;
}

export function skillUninstallResponseFromJSON(
  jsonString: string,
): SafeParseResult<SkillUninstallResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillUninstallResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillUninstallResponse' from JSON`,
  );
}
