/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SkillListEnabledRequest = {
  /**
   * Agent ID (required)
   */
  agentId: string;
};

/**
 * Default Response
 */
export type SkillListEnabledSkillResponseBody = {
  error?: string | undefined;
};

export type SkillListEnabledSkills = {
  skillName?: string | undefined;
  enabled?: boolean | undefined;
  agentId?: string | undefined;
  enabledAt?: string | undefined;
};

/**
 * Default Response
 */
export type SkillListEnabledResponseBody = {
  skills?: Array<SkillListEnabledSkills> | undefined;
  count?: number | undefined;
  agentId?: string | undefined;
};

export type SkillListEnabledResponse =
  | SkillListEnabledResponseBody
  | SkillListEnabledSkillResponseBody;

/** @internal */
export type SkillListEnabledRequest$Outbound = {
  agent_id: string;
};

/** @internal */
export const SkillListEnabledRequest$outboundSchema: z.ZodType<
  SkillListEnabledRequest$Outbound,
  z.ZodTypeDef,
  SkillListEnabledRequest
> = z.object({
  agentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    agentId: "agent_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListEnabledRequest$ {
  /** @deprecated use `SkillListEnabledRequest$outboundSchema` instead. */
  export const outboundSchema = SkillListEnabledRequest$outboundSchema;
  /** @deprecated use `SkillListEnabledRequest$Outbound` instead. */
  export type Outbound = SkillListEnabledRequest$Outbound;
}

export function skillListEnabledRequestToJSON(
  skillListEnabledRequest: SkillListEnabledRequest,
): string {
  return JSON.stringify(
    SkillListEnabledRequest$outboundSchema.parse(skillListEnabledRequest),
  );
}

/** @internal */
export const SkillListEnabledSkillResponseBody$inboundSchema: z.ZodType<
  SkillListEnabledSkillResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListEnabledSkillResponseBody$ {
  /** @deprecated use `SkillListEnabledSkillResponseBody$inboundSchema` instead. */
  export const inboundSchema = SkillListEnabledSkillResponseBody$inboundSchema;
}

export function skillListEnabledSkillResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SkillListEnabledSkillResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillListEnabledSkillResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillListEnabledSkillResponseBody' from JSON`,
  );
}

/** @internal */
export const SkillListEnabledSkills$inboundSchema: z.ZodType<
  SkillListEnabledSkills,
  z.ZodTypeDef,
  unknown
> = z.object({
  skillName: z.string().optional(),
  enabled: z.boolean().optional(),
  agentId: z.string().optional(),
  enabledAt: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListEnabledSkills$ {
  /** @deprecated use `SkillListEnabledSkills$inboundSchema` instead. */
  export const inboundSchema = SkillListEnabledSkills$inboundSchema;
}

export function skillListEnabledSkillsFromJSON(
  jsonString: string,
): SafeParseResult<SkillListEnabledSkills, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillListEnabledSkills$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillListEnabledSkills' from JSON`,
  );
}

/** @internal */
export const SkillListEnabledResponseBody$inboundSchema: z.ZodType<
  SkillListEnabledResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  skills: z.array(z.lazy(() => SkillListEnabledSkills$inboundSchema))
    .optional(),
  count: z.number().optional(),
  agent_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "agent_id": "agentId",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListEnabledResponseBody$ {
  /** @deprecated use `SkillListEnabledResponseBody$inboundSchema` instead. */
  export const inboundSchema = SkillListEnabledResponseBody$inboundSchema;
}

export function skillListEnabledResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SkillListEnabledResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillListEnabledResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillListEnabledResponseBody' from JSON`,
  );
}

/** @internal */
export const SkillListEnabledResponse$inboundSchema: z.ZodType<
  SkillListEnabledResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => SkillListEnabledResponseBody$inboundSchema),
  z.lazy(() => SkillListEnabledSkillResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillListEnabledResponse$ {
  /** @deprecated use `SkillListEnabledResponse$inboundSchema` instead. */
  export const inboundSchema = SkillListEnabledResponse$inboundSchema;
}

export function skillListEnabledResponseFromJSON(
  jsonString: string,
): SafeParseResult<SkillListEnabledResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkillListEnabledResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkillListEnabledResponse' from JSON`,
  );
}
