/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SkillMarketCreateFavoriteRequest = {
  id: string;
};

/** @internal */
export type SkillMarketCreateFavoriteRequest$Outbound = {
  id: string;
};

/** @internal */
export const SkillMarketCreateFavoriteRequest$outboundSchema: z.ZodType<
  SkillMarketCreateFavoriteRequest$Outbound,
  z.ZodTypeDef,
  SkillMarketCreateFavoriteRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillMarketCreateFavoriteRequest$ {
  /** @deprecated use `SkillMarketCreateFavoriteRequest$outboundSchema` instead. */
  export const outboundSchema = SkillMarketCreateFavoriteRequest$outboundSchema;
  /** @deprecated use `SkillMarketCreateFavoriteRequest$Outbound` instead. */
  export type Outbound = SkillMarketCreateFavoriteRequest$Outbound;
}

export function skillMarketCreateFavoriteRequestToJSON(
  skillMarketCreateFavoriteRequest: SkillMarketCreateFavoriteRequest,
): string {
  return JSON.stringify(
    SkillMarketCreateFavoriteRequest$outboundSchema.parse(
      skillMarketCreateFavoriteRequest,
    ),
  );
}
