/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type TaskListEventsStreamRequest = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Comma-separated task IDs for filtering
   */
  taskIds?: string | undefined;
  /**
   * Last received sequence for replay
   */
  lastSequence?: string | undefined;
};

/** @internal */
export type TaskListEventsStreamRequest$Outbound = {
  workspace_path: string;
  task_ids?: string | undefined;
  last_sequence?: string | undefined;
};

/** @internal */
export const TaskListEventsStreamRequest$outboundSchema: z.ZodType<
  TaskListEventsStreamRequest$Outbound,
  z.ZodTypeDef,
  TaskListEventsStreamRequest
> = z.object({
  workspacePath: z.string(),
  taskIds: z.string().optional(),
  lastSequence: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
    taskIds: "task_ids",
    lastSequence: "last_sequence",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskListEventsStreamRequest$ {
  /** @deprecated use `TaskListEventsStreamRequest$outboundSchema` instead. */
  export const outboundSchema = TaskListEventsStreamRequest$outboundSchema;
  /** @deprecated use `TaskListEventsStreamRequest$Outbound` instead. */
  export type Outbound = TaskListEventsStreamRequest$Outbound;
}

export function taskListEventsStreamRequestToJSON(
  taskListEventsStreamRequest: TaskListEventsStreamRequest,
): string {
  return JSON.stringify(
    TaskListEventsStreamRequest$outboundSchema.parse(
      taskListEventsStreamRequest,
    ),
  );
}
