/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type TaskCleanupRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Branch name to cleanup
   */
  branch?: string | undefined;
  /**
   * Keep the git branch
   */
  keepBranch?: boolean | undefined;
  /**
   * Cleanup merged worktrees
   */
  merged?: boolean | undefined;
  /**
   * Cleanup all worktrees
   */
  all?: boolean | undefined;
  /**
   * List all worktrees
   */
  list?: boolean | undefined;
};

/** @internal */
export type TaskCleanupRequestBody$Outbound = {
  workspace_path: string;
  branch?: string | undefined;
  keep_branch?: boolean | undefined;
  merged?: boolean | undefined;
  all?: boolean | undefined;
  list?: boolean | undefined;
};

/** @internal */
export const TaskCleanupRequestBody$outboundSchema: z.ZodType<
  TaskCleanupRequestBody$Outbound,
  z.ZodTypeDef,
  TaskCleanupRequestBody
> = z.object({
  workspacePath: z.string(),
  branch: z.string().optional(),
  keepBranch: z.boolean().optional(),
  merged: z.boolean().optional(),
  all: z.boolean().optional(),
  list: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
    keepBranch: "keep_branch",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskCleanupRequestBody$ {
  /** @deprecated use `TaskCleanupRequestBody$outboundSchema` instead. */
  export const outboundSchema = TaskCleanupRequestBody$outboundSchema;
  /** @deprecated use `TaskCleanupRequestBody$Outbound` instead. */
  export type Outbound = TaskCleanupRequestBody$Outbound;
}

export function taskCleanupRequestBodyToJSON(
  taskCleanupRequestBody: TaskCleanupRequestBody,
): string {
  return JSON.stringify(
    TaskCleanupRequestBody$outboundSchema.parse(taskCleanupRequestBody),
  );
}
