/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TaskCreateQueueConfigRequestBody = {
  maxConcurrency?: number | undefined;
  defaultMaxRetries?: number | undefined;
};

/**
 * Default Response
 */
export type TaskCreateQueueConfigResponseBody = {
  maxConcurrency?: number | undefined;
  defaultMaxRetries?: number | undefined;
  persistDebounceMs?: number | undefined;
  shutdownTimeoutMs?: number | undefined;
};

/** @internal */
export type TaskCreateQueueConfigRequestBody$Outbound = {
  max_concurrency?: number | undefined;
  default_max_retries?: number | undefined;
};

/** @internal */
export const TaskCreateQueueConfigRequestBody$outboundSchema: z.ZodType<
  TaskCreateQueueConfigRequestBody$Outbound,
  z.ZodTypeDef,
  TaskCreateQueueConfigRequestBody
> = z.object({
  maxConcurrency: z.number().optional(),
  defaultMaxRetries: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    maxConcurrency: "max_concurrency",
    defaultMaxRetries: "default_max_retries",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskCreateQueueConfigRequestBody$ {
  /** @deprecated use `TaskCreateQueueConfigRequestBody$outboundSchema` instead. */
  export const outboundSchema = TaskCreateQueueConfigRequestBody$outboundSchema;
  /** @deprecated use `TaskCreateQueueConfigRequestBody$Outbound` instead. */
  export type Outbound = TaskCreateQueueConfigRequestBody$Outbound;
}

export function taskCreateQueueConfigRequestBodyToJSON(
  taskCreateQueueConfigRequestBody: TaskCreateQueueConfigRequestBody,
): string {
  return JSON.stringify(
    TaskCreateQueueConfigRequestBody$outboundSchema.parse(
      taskCreateQueueConfigRequestBody,
    ),
  );
}

/** @internal */
export const TaskCreateQueueConfigResponseBody$inboundSchema: z.ZodType<
  TaskCreateQueueConfigResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  max_concurrency: z.number().optional(),
  default_max_retries: z.number().optional(),
  persist_debounce_ms: z.number().optional(),
  shutdown_timeout_ms: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "max_concurrency": "maxConcurrency",
    "default_max_retries": "defaultMaxRetries",
    "persist_debounce_ms": "persistDebounceMs",
    "shutdown_timeout_ms": "shutdownTimeoutMs",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskCreateQueueConfigResponseBody$ {
  /** @deprecated use `TaskCreateQueueConfigResponseBody$inboundSchema` instead. */
  export const inboundSchema = TaskCreateQueueConfigResponseBody$inboundSchema;
}

export function taskCreateQueueConfigResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskCreateQueueConfigResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskCreateQueueConfigResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskCreateQueueConfigResponseBody' from JSON`,
  );
}
