/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TaskStopRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Task directory path or ID (required)
   */
  taskDir: string;
};

/**
 * Default Response
 */
export type TaskStopTasksResponseBody = {
  error?: string | undefined;
};

/**
 * Default Response
 */
export type TaskStopResponseBody = {
  success?: boolean | undefined;
  cancelled?: boolean | undefined;
  taskId?: string | undefined;
};

export type TaskStopResponse = TaskStopResponseBody | TaskStopTasksResponseBody;

/** @internal */
export type TaskStopRequestBody$Outbound = {
  workspace_path: string;
  task_dir: string;
};

/** @internal */
export const TaskStopRequestBody$outboundSchema: z.ZodType<
  TaskStopRequestBody$Outbound,
  z.ZodTypeDef,
  TaskStopRequestBody
> = z.object({
  workspacePath: z.string(),
  taskDir: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
    taskDir: "task_dir",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskStopRequestBody$ {
  /** @deprecated use `TaskStopRequestBody$outboundSchema` instead. */
  export const outboundSchema = TaskStopRequestBody$outboundSchema;
  /** @deprecated use `TaskStopRequestBody$Outbound` instead. */
  export type Outbound = TaskStopRequestBody$Outbound;
}

export function taskStopRequestBodyToJSON(
  taskStopRequestBody: TaskStopRequestBody,
): string {
  return JSON.stringify(
    TaskStopRequestBody$outboundSchema.parse(taskStopRequestBody),
  );
}

/** @internal */
export const TaskStopTasksResponseBody$inboundSchema: z.ZodType<
  TaskStopTasksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskStopTasksResponseBody$ {
  /** @deprecated use `TaskStopTasksResponseBody$inboundSchema` instead. */
  export const inboundSchema = TaskStopTasksResponseBody$inboundSchema;
}

export function taskStopTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskStopTasksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskStopTasksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskStopTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const TaskStopResponseBody$inboundSchema: z.ZodType<
  TaskStopResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  cancelled: z.boolean().optional(),
  task_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "task_id": "taskId",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskStopResponseBody$ {
  /** @deprecated use `TaskStopResponseBody$inboundSchema` instead. */
  export const inboundSchema = TaskStopResponseBody$inboundSchema;
}

export function taskStopResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskStopResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskStopResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskStopResponseBody' from JSON`,
  );
}

/** @internal */
export const TaskStopResponse$inboundSchema: z.ZodType<
  TaskStopResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => TaskStopResponseBody$inboundSchema),
  z.lazy(() => TaskStopTasksResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskStopResponse$ {
  /** @deprecated use `TaskStopResponse$inboundSchema` instead. */
  export const inboundSchema = TaskStopResponse$inboundSchema;
}

export function taskStopResponseFromJSON(
  jsonString: string,
): SafeParseResult<TaskStopResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskStopResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskStopResponse' from JSON`,
  );
}
