/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type TasksGetEventsRequest = {
  taskId: string;
};

/** @internal */
export type TasksGetEventsRequest$Outbound = {
  task_id: string;
};

/** @internal */
export const TasksGetEventsRequest$outboundSchema: z.ZodType<
  TasksGetEventsRequest$Outbound,
  z.ZodTypeDef,
  TasksGetEventsRequest
> = z.object({
  taskId: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TasksGetEventsRequest$ {
  /** @deprecated use `TasksGetEventsRequest$outboundSchema` instead. */
  export const outboundSchema = TasksGetEventsRequest$outboundSchema;
  /** @deprecated use `TasksGetEventsRequest$Outbound` instead. */
  export type Outbound = TasksGetEventsRequest$Outbound;
}

export function tasksGetEventsRequestToJSON(
  tasksGetEventsRequest: TasksGetEventsRequest,
): string {
  return JSON.stringify(
    TasksGetEventsRequest$outboundSchema.parse(tasksGetEventsRequest),
  );
}
