/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type TasksUpdate2Request = {
  id: string;
};

/** @internal */
export type TasksUpdate2Request$Outbound = {
  id: string;
};

/** @internal */
export const TasksUpdate2Request$outboundSchema: z.ZodType<
  TasksUpdate2Request$Outbound,
  z.ZodTypeDef,
  TasksUpdate2Request
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TasksUpdate2Request$ {
  /** @deprecated use `TasksUpdate2Request$outboundSchema` instead. */
  export const outboundSchema = TasksUpdate2Request$outboundSchema;
  /** @deprecated use `TasksUpdate2Request$Outbound` instead. */
  export type Outbound = TasksUpdate2Request$Outbound;
}

export function tasksUpdate2RequestToJSON(
  tasksUpdate2Request: TasksUpdate2Request,
): string {
  return JSON.stringify(
    TasksUpdate2Request$outboundSchema.parse(tasksUpdate2Request),
  );
}
