/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TaskCreateFinishRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Task ID or directory (required)
   */
  taskId: string;
};

/**
 * Default Response
 */
export type TaskCreateFinishResponseBody = {
  success?: boolean | undefined;
  taskId?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export type TaskCreateFinishRequestBody$Outbound = {
  workspace_path: string;
  task_id: string;
};

/** @internal */
export const TaskCreateFinishRequestBody$outboundSchema: z.ZodType<
  TaskCreateFinishRequestBody$Outbound,
  z.ZodTypeDef,
  TaskCreateFinishRequestBody
> = z.object({
  workspacePath: z.string(),
  taskId: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
    taskId: "task_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskCreateFinishRequestBody$ {
  /** @deprecated use `TaskCreateFinishRequestBody$outboundSchema` instead. */
  export const outboundSchema = TaskCreateFinishRequestBody$outboundSchema;
  /** @deprecated use `TaskCreateFinishRequestBody$Outbound` instead. */
  export type Outbound = TaskCreateFinishRequestBody$Outbound;
}

export function taskCreateFinishRequestBodyToJSON(
  taskCreateFinishRequestBody: TaskCreateFinishRequestBody,
): string {
  return JSON.stringify(
    TaskCreateFinishRequestBody$outboundSchema.parse(
      taskCreateFinishRequestBody,
    ),
  );
}

/** @internal */
export const TaskCreateFinishResponseBody$inboundSchema: z.ZodType<
  TaskCreateFinishResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  task_id: z.string().optional(),
  message: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "task_id": "taskId",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskCreateFinishResponseBody$ {
  /** @deprecated use `TaskCreateFinishResponseBody$inboundSchema` instead. */
  export const inboundSchema = TaskCreateFinishResponseBody$inboundSchema;
}

export function taskCreateFinishResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskCreateFinishResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskCreateFinishResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskCreateFinishResponseBody' from JSON`,
  );
}
