/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type TaskCreateWorkPhaseRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Task ID or directory (required)
   */
  taskId: string;
  /**
   * Platform (claude, cursor, iflow, opencode)
   */
  platform?: string | undefined;
  /**
   * Enable verbose output
   */
  verbose?: boolean | undefined;
  /**
   * Run in background
   */
  detach?: boolean | undefined;
};

/** @internal */
export type TaskCreateWorkPhaseRequestBody$Outbound = {
  workspace_path: string;
  task_id: string;
  platform: string;
  verbose?: boolean | undefined;
  detach: boolean;
};

/** @internal */
export const TaskCreateWorkPhaseRequestBody$outboundSchema: z.ZodType<
  TaskCreateWorkPhaseRequestBody$Outbound,
  z.ZodTypeDef,
  TaskCreateWorkPhaseRequestBody
> = z.object({
  workspacePath: z.string(),
  taskId: z.string(),
  platform: z.string().default("claude"),
  verbose: z.boolean().optional(),
  detach: z.boolean().default(true),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
    taskId: "task_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskCreateWorkPhaseRequestBody$ {
  /** @deprecated use `TaskCreateWorkPhaseRequestBody$outboundSchema` instead. */
  export const outboundSchema = TaskCreateWorkPhaseRequestBody$outboundSchema;
  /** @deprecated use `TaskCreateWorkPhaseRequestBody$Outbound` instead. */
  export type Outbound = TaskCreateWorkPhaseRequestBody$Outbound;
}

export function taskCreateWorkPhaseRequestBodyToJSON(
  taskCreateWorkPhaseRequestBody: TaskCreateWorkPhaseRequestBody,
): string {
  return JSON.stringify(
    TaskCreateWorkPhaseRequestBody$outboundSchema.parse(
      taskCreateWorkPhaseRequestBody,
    ),
  );
}
