/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type TasksDeleteRequest = {
  id: string;
};

/** @internal */
export type TasksDeleteRequest$Outbound = {
  id: string;
};

/** @internal */
export const TasksDeleteRequest$outboundSchema: z.ZodType<
  TasksDeleteRequest$Outbound,
  z.ZodTypeDef,
  TasksDeleteRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TasksDeleteRequest$ {
  /** @deprecated use `TasksDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = TasksDeleteRequest$outboundSchema;
  /** @deprecated use `TasksDeleteRequest$Outbound` instead. */
  export type Outbound = TasksDeleteRequest$Outbound;
}

export function tasksDeleteRequestToJSON(
  tasksDeleteRequest: TasksDeleteRequest,
): string {
  return JSON.stringify(
    TasksDeleteRequest$outboundSchema.parse(tasksDeleteRequest),
  );
}
