/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TaskResumeRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Task ID or directory (required)
   */
  taskId: string;
};

/**
 * Default Response
 */
export type TaskResumeTasksResponseResponseBody = {
  error?: string | undefined;
  code?: string | undefined;
};

/**
 * Default Response
 */
export type TaskResumeTasksResponseBody = {
  error?: string | undefined;
  code?: string | undefined;
};

/**
 * Default Response
 */
export type TaskResumeResponseBody = {
  success?: boolean | undefined;
  taskId?: string | undefined;
  status?: string | undefined;
  previousStatus?: string | undefined;
};

export type TaskResumeResponse =
  | TaskResumeResponseBody
  | TaskResumeTasksResponseBody
  | TaskResumeTasksResponseResponseBody;

/** @internal */
export type TaskResumeRequestBody$Outbound = {
  workspace_path: string;
  task_id: string;
};

/** @internal */
export const TaskResumeRequestBody$outboundSchema: z.ZodType<
  TaskResumeRequestBody$Outbound,
  z.ZodTypeDef,
  TaskResumeRequestBody
> = z.object({
  workspacePath: z.string(),
  taskId: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
    taskId: "task_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskResumeRequestBody$ {
  /** @deprecated use `TaskResumeRequestBody$outboundSchema` instead. */
  export const outboundSchema = TaskResumeRequestBody$outboundSchema;
  /** @deprecated use `TaskResumeRequestBody$Outbound` instead. */
  export type Outbound = TaskResumeRequestBody$Outbound;
}

export function taskResumeRequestBodyToJSON(
  taskResumeRequestBody: TaskResumeRequestBody,
): string {
  return JSON.stringify(
    TaskResumeRequestBody$outboundSchema.parse(taskResumeRequestBody),
  );
}

/** @internal */
export const TaskResumeTasksResponseResponseBody$inboundSchema: z.ZodType<
  TaskResumeTasksResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  code: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskResumeTasksResponseResponseBody$ {
  /** @deprecated use `TaskResumeTasksResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    TaskResumeTasksResponseResponseBody$inboundSchema;
}

export function taskResumeTasksResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskResumeTasksResponseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TaskResumeTasksResponseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskResumeTasksResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const TaskResumeTasksResponseBody$inboundSchema: z.ZodType<
  TaskResumeTasksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  code: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskResumeTasksResponseBody$ {
  /** @deprecated use `TaskResumeTasksResponseBody$inboundSchema` instead. */
  export const inboundSchema = TaskResumeTasksResponseBody$inboundSchema;
}

export function taskResumeTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskResumeTasksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskResumeTasksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskResumeTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const TaskResumeResponseBody$inboundSchema: z.ZodType<
  TaskResumeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  task_id: z.string().optional(),
  status: z.string().optional(),
  previous_status: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "task_id": "taskId",
    "previous_status": "previousStatus",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskResumeResponseBody$ {
  /** @deprecated use `TaskResumeResponseBody$inboundSchema` instead. */
  export const inboundSchema = TaskResumeResponseBody$inboundSchema;
}

export function taskResumeResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskResumeResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskResumeResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskResumeResponseBody' from JSON`,
  );
}

/** @internal */
export const TaskResumeResponse$inboundSchema: z.ZodType<
  TaskResumeResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => TaskResumeResponseBody$inboundSchema),
  z.lazy(() => TaskResumeTasksResponseBody$inboundSchema),
  z.lazy(() => TaskResumeTasksResponseResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskResumeResponse$ {
  /** @deprecated use `TaskResumeResponse$inboundSchema` instead. */
  export const inboundSchema = TaskResumeResponse$inboundSchema;
}

export function taskResumeResponseFromJSON(
  jsonString: string,
): SafeParseResult<TaskResumeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskResumeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskResumeResponse' from JSON`,
  );
}
