/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type TaskCreateReviewRequest = {
  /**
   * Workspace path
   */
  workspacePath?: string | undefined;
  /**
   * Task directory path (required)
   */
  taskDir: string;
};

/** @internal */
export type TaskCreateReviewRequest$Outbound = {
  workspace_path?: string | undefined;
  task_dir: string;
};

/** @internal */
export const TaskCreateReviewRequest$outboundSchema: z.ZodType<
  TaskCreateReviewRequest$Outbound,
  z.ZodTypeDef,
  TaskCreateReviewRequest
> = z.object({
  workspacePath: z.string().optional(),
  taskDir: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
    taskDir: "task_dir",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskCreateReviewRequest$ {
  /** @deprecated use `TaskCreateReviewRequest$outboundSchema` instead. */
  export const outboundSchema = TaskCreateReviewRequest$outboundSchema;
  /** @deprecated use `TaskCreateReviewRequest$Outbound` instead. */
  export type Outbound = TaskCreateReviewRequest$Outbound;
}

export function taskCreateReviewRequestToJSON(
  taskCreateReviewRequest: TaskCreateReviewRequest,
): string {
  return JSON.stringify(
    TaskCreateReviewRequest$outboundSchema.parse(taskCreateReviewRequest),
  );
}
