/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TaskRetryRequestBody = {
  /**
   * Workspace path (required)
   */
  workspacePath: string;
  /**
   * Task ID or directory (required)
   */
  taskId: string;
};

/**
 * Default Response
 */
export type TaskRetryTasksResponseResponseBody = {
  error?: string | undefined;
  code?: string | undefined;
};

/**
 * Default Response
 */
export type TaskRetryTasksResponseBody = {
  error?: string | undefined;
  code?: string | undefined;
};

/**
 * Default Response
 */
export type TaskRetryResponseBody = {
  success?: boolean | undefined;
  taskId?: string | undefined;
  status?: string | undefined;
  previousStatus?: string | undefined;
};

export type TaskRetryResponse =
  | TaskRetryResponseBody
  | TaskRetryTasksResponseBody
  | TaskRetryTasksResponseResponseBody;

/** @internal */
export type TaskRetryRequestBody$Outbound = {
  workspace_path: string;
  task_id: string;
};

/** @internal */
export const TaskRetryRequestBody$outboundSchema: z.ZodType<
  TaskRetryRequestBody$Outbound,
  z.ZodTypeDef,
  TaskRetryRequestBody
> = z.object({
  workspacePath: z.string(),
  taskId: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspacePath: "workspace_path",
    taskId: "task_id",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskRetryRequestBody$ {
  /** @deprecated use `TaskRetryRequestBody$outboundSchema` instead. */
  export const outboundSchema = TaskRetryRequestBody$outboundSchema;
  /** @deprecated use `TaskRetryRequestBody$Outbound` instead. */
  export type Outbound = TaskRetryRequestBody$Outbound;
}

export function taskRetryRequestBodyToJSON(
  taskRetryRequestBody: TaskRetryRequestBody,
): string {
  return JSON.stringify(
    TaskRetryRequestBody$outboundSchema.parse(taskRetryRequestBody),
  );
}

/** @internal */
export const TaskRetryTasksResponseResponseBody$inboundSchema: z.ZodType<
  TaskRetryTasksResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  code: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskRetryTasksResponseResponseBody$ {
  /** @deprecated use `TaskRetryTasksResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema = TaskRetryTasksResponseResponseBody$inboundSchema;
}

export function taskRetryTasksResponseResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskRetryTasksResponseResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TaskRetryTasksResponseResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskRetryTasksResponseResponseBody' from JSON`,
  );
}

/** @internal */
export const TaskRetryTasksResponseBody$inboundSchema: z.ZodType<
  TaskRetryTasksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  code: z.string().optional(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskRetryTasksResponseBody$ {
  /** @deprecated use `TaskRetryTasksResponseBody$inboundSchema` instead. */
  export const inboundSchema = TaskRetryTasksResponseBody$inboundSchema;
}

export function taskRetryTasksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskRetryTasksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskRetryTasksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskRetryTasksResponseBody' from JSON`,
  );
}

/** @internal */
export const TaskRetryResponseBody$inboundSchema: z.ZodType<
  TaskRetryResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
  task_id: z.string().optional(),
  status: z.string().optional(),
  previous_status: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "task_id": "taskId",
    "previous_status": "previousStatus",
  });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskRetryResponseBody$ {
  /** @deprecated use `TaskRetryResponseBody$inboundSchema` instead. */
  export const inboundSchema = TaskRetryResponseBody$inboundSchema;
}

export function taskRetryResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TaskRetryResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskRetryResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskRetryResponseBody' from JSON`,
  );
}

/** @internal */
export const TaskRetryResponse$inboundSchema: z.ZodType<
  TaskRetryResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => TaskRetryResponseBody$inboundSchema),
  z.lazy(() => TaskRetryTasksResponseBody$inboundSchema),
  z.lazy(() => TaskRetryTasksResponseResponseBody$inboundSchema),
]);
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskRetryResponse$ {
  /** @deprecated use `TaskRetryResponse$inboundSchema` instead. */
  export const inboundSchema = TaskRetryResponse$inboundSchema;
}

export function taskRetryResponseFromJSON(
  jsonString: string,
): SafeParseResult<TaskRetryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskRetryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskRetryResponse' from JSON`,
  );
}
