/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type UserDeleteMeApiKeyRequest = {
  id: string;
};

/** @internal */
export type UserDeleteMeApiKeyRequest$Outbound = {
  id: string;
};

/** @internal */
export const UserDeleteMeApiKeyRequest$outboundSchema: z.ZodType<
  UserDeleteMeApiKeyRequest$Outbound,
  z.ZodTypeDef,
  UserDeleteMeApiKeyRequest
> = z.object({
  id: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserDeleteMeApiKeyRequest$ {
  /** @deprecated use `UserDeleteMeApiKeyRequest$outboundSchema` instead. */
  export const outboundSchema = UserDeleteMeApiKeyRequest$outboundSchema;
  /** @deprecated use `UserDeleteMeApiKeyRequest$Outbound` instead. */
  export type Outbound = UserDeleteMeApiKeyRequest$Outbound;
}

export function userDeleteMeApiKeyRequestToJSON(
  userDeleteMeApiKeyRequest: UserDeleteMeApiKeyRequest,
): string {
  return JSON.stringify(
    UserDeleteMeApiKeyRequest$outboundSchema.parse(userDeleteMeApiKeyRequest),
  );
}
