/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type UserGetRequest = {
  username: string;
};

/** @internal */
export type UserGetRequest$Outbound = {
  username: string;
};

/** @internal */
export const UserGetRequest$outboundSchema: z.ZodType<
  UserGetRequest$Outbound,
  z.ZodTypeDef,
  UserGetRequest
> = z.object({
  username: z.string(),
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserGetRequest$ {
  /** @deprecated use `UserGetRequest$outboundSchema` instead. */
  export const outboundSchema = UserGetRequest$outboundSchema;
  /** @deprecated use `UserGetRequest$Outbound` instead. */
  export type Outbound = UserGetRequest$Outbound;
}

export function userGetRequestToJSON(userGetRequest: UserGetRequest): string {
  return JSON.stringify(UserGetRequest$outboundSchema.parse(userGetRequest));
}
