import {
  CodeIcon,
  FileIcon,
  ImageIcon,
  TableIcon,
  TextIcon,
  VideoIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  ListIcon,
  LinkIcon,
  QuoteIcon,
  MinusIcon,
  AtSignIcon,
  ListCollapseIcon,
  ListOrderedIcon,
  PanelLeftIcon,
  GridIcon,
  TableOfContentsIcon,
  RadicalIcon,
  CheckSquareIcon,
  SmileIcon,
  AlertCircleIcon,
  type LucideIcon,
} from "lucide-react";

export const BLOCK_ICONS: Record<string, LucideIcon> = {
  Paragraph: TextIcon,
  HeadingOne: Heading1Icon,
  HeadingTwo: Heading2Icon,
  HeadingThree: Heading3Icon,
  Code: CodeIcon,
  CodeGroup: CodeIcon,
  Embed: LinkIcon,
  Image: ImageIcon,
  Video: VideoIcon,
  Blockquote: QuoteIcon,
  TodoList: CheckSquareIcon,
  BulletedList: ListIcon,
  NumberedList: ListOrderedIcon,
  Table: TableIcon,
  Callout: AlertCircleIcon,
  File: FileIcon,
  Divider: MinusIcon,
  Accordion: ListCollapseIcon,
  Steps: ListOrderedIcon,
  Tabs: PanelLeftIcon,
  Carousel: GridIcon,
  TableOfContents: TableOfContentsIcon,
  MathBlock: RadicalIcon,
  Emoji: SmileIcon,
  Mention: AtSignIcon,
};

export const BLOCK_CATEGORIES: Record<string, string> = {
  Paragraph: "Basic blocks",
  HeadingOne: "Basic blocks",
  HeadingTwo: "Basic blocks",
  HeadingThree: "Basic blocks",
  TodoList: "Basic blocks",
  BulletedList: "Basic blocks",
  NumberedList: "Basic blocks",
  Blockquote: "Basic blocks",
  Divider: "Basic blocks",
  Callout: "Basic blocks",
  Image: "Media",
  Video: "Media",
  File: "Media",
  Embed: "Media",
  Emoji: "Media",
  Code: "Code",
  CodeGroup: "Code",
  Table: "Advanced",
  Accordion: "Advanced",
  Steps: "Advanced",
  Tabs: "Advanced",
  Carousel: "Advanced",
  TableOfContents: "Advanced",
  MathBlock: "Advanced",
  Mention: "Inline",
};

export const CATEGORY_ORDER = [
  "Basic blocks",
  "Media",
  "Code",
  "Advanced",
  "Inline",
  "Other",
];

export const IS_MAC =
  typeof navigator !== "undefined" && /Mac/.test(navigator.userAgent);

export const MOD_KEY = IS_MAC ? "\u2318" : "Ctrl";
