/**
 * Idea Types
 *
 * Type definitions for the idea module.
 * Based on docs/specs/modules/cli/idea.md
 */

// =============================================================================
// Constants
// =============================================================================

/**
 * Built-in idea types that are shipped with viben
 */
export const BUILTIN_IDEA_TYPES = [
  "code_improvements",
  "code_quality",
  "documentation_gaps",
  "performance_optimizations",
  "security_hardening",
  "ui_ux_improvements",
] as const;

/**
 * Type for built-in idea type names
 */
export type BuiltinIdeaTypeName = (typeof BUILTIN_IDEA_TYPES)[number];

/**
 * Effort levels for ideas
 * Represents the estimated work required to implement an idea
 */
export const EFFORT_LEVELS = [
  "trivial",
  "small",
  "medium",
  "large",
  "complex",
] as const;

/**
 * Type for effort level values
 */
export type EffortLevel = (typeof EFFORT_LEVELS)[number];

/**
 * Idea statuses in the lifecycle
 */
export const IDEA_STATUSES = ["draft", "promoted", "dismissed"] as const;

/**
 * Type for idea status values
 */
export type IdeaStatus = (typeof IDEA_STATUSES)[number];

/**
 * Mapping from effort level to default priority when promoting to task
 */
export const EFFORT_PRIORITY_MAP: Record<EffortLevel, string> = {
  trivial: "low",
  small: "low",
  medium: "medium",
  large: "high",
  complex: "high",
};

/**
 * Default maximum ideas per type
 */
export const DEFAULT_MAX_IDEAS = 5;

/**
 * Ideas output directory relative to .viben
 */
export const IDEAS_DIR = "ideas";

/**
 * Custom idea types directory
 */
export const CUSTOM_IDEA_TYPES_DIR = "docs/idea-types";

/**
 * Idea metadata file name
 */
export const IDEA_JSON_FILE = "idea.json";

/**
 * Idea markdown file prefix
 */
export const IDEA_FILE_PREFIX = "idea_";

// =============================================================================
// Idea Type (Prompt Template)
// =============================================================================

/**
 * Source of an idea type
 */
export type IdeaTypeSource = "builtin" | "custom";

/**
 * Represents an idea type (prompt template)
 *
 * Idea types define how ideas are generated. They can be:
 * - Built-in: shipped with viben in packages/core/src/prompts/idea-types/
 * - Custom: user-defined in docs/idea-types/
 */
export interface IdeaType {
  /** Type identifier (e.g., "code_improvements") */
  name: string;

  /** Human-readable description of this type */
  description: string;

  /** Default maximum ideas to generate for this type */
  maxIdeas?: number;

  /** Whether this is a built-in or custom type */
  source: IdeaTypeSource;

  /** Absolute path to the prompt template file */
  promptPath: string;
}

// =============================================================================
// Idea
// =============================================================================

/**
 * Represents a single idea in an idea_*.md file
 *
 * Ideas are generated by AI based on project analysis.
 * They can be promoted to tasks via `viben idea promote`.
 */
export interface Idea {
  /** Unique identifier - 8-character short UUID (e.g., "a1b2c3d4") */
  id: string;

  /** Type of idea (e.g., "code_improvements") */
  type: string;

  /** File-friendly name for the idea (e.g., "add-pagination-sessions") */
  name?: string;

  /** Short title describing the idea */
  title: string;

  /** Detailed description of the idea */
  description: string;

  /** Why this idea is valuable or needed */
  rationale: string;

  /** Estimated effort to implement */
  estimatedEffort: EffortLevel;

  /** Current status in the lifecycle */
  status: IdeaStatus;

  /** Task ID if this idea was promoted */
  promotedTo?: string;

  /** ISO timestamp when the idea was created */
  createdAt: string;

  // ----- Optional fields depending on idea type -----

  /** Files affected by this idea */
  affectedFiles?: string[];

  /** Existing code patterns that can be referenced */
  existingPatterns?: string[];

  /** Other ideas this builds upon */
  buildsUpon?: string[];

  /** Suggested approach to implement this idea */
  implementationApproach?: string;

  /** Category for organizing ideas */
  category?: string;

  /** Severity level (for security/quality issues) */
  severity?: string;

  /** Target audience (for documentation) */
  targetAudience?: string;

  /** Related documentation links */
  relatedDocs?: string[];

  /** Performance metrics affected */
  metrics?: string[];

  /** UI components affected */
  uiComponents?: string[];

  /** User stories addressed */
  userStories?: string[];
}

/**
 * Raw idea data as parsed from YAML frontmatter
 * Uses snake_case to match the file format
 */
export interface RawIdeaData {
  id: string;
  type: string;
  name?: string;
  title: string;
  description: string;
  rationale: string;
  estimated_effort: string;
  status: string;
  promoted_to?: string | null;
  created_at: string;

  affected_files?: string[];
  existing_patterns?: string[];
  builds_upon?: string[];
  implementation_approach?: string;
  category?: string;
  severity?: string;
  target_audience?: string;
  related_docs?: string[];
  metrics?: string[];
  ui_components?: string[];
  user_stories?: string[];
}

// =============================================================================
// Idea Session
// =============================================================================

/**
 * Summary statistics for an idea session
 */
export interface IdeaSessionSummary {
  /** Total number of ideas generated */
  totalIdeas: number;

  /** Count of ideas by type */
  byType: Record<string, number>;

  /** Count of ideas by status */
  byStatus: Record<IdeaStatus, number>;
}

/**
 * Raw session summary as stored in idea.json
 * Uses snake_case to match the file format
 */
export interface RawIdeaSessionSummary {
  total_ideas: number;
  by_type: Record<string, number>;
  by_status: Record<string, number>;
}

/**
 * Represents an idea session (idea.json metadata)
 *
 * Each idea generation creates a session directory with:
 * - idea.json: session metadata
 * - idea_*.md: ideas for each type
 */
export interface IdeaSession {
  /** Session identifier (e.g., "03-11-api-improvement") */
  id: string;

  /** Types that were generated in this session */
  types: string[];

  /** AI model used for generation */
  model: string;

  /** Summary statistics */
  summary: IdeaSessionSummary;

  /** Generated idea files */
  files?: string[];

  /** ISO timestamp when session was created */
  generatedAt: string;

  /** ISO timestamp when session was last updated */
  updatedAt: string;
}

/**
 * Raw session data as stored in idea.json
 * Uses snake_case to match the file format
 */
export interface RawIdeaSession {
  id: string;
  types: string[];
  model: string;
  summary: RawIdeaSessionSummary;
  files?: string[];
  generated_at: string;
  updated_at: string;
}

// =============================================================================
// Command Options
// =============================================================================

/**
 * Options for generating ideas
 */
export interface IdeaGenerateOptions {
  /** Types of ideas to generate (required) */
  types: string[];

  /** Output directory (default: .viben/ideas/) */
  output?: string;

  /** AI model to use (default: global config) */
  model?: string;

  /** Maximum ideas per type (default: 5) */
  maxIdeas?: number;

  /** Append to existing ideas instead of replacing */
  append?: boolean;

  /** Force regenerate all types */
  override?: boolean;

  /** Output progress as JSON */
  json?: boolean;
}

/**
 * Options for listing ideas
 */
export interface IdeaListOptions {
  /** Filter by idea type */
  type?: string;

  /** Filter by effort level */
  effort?: EffortLevel;

  /** Filter by status */
  status?: IdeaStatus;

  /** Output as JSON */
  json?: boolean;
}

/**
 * Options for promoting an idea to task
 */
export interface IdeaPromoteOptions {
  /** Task slug (default: generated from title) */
  slug?: string;

  /** Task priority (default: mapped from effort) */
  priority?: string;

  /** Task assignee (default: current developer) */
  assignee?: string;

  /** Custom branch name */
  branch?: string;

  /** Agent configuration */
  agent?: string;

  /** Executor type */
  executor?: string;

  /** Model to use */
  model?: string;

  /** Auto-start task */
  start?: boolean;

  /** Run in worktree */
  worktree?: boolean;

  /** Task description override */
  description?: string;

  /** Enable reward computation for FileRL */
  computeReward?: boolean;

  /** FileRL directory absolute path for reward config and output */
  filerlDir?: string;
}

/**
 * Options for removing ideas
 */
export interface IdeaRemoveOptions {
  /** Remove all ideas of this type */
  type?: string;

  /** Remove all ideas */
  all?: boolean;
}

// =============================================================================
// Result Types
// =============================================================================

/**
 * Result of generating ideas for a single type
 */
export interface IdeaGenerateTypeResult {
  /** Type that was generated */
  type: string;

  /** Number of ideas generated */
  count: number;

  /** Path to the output file */
  file: string;

  /** Error message if generation failed */
  error?: string;
}

/**
 * Result of the entire generate command
 */
export interface IdeaGenerateResult {
  /** Session ID */
  sessionId: string;

  /** Session directory path */
  sessionDir: string;

  /** Results for each type */
  typeResults: IdeaGenerateTypeResult[];

  /** All generated ideas */
  ideas: Idea[];

  /** Count by type */
  byType: Record<string, number>;

  /** Errors encountered */
  errors: string[];

  /** Total ideas generated */
  totalIdeas: number;

  /** Whether the operation succeeded */
  success: boolean;
}

/**
 * Result of promoting an idea to a task
 */
export interface IdeaPromoteResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** Original idea ID */
  ideaId?: string;

  /** Idea title */
  ideaTitle?: string;

  /** Created task ID */
  taskId?: string;

  /** Created task directory */
  taskDir?: string;

  /** Task directory name */
  dirName?: string;

  /** Task priority */
  priority?: string;

  /** Task status */
  status?: string;

  /** Whether worktree is enabled */
  worktree?: boolean;

  /** Error message if promotion failed */
  error?: string;
}

/**
 * Result of listing ideas
 */
export interface IdeaListResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** List of ideas */
  ideas: Idea[];

  /** Total count */
  count: number;

  /** Error message if failed */
  error?: string;
}

/**
 * Result of viewing an idea
 */
export interface IdeaViewResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** The idea */
  idea?: Idea;

  /** Session directory containing the idea */
  sessionDir?: string;

  /** File path of the idea */
  filePath?: string;

  /** Error message if failed */
  error?: string;
}

/**
 * Result of removing ideas
 */
export interface IdeaRemoveResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** IDs of removed ideas */
  removed: string[];

  /** Number of ideas removed */
  count: number;

  /** Error message if failed */
  error?: string;
}

/**
 * Result of listing idea types
 */
export interface IdeaListTypesResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** Available idea types */
  types: IdeaType[];

  /** Total count */
  count: number;

  /** Error message if failed */
  error?: string;
}

// =============================================================================
// Idea Type CRUD Types
// =============================================================================

/**
 * Options for creating/updating an idea type
 */
export interface IdeaTypeInput {
  /** Type name (e.g., "code_improvements") - used as filename */
  name: string;

  /** Human-readable description */
  description: string;

  /** Maximum ideas to generate for this type */
  maxIdeas?: number;

  /** Prompt content (markdown body without frontmatter) */
  promptContent: string;
}

/**
 * Result of creating an idea type
 */
export interface IdeaTypeCreateResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** Created idea type */
  ideaType?: IdeaType;

  /** Error message if failed */
  error?: string;
}

/**
 * Result of updating an idea type
 */
export interface IdeaTypeUpdateResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** Updated idea type */
  ideaType?: IdeaType;

  /** Error message if failed */
  error?: string;
}

/**
 * Result of deleting an idea type
 */
export interface IdeaTypeDeleteResult {
  /** Whether the operation succeeded */
  success: boolean;

  /** Deleted type name */
  name?: string;

  /** Error message if failed */
  error?: string;
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Check if a string is a valid effort level
 */
export function isValidEffortLevel(value: string): value is EffortLevel {
  return EFFORT_LEVELS.includes(value as EffortLevel);
}

/**
 * Check if a string is a valid idea status
 */
export function isValidIdeaStatus(value: string): value is IdeaStatus {
  return IDEA_STATUSES.includes(value as IdeaStatus);
}

/**
 * Check if a string is a built-in idea type
 */
export function isBuiltinIdeaType(value: string): value is BuiltinIdeaTypeName {
  return BUILTIN_IDEA_TYPES.includes(value as BuiltinIdeaTypeName);
}

/**
 * Get the default priority for an effort level
 */
export function getDefaultPriority(effort: EffortLevel): string {
  return EFFORT_PRIORITY_MAP[effort];
}

/**
 * Generate idea ID prefix from type name
 *
 * @param typeName - Idea type name
 * @returns Two-letter prefix (e.g., "ci" for code_improvements)
 */
export function getIdeaIdPrefix(typeName: string): string {
  // Take first letter of each word, max 2 letters
  const words = typeName.split("_");
  if (words.length >= 2) {
    return words[0][0] + words[1][0];
  }
  return typeName.slice(0, 2);
}

/**
 * Convert raw idea data from YAML to Idea interface
 */
export function parseRawIdea(raw: RawIdeaData): Idea {
  return {
    id: raw.id,
    type: raw.type,
    name: raw.name,
    title: raw.title,
    description: raw.description,
    rationale: raw.rationale,
    estimatedEffort: isValidEffortLevel(raw.estimated_effort)
      ? raw.estimated_effort
      : "medium",
    status: isValidIdeaStatus(raw.status) ? raw.status : "draft",
    promotedTo: raw.promoted_to || undefined,
    createdAt: raw.created_at,
    affectedFiles: raw.affected_files,
    existingPatterns: raw.existing_patterns,
    buildsUpon: raw.builds_upon,
    implementationApproach: raw.implementation_approach,
    category: raw.category,
    severity: raw.severity,
    targetAudience: raw.target_audience,
    relatedDocs: raw.related_docs,
    metrics: raw.metrics,
    uiComponents: raw.ui_components,
    userStories: raw.user_stories,
  };
}

/**
 * Convert raw session data from JSON to IdeaSession interface
 */
export function parseRawSession(raw: RawIdeaSession): IdeaSession {
  return {
    id: raw.id,
    types: raw.types,
    model: raw.model,
    summary: {
      totalIdeas: raw.summary.total_ideas,
      byType: raw.summary.by_type,
      byStatus: {
        draft: raw.summary.by_status.draft || 0,
        promoted: raw.summary.by_status.promoted || 0,
        dismissed: raw.summary.by_status.dismissed || 0,
      },
    },
    files: raw.files,
    generatedAt: raw.generated_at,
    updatedAt: raw.updated_at,
  };
}

/**
 * Generate a short UUID (8 characters)
 */
export function generateShortUuid(): string {
  return crypto.randomUUID().replace(/-/g, "").substring(0, 8);
}
