export const EXHAUSTIVE_MARKDOWN_SAMPLE = [
  "---",
  "page:",
  "  type: markdown",
  "  permission: [read, write]",
  "name: editor_plugin_roundtrip_lab",
  "page_width: full",
  "show_toc: true",
  "sync_mode: markdown_approx_yoopta",
  "tags:",
  "  - editor",
  "  - markdown",
  "  - roundtrip",
  "---",
  "[TOC]",
  "",
  "# Viben Editor 插件全量演示",
  "",
  "这个样例用于验证 `markdown ≈ serializeMarkdown(editor, deserializeMarkdown(editor, markdown))`。它覆盖纯 Markdown 能表达的核心块，也标注了从纯 Markdown 回流时会退化为普通块的插件形态。",
  "",
  "内联内容包含 **bold 加粗**、*italic 斜体*、~~strike 删除线~~、<u>underline 下划线</u>、<mark>highlight 高亮 HTML</mark>、`inline_code()`、[内部链接](pages/example-page/SKILL.md)、[外部链接](https://yoopta.dev)、直接 emoji 🚀、用户提及 <span data-mention data-mention-id=\"user-1\" data-mention-name=\"You\" data-mention-type=\"user\">@You</span>、页面提及文本 #editor-example，以及内联数学 $E = mc^2$。",
  "",
  "## 标题层级与段落",
  "",
  "### 第三级标题",
  "",
  "长段落用于测试视觉行和跨 block 光标移动。请把光标放在这一段最后一行中间，然后按 ArrowDown，右侧光标应该进入下一个 block 第一行的相近水平位置，而不是先跳到当前行尾。",
  "",
  "> Blockquote：这是标准引用块，Markdown 可以稳定表达。",
  "",
  "<dl data-theme=\"info\">Callout 插件：这里使用 Yoopta 支持的 HTML passthrough，因此初始导入后就是一个真实 Callout block。序列化回 Markdown 时会变成引用语法。</dl>",
  "",
  "## 列表插件",
  "",
  "- BulletedList 项目 A",
  "- BulletedList 项目 B，包含 **粗体** 和 `code`",
  "  - 嵌套 bullet，用于验证缩进稳定性",
  "",
  "1. NumberedList 第一步",
  "2. NumberedList 第二步",
  "3. NumberedList 第三步",
  "",
  "- [ ] TodoList 未完成事项",
  "- [x] TodoList 已完成事项",
  "",
  "## Steps 插件的 Markdown 近似",
  "",
  "1. **收集输入**",
  "   从左侧 Monaco Markdown 读取文本。",
  "2. **解析为 blocks**",
  "   使用 `deserializeMarkdown` 写入 Yoopta editor。",
  "3. **导出 Markdown**",
  "   右侧修改后通过 `serializeMarkdown` 同步回左侧。",
  "",
  "## 代码与 CodeGroup 插件",
  "",
  "```ts",
  "type SyncDirection = \"markdown_to_editor\" | \"editor_to_markdown\";",
  "",
  "function normalize(value: string) {",
  "  return value.trim();",
  "}",
  "```",
  "",
  "```bash",
  "pnpm --filter @viben/editor-example dev",
  "pnpm --filter @viben/editor test",
  "```",
  "",
  "<div data-type=\"code-group-container\" data-theme=\"github-dark\">",
  "<div style=\"display: flex; background: #1e293b;\">",
  "<button data-tab-id=\"cg-ts\">sync.ts</button>",
  "<button data-tab-id=\"cg-sh\">verify.sh</button>",
  "</div>",
  "<pre data-tab-content-id=\"cg-ts\" data-language=\"typescript\"><code>export const syncDirection = \"markdown_to_editor\";",
  "export const debounceMs = 90;</code></pre>",
  "<pre data-tab-content-id=\"cg-sh\" data-language=\"bash\"><code>pnpm --filter @viben/editor exec vitest run",
  "pnpm --filter @viben/editor-example build</code></pre>",
  "</div>",
  "",
  "## Table 插件",
  "",
  "| Plugin | Markdown form | Roundtrip note |",
  "| --- | --- | --- |",
  "| Paragraph | plain text | exact |",
  "| Table | pipe table | basic GFM table only |",
  "| Tabs | headings | lossy from pure markdown |",
  "| Carousel | ordered items | lossy from pure markdown |",
  "",
  "## 媒体与链接类插件",
  "",
  "![Image plugin sample](https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop)",
  "",
  "[editor-spec.pdf](https://example.com/editor-spec.pdf)",
  "",
  "<div data-yoopta-embed data-provider=\"youtube\">",
  "<iframe src=\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\" width=\"650\" height=\"366\" frameborder=\"0\" allowfullscreen></iframe>",
  "</div>",
  "",
  "![https://example.com/demo-video.mp4](https://example.com/demo-video.mp4)",
  "",
  "## Accordion 插件 HTML passthrough",
  "",
  "<details>",
  "<summary>为什么这里使用 HTML?</summary>",
  "<p>Accordion 可以通过 details/summary/p 的 HTML 形式稳定导入导出。</p>",
  "</details>",
  "",
  "<details>",
  "<summary>第二个折叠项</summary>",
  "<p>这里包含 **Markdown 标记文本**，导入后会按 HTML 内容处理。</p>",
  "</details>",
  "",
  "## Tabs 插件",
  "",
  "<div data-type=\"tabs-container\">",
  "<div style=\"display: flex; border-bottom: 1px solid #e5e7eb;\">",
  "<button data-tab-id=\"tab-overview\">Overview</button>",
  "<button data-tab-id=\"tab-api\">API</button>",
  "</div>",
  "<div data-tab-content-id=\"tab-overview\">Tabs 插件：初始导入为真实 Tabs block，右侧切换和编辑后会同步回左侧。</div>",
  "<div data-tab-content-id=\"tab-api\">createYooptaPlugins(), deserializeMarkdown(), serializeMarkdown()</div>",
  "</div>",
  "",
  "## Steps 插件",
  "",
  "<div data-type=\"steps-container\">",
  "<div><h4>收集输入</h4><p>从左侧 Monaco Markdown 读取文本。</p></div>",
  "<div><h4>解析为 blocks</h4><p>使用 deserializeMarkdown 写入 Yoopta editor。</p></div>",
  "<div><h4>导出 Markdown</h4><p>右侧修改后通过 serializeMarkdown 同步回左侧。</p></div>",
  "</div>",
  "",
  "## Carousel 插件",
  "",
  "<div>",
  "<div style=\"display: flex; padding: 8px 0;\">",
  "<div style=\"flex: 0 0 auto; width: 200px; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; margin-right: 16px;\">Carousel slide: 需求梳理</div>",
  "<div style=\"flex: 0 0 auto; width: 200px; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; margin-right: 16px;\">Carousel slide: markdown_to_editor 动画同步</div>",
  "<div style=\"flex: 0 0 auto; width: 200px; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; margin-right: 16px;\">Carousel slide: editor_to_markdown 语法高亮同步</div>",
  "</div>",
  "</div>",
  "",
  "## 数学插件",
  "",
  "$$",
  "\\int_0^\\infty e^{-x} dx = 1",
  "$$",
  "",
  "## 分隔线",
  "",
  "---",
  "",
  "## 右侧可创建的富 blocks",
  "",
  "右侧 slash menu 还可以直接创建真实的 Callout、CodeGroup、Embed、File、Video、Tabs、Steps、Carousel、Mention、Emoji、MathInline、MathBlock 和 TableOfContents。左侧会同步显示它们当前可序列化的 Markdown 形式；其中部分结构是 lossy，这是 Markdown 表达能力的限制，不是同步失败。",
  "",
  "最后一段用于空白区域点击测试。清空左侧全部内容后，右侧应该展示空白页面，并且点击任何空白位置都会创建或聚焦 Paragraph 输入框。",
].join("\n");
