import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  backendSidebar: [
    'index',
    'directory-structure',
    'database-guidelines',
    'error-handling',
    'logging-guidelines',
    'api-module',
    'quality-guidelines',
    'telemetry-guidelines',
    {
      type: 'category',
      label: 'Gateway',
      collapsed: false,
      items: [
        'gateway/index',
        'gateway/agents',
        'gateway/channels',
        'gateway/chat-list',
        'gateway/cron',
        'gateway/events',
        'gateway/executors',
        'gateway/group-chats',
        'gateway/health',
        'gateway/models',
        'gateway/providers',
        'gateway/sessions',
        'gateway/tasks',
        'gateway/websocket',
        'gateway/task',
        'gateway/queue',
        'gateway/idea',
        'gateway/kanban-api',
        'gateway/telemetry',
        'gateway/resource-api',
        'gateway/sse-streaming',
        'gateway/background-tasks',
        'gateway/group-chat-design',
        'gateway/workspace-management',
        'gateway/session-persistence',
        'gateway/queue-auto-promotion',
        'gateway/sandbox',
        'gateway/agent-hooks',
      ],
    },
    {
      type: 'category',
      label: 'Kanban',
      collapsed: false,
      items: [
        'kanban/index',
        'kanban/tasks',
        'kanban/sessions',
        'kanban/workspaces',
        'kanban/projects',
        'kanban/storage',
        'kanban/git-operations',
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: [
        'api/index',
        'api/mcp-api',
        'api/skill-api',
        'api/user-api',
        'api/social-api',
        'api/collections-api',
        'api/packages',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      items: [
        'modules/auth',
        'modules/database',
        'modules/storage',
        'modules/project-setup',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsed: false,
      items: [
        'deployment/vercel',
        'deployment/github-oauth',
      ],
    },
    {
      type: 'link',
      label: 'Shared Docs',
      href: '/shared/',
    },
  ],
};

export default sidebars;
