import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["cjs", "esm"],
  dts: {
    resolve: true,
  },
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    "@yoopta/accordion",
    "@yoopta/blockquote",
    "@yoopta/callout",
    "@yoopta/carousel",
    "@yoopta/code",
    "@yoopta/divider",
    "@yoopta/editor",
    "@yoopta/embed",
    "@yoopta/emoji",
    "@yoopta/exports",
    "@yoopta/file",
    "@yoopta/headings",
    "@yoopta/image",
    "@yoopta/link",
    "@yoopta/lists",
    "@yoopta/marks",
    "@yoopta/math",
    "@yoopta/mention",
    "@yoopta/paragraph",
    "@yoopta/steps",
    "@yoopta/table",
    "@yoopta/table-of-contents",
    "@yoopta/tabs",
    "@yoopta/themes-shadcn",
    "@yoopta/ui",
    "@yoopta/ui/block-dnd",
    "@yoopta/ui/floating-toolbar",
    "@yoopta/ui/highlight-color-picker",
    "@yoopta/ui/selection-box",
    "@yoopta/themes-shadcn/emoji",
    "@yoopta/themes-shadcn/mention",
    "@yoopta/video",
    "i18next",
    "lucide-react",
    "react",
    "react-dom",
    "react-i18next",
    "slate",
    "slate-react",
  ],
  treeshake: true,
});
