/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentApprove } from "../funcs/agentApprove.js";
import { agentCreate } from "../funcs/agentCreate.js";
import { agentCreateAnswer } from "../funcs/agentCreateAnswer.js";
import { agentCreateSession } from "../funcs/agentCreateSession.js";
import { agentCreateSessionMessage } from "../funcs/agentCreateSessionMessage.js";
import { agentCreateSessionSteer } from "../funcs/agentCreateSessionSteer.js";
import { agentCreateTemplate } from "../funcs/agentCreateTemplate.js";
import { agentDelete } from "../funcs/agentDelete.js";
import { agentDeleteSession } from "../funcs/agentDeleteSession.js";
import { agentGet } from "../funcs/agentGet.js";
import { agentGetAvailability } from "../funcs/agentGetAvailability.js";
import { agentGetDefault } from "../funcs/agentGetDefault.js";
import { agentGetPlan } from "../funcs/agentGetPlan.js";
import { agentGetSession } from "../funcs/agentGetSession.js";
import { agentGetSession2 } from "../funcs/agentGetSession2.js";
import { agentGetSessionMessages } from "../funcs/agentGetSessionMessages.js";
import { agentGetSessions } from "../funcs/agentGetSessions.js";
import { agentGetSessionTaskMessages } from "../funcs/agentGetSessionTaskMessages.js";
import { agentGetSessionTasks } from "../funcs/agentGetSessionTasks.js";
import { agentGetSessionUiMessages } from "../funcs/agentGetSessionUiMessages.js";
import { agentGetTasks } from "../funcs/agentGetTasks.js";
import { agentGetTemplate } from "../funcs/agentGetTemplate.js";
import { agentInstantiateTemplate } from "../funcs/agentInstantiateTemplate.js";
import { agentList } from "../funcs/agentList.js";
import { agentListTemplates } from "../funcs/agentListTemplates.js";
import { agentPromote } from "../funcs/agentPromote.js";
import { agentReject } from "../funcs/agentReject.js";
import { agentRun } from "../funcs/agentRun.js";
import { agentStop } from "../funcs/agentStop.js";
import { agentStopTask } from "../funcs/agentStopTask.js";
import { agentSubscribeTask } from "../funcs/agentSubscribeTask.js";
import { agentUpdate } from "../funcs/agentUpdate.js";
import { agentUpdateDefault } from "../funcs/agentUpdateDefault.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Agent extends ClientSDK {
  /**
   * List all agents
   */
  async list(
    request?: operations.AgentListRequest | undefined,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<operations.AgentListResponseBody> {
    return unwrapAsync(agentList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new custom idea type
   */
  async create(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentCreate(
      this,
      options,
    ));
  }

  async getDefault(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetDefault(
      this,
      options,
    ));
  }

  async updateDefault(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentUpdateDefault(
      this,
      options,
    ));
  }

  async listTemplates(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentListTemplates(
      this,
      options,
    ));
  }

  /**
   * List available page templates
   */
  async createTemplate(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentCreateTemplate(
      this,
      options,
    ));
  }

  async getTemplate(
    request: operations.AgentGetTemplateRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetTemplate(
      this,
      request,
      options,
    ));
  }

  async instantiateTemplate(
    request: operations.AgentInstantiateTemplateRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentInstantiateTemplate(
      this,
      request,
      options,
    ));
  }

  /**
   * Promote an idea to a task
   */
  async promote(
    request: operations.AgentPromoteRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentPromote(
      this,
      request,
      options,
    ));
  }

  async getSessions(
    request: operations.AgentGetSessionsRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetSessions(
      this,
      request,
      options,
    ));
  }

  async createSession(
    request: operations.AgentCreateSessionRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentCreateSession(
      this,
      request,
      options,
    ));
  }

  async getSession(
    request: operations.AgentGetSessionRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetSession(
      this,
      request,
      options,
    ));
  }

  async deleteSession(
    request: operations.AgentDeleteSessionRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentDeleteSession(
      this,
      request,
      options,
    ));
  }

  async getSessionMessages(
    request: operations.AgentGetSessionMessagesRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetSessionMessages(
      this,
      request,
      options,
    ));
  }

  async createSessionMessage(
    request: operations.AgentCreateSessionMessageRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentCreateSessionMessage(
      this,
      request,
      options,
    ));
  }

  async getSessionUiMessages(
    request: operations.AgentGetSessionUiMessagesRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetSessionUiMessages(
      this,
      request,
      options,
    ));
  }

  async getAvailability(
    request: operations.AgentGetAvailabilityRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetAvailability(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific model by ID
   */
  async get(
    request: operations.AgentGetRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a single idea by ID
   */
  async delete(
    request: operations.AgentDeleteRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing idea type
   */
  async update(
    request: operations.AgentUpdateRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentUpdate(
      this,
      request,
      options,
    ));
  }

  async getTasks(
    request: operations.AgentGetTasksRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetTasks(
      this,
      request,
      options,
    ));
  }

  async getSessionTasks(
    request: operations.AgentGetSessionTasksRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetSessionTasks(
      this,
      request,
      options,
    ));
  }

  async getSessionTaskMessages(
    request: operations.AgentGetSessionTaskMessagesRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetSessionTaskMessages(
      this,
      request,
      options,
    ));
  }

  async run(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentRun(
      this,
      options,
    ));
  }

  /**
   * Stop a Vite preview server
   */
  async stop(
    request: operations.AgentStopRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentStop(
      this,
      request,
      options,
    ));
  }

  async approve(
    request: operations.AgentApproveRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentApprove(
      this,
      request,
      options,
    ));
  }

  async reject(
    request: operations.AgentRejectRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentReject(
      this,
      request,
      options,
    ));
  }

  async createAnswer(
    request: operations.AgentCreateAnswerRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentCreateAnswer(
      this,
      request,
      options,
    ));
  }

  async subscribeTask(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentSubscribeTask(
      this,
      options,
    ));
  }

  async stopTask(
    request: operations.AgentStopTaskRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentStopTask(
      this,
      request,
      options,
    ));
  }

  async getSession2(
    request: operations.AgentGetSession2Request,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetSession2(
      this,
      request,
      options,
    ));
  }

  async createSessionSteer(
    request: operations.AgentCreateSessionSteerRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentCreateSessionSteer(
      this,
      request,
      options,
    ));
  }

  async getPlan(
    request: operations.AgentGetPlanRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(agentGetPlan(
      this,
      request,
      options,
    ));
  }
}
