/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { channelsCreate } from "../funcs/channelsCreate.js";
import { channelsCreateDefault } from "../funcs/channelsCreateDefault.js";
import { channelsCreateSendTest } from "../funcs/channelsCreateSendTest.js";
import { channelsCreateWebhook } from "../funcs/channelsCreateWebhook.js";
import { channelsCreateWebhook2 } from "../funcs/channelsCreateWebhook2.js";
import { channelsDelete } from "../funcs/channelsDelete.js";
import { channelsGet } from "../funcs/channelsGet.js";
import { channelsList } from "../funcs/channelsList.js";
import { channelsSend } from "../funcs/channelsSend.js";
import { channelsTest } from "../funcs/channelsTest.js";
import { channelsUpdate } from "../funcs/channelsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Channels extends ClientSDK {
  /**
   * List all notification channels
   */
  async list(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<operations.ChannelsListResponseBody> {
    return unwrapAsync(channelsList(
      this,
      options,
    ));
  }

  /**
   * Create a new custom idea type
   */
  async create(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(channelsCreate(
      this,
      options,
    ));
  }

  /**
   * Get a specific channel by ID
   */
  async get(
    request: operations.ChannelsGetRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<operations.ChannelsGetResponse> {
    return unwrapAsync(channelsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a single idea by ID
   */
  async delete(
    request: operations.ChannelsDeleteRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(channelsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing idea type
   */
  async update(
    request: operations.ChannelsUpdateRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(channelsUpdate(
      this,
      request,
      options,
    ));
  }

  async createDefault(
    request: operations.ChannelsCreateDefaultRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(channelsCreateDefault(
      this,
      request,
      options,
    ));
  }

  async send(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(channelsSend(
      this,
      options,
    ));
  }

  async test(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(channelsTest(
      this,
      options,
    ));
  }

  async createSendTest(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(channelsCreateSendTest(
      this,
      options,
    ));
  }

  async createWebhook(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(channelsCreateWebhook(
      this,
      options,
    ));
  }

  async createWebhook2(
    request: operations.ChannelsCreateWebhook2Request,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(channelsCreateWebhook2(
      this,
      request,
      options,
    ));
  }
}
