/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectionsCreate } from "../funcs/collectionsCreate.js";
import { collectionsCreateComment } from "../funcs/collectionsCreateComment.js";
import { collectionsCreateFavorite } from "../funcs/collectionsCreateFavorite.js";
import { collectionsCreateFork } from "../funcs/collectionsCreateFork.js";
import { collectionsCreateItem } from "../funcs/collectionsCreateItem.js";
import { collectionsDelete } from "../funcs/collectionsDelete.js";
import { collectionsDeleteItem } from "../funcs/collectionsDeleteItem.js";
import { collectionsGet } from "../funcs/collectionsGet.js";
import { collectionsGetComments } from "../funcs/collectionsGetComments.js";
import { collectionsList } from "../funcs/collectionsList.js";
import { collectionsUpdate } from "../funcs/collectionsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Collections extends ClientSDK {
  /**
   * List all agents
   */
  async list(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsList(
      this,
      options,
    ));
  }

  /**
   * Create a new custom idea type
   */
  async create(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsCreate(
      this,
      options,
    ));
  }

  /**
   * Get a specific model by ID
   */
  async get(
    request: operations.CollectionsGetRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a single idea by ID
   */
  async delete(
    request: operations.CollectionsDeleteRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing idea type
   */
  async update(
    request: operations.CollectionsUpdateRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsUpdate(
      this,
      request,
      options,
    ));
  }

  async createItem(
    request: operations.CollectionsCreateItemRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsCreateItem(
      this,
      request,
      options,
    ));
  }

  async deleteItem(
    request: operations.CollectionsDeleteItemRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsDeleteItem(
      this,
      request,
      options,
    ));
  }

  async createFork(
    request: operations.CollectionsCreateForkRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsCreateFork(
      this,
      request,
      options,
    ));
  }

  /**
   * Toggle favorite for a marketplace skill
   */
  async createFavorite(
    request: operations.CollectionsCreateFavoriteRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsCreateFavorite(
      this,
      request,
      options,
    ));
  }

  async getComments(
    request: operations.CollectionsGetCommentsRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsGetComments(
      this,
      request,
      options,
    ));
  }

  async createComment(
    request: operations.CollectionsCreateCommentRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(collectionsCreateComment(
      this,
      request,
      options,
    ));
  }
}
