/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commandsListSkills } from "../funcs/commandsListSkills.js";
import { commandsListWorkspace } from "../funcs/commandsListWorkspace.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "./types/fp.js";

export class Commands extends ClientSDK {
  async listWorkspace(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(commandsListWorkspace(
      this,
      options,
    ));
  }

  async listSkills(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(commandsListSkills(
      this,
      options,
    ));
  }
}
