/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { executorsGetApiExecutors } from "../funcs/executorsGetApiExecutors.js";
import { executorsGetApiExecutorsOpenclawRuntimeConfig } from "../funcs/executorsGetApiExecutorsOpenclawRuntimeConfig.js";
import { executorsPostApiExecutorsOpenclawTestConnection } from "../funcs/executorsPostApiExecutorsOpenclawTestConnection.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Executors extends ClientSDK {
  /**
   * List available executors
   */
  async getApiExecutors(
    request?: operations.GetApiExecutorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetApiExecutorsResponseBody> {
    return unwrapAsync(executorsGetApiExecutors(
      this,
      request,
      options,
    ));
  }

  /**
   * Get the effective OpenClaw gateway config from the server side
   */
  async getApiExecutorsOpenclawRuntimeConfig(
    options?: RequestOptions,
  ): Promise<operations.GetApiExecutorsOpenclawRuntimeConfigResponseBody> {
    return unwrapAsync(executorsGetApiExecutorsOpenclawRuntimeConfig(
      this,
      options,
    ));
  }

  /**
   * Test connection to an OpenClaw gateway with device auth handshake
   */
  async postApiExecutorsOpenclawTestConnection(
    request: operations.PostApiExecutorsOpenclawTestConnectionRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostApiExecutorsOpenclawTestConnectionResponseBody> {
    return unwrapAsync(executorsPostApiExecutorsOpenclawTestConnection(
      this,
      request,
      options,
    ));
  }
}
