/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupChatsCreate } from "../funcs/groupChatsCreate.js";
import { groupChatsCreateFile } from "../funcs/groupChatsCreateFile.js";
import { groupChatsCreateMember } from "../funcs/groupChatsCreateMember.js";
import { groupChatsCreatePicture } from "../funcs/groupChatsCreatePicture.js";
import { groupChatsCreateSession } from "../funcs/groupChatsCreateSession.js";
import { groupChatsCreateSessionMessage } from "../funcs/groupChatsCreateSessionMessage.js";
import { groupChatsDelete } from "../funcs/groupChatsDelete.js";
import { groupChatsDeleteFile } from "../funcs/groupChatsDeleteFile.js";
import { groupChatsDeleteMember } from "../funcs/groupChatsDeleteMember.js";
import { groupChatsDeletePicture } from "../funcs/groupChatsDeletePicture.js";
import { groupChatsDeleteSession } from "../funcs/groupChatsDeleteSession.js";
import { groupChatsGet } from "../funcs/groupChatsGet.js";
import { groupChatsGetFile } from "../funcs/groupChatsGetFile.js";
import { groupChatsGetFiles } from "../funcs/groupChatsGetFiles.js";
import { groupChatsGetMembers } from "../funcs/groupChatsGetMembers.js";
import { groupChatsGetPicture } from "../funcs/groupChatsGetPicture.js";
import { groupChatsGetPictures } from "../funcs/groupChatsGetPictures.js";
import { groupChatsGetSession } from "../funcs/groupChatsGetSession.js";
import { groupChatsGetSessionAgents } from "../funcs/groupChatsGetSessionAgents.js";
import { groupChatsGetSessionMessages } from "../funcs/groupChatsGetSessionMessages.js";
import { groupChatsGetSessions } from "../funcs/groupChatsGetSessions.js";
import { groupChatsList } from "../funcs/groupChatsList.js";
import { groupChatsUpdate } from "../funcs/groupChatsUpdate.js";
import { groupChatsUpdateSession } from "../funcs/groupChatsUpdateSession.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class GroupChats extends ClientSDK {
  async list(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsList(
      this,
      options,
    ));
  }

  async create(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsCreate(
      this,
      options,
    ));
  }

  async get(
    request: operations.GroupChatsGetRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGet(
      this,
      request,
      options,
    ));
  }

  async delete(
    request: operations.GroupChatsDeleteRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsDelete(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.GroupChatsUpdateRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsUpdate(
      this,
      request,
      options,
    ));
  }

  async getMembers(
    request: operations.GroupChatsGetMembersRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGetMembers(
      this,
      request,
      options,
    ));
  }

  async createMember(
    request: operations.GroupChatsCreateMemberRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsCreateMember(
      this,
      request,
      options,
    ));
  }

  async deleteMember(
    request: operations.GroupChatsDeleteMemberRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsDeleteMember(
      this,
      request,
      options,
    ));
  }

  async getSessions(
    request: operations.GroupChatsGetSessionsRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGetSessions(
      this,
      request,
      options,
    ));
  }

  async createSession(
    request: operations.GroupChatsCreateSessionRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsCreateSession(
      this,
      request,
      options,
    ));
  }

  async getSession(
    request: operations.GroupChatsGetSessionRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGetSession(
      this,
      request,
      options,
    ));
  }

  async deleteSession(
    request: operations.GroupChatsDeleteSessionRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsDeleteSession(
      this,
      request,
      options,
    ));
  }

  async updateSession(
    request: operations.GroupChatsUpdateSessionRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsUpdateSession(
      this,
      request,
      options,
    ));
  }

  async getSessionAgents(
    request: operations.GroupChatsGetSessionAgentsRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGetSessionAgents(
      this,
      request,
      options,
    ));
  }

  async getFiles(
    request: operations.GroupChatsGetFilesRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGetFiles(
      this,
      request,
      options,
    ));
  }

  async createFile(
    request: operations.GroupChatsCreateFileRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsCreateFile(
      this,
      request,
      options,
    ));
  }

  async getFile(
    request: operations.GroupChatsGetFileRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGetFile(
      this,
      request,
      options,
    ));
  }

  async deleteFile(
    request: operations.GroupChatsDeleteFileRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsDeleteFile(
      this,
      request,
      options,
    ));
  }

  async getPictures(
    request: operations.GroupChatsGetPicturesRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGetPictures(
      this,
      request,
      options,
    ));
  }

  async createPicture(
    request: operations.GroupChatsCreatePictureRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsCreatePicture(
      this,
      request,
      options,
    ));
  }

  async getPicture(
    request: operations.GroupChatsGetPictureRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGetPicture(
      this,
      request,
      options,
    ));
  }

  async deletePicture(
    request: operations.GroupChatsDeletePictureRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsDeletePicture(
      this,
      request,
      options,
    ));
  }

  async getSessionMessages(
    request: operations.GroupChatsGetSessionMessagesRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsGetSessionMessages(
      this,
      request,
      options,
    ));
  }

  async createSessionMessage(
    request: operations.GroupChatsCreateSessionMessageRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(groupChatsCreateSessionMessage(
      this,
      request,
      options,
    ));
  }
}
