/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { historyCreate } from "../funcs/historyCreate.js";
import { historyDelete } from "../funcs/historyDelete.js";
import { historyDelete2 } from "../funcs/historyDelete2.js";
import { historyGet } from "../funcs/historyGet.js";
import { historyList } from "../funcs/historyList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class History extends ClientSDK {
  /**
   * List all models
   */
  async list(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(historyList(
      this,
      options,
    ));
  }

  /**
   * Create a new custom idea type
   */
  async create(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(historyCreate(
      this,
      options,
    ));
  }

  /**
   * Remove ideas by type or all ideas
   */
  async delete2(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(historyDelete2(
      this,
      options,
    ));
  }

  /**
   * Get a specific model by ID
   */
  async get(
    request: operations.HistoryGetRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(historyGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a single idea by ID
   */
  async delete(
    request: operations.HistoryDeleteRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(historyDelete(
      this,
      request,
      options,
    ));
  }
}
