/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { kanbanGetApiKanbanTasksTaskIdActivities } from "../funcs/kanbanGetApiKanbanTasksTaskIdActivities.js";
import { kanbanGetApiKanbanTasksTaskIdComments } from "../funcs/kanbanGetApiKanbanTasksTaskIdComments.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Kanban extends ClientSDK {
  /**
   * Get all activities for a task
   */
  async getApiKanbanTasksTaskIdActivities(
    request: operations.GetApiKanbanTasksTaskIdActivitiesRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.ResponseBody>> {
    return unwrapAsync(kanbanGetApiKanbanTasksTaskIdActivities(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all comments for a task
   */
  async getApiKanbanTasksTaskIdComments(
    request: operations.GetApiKanbanTasksTaskIdCommentsRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.GetApiKanbanTasksTaskIdCommentsResponseBody>> {
    return unwrapAsync(kanbanGetApiKanbanTasksTaskIdComments(
      this,
      request,
      options,
    ));
  }
}
