/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { kanbanCreateTaskActivity } from "../funcs/kanbanCreateTaskActivity.js";
import { kanbanCreateTaskComment } from "../funcs/kanbanCreateTaskComment.js";
import { kanbanCreateTaskCommentReaction } from "../funcs/kanbanCreateTaskCommentReaction.js";
import { kanbanDeleteTaskComment } from "../funcs/kanbanDeleteTaskComment.js";
import { kanbanDeleteTaskData } from "../funcs/kanbanDeleteTaskData.js";
import { kanbanGetTaskActivities } from "../funcs/kanbanGetTaskActivities.js";
import { kanbanGetTaskComments } from "../funcs/kanbanGetTaskComments.js";
import { kanbanUpdateTaskComment } from "../funcs/kanbanUpdateTaskComment.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Kanban extends ClientSDK {
  /**
   * Get all comments for a task
   */
  async getTaskComments(
    request: operations.KanbanGetTaskCommentsRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<Array<operations.ResponseBody>> {
    return unwrapAsync(kanbanGetTaskComments(
      this,
      request,
      options,
    ));
  }

  async createTaskComment(
    request: operations.KanbanCreateTaskCommentRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(kanbanCreateTaskComment(
      this,
      request,
      options,
    ));
  }

  async deleteTaskComment(
    request: operations.KanbanDeleteTaskCommentRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(kanbanDeleteTaskComment(
      this,
      request,
      options,
    ));
  }

  async updateTaskComment(
    request: operations.KanbanUpdateTaskCommentRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(kanbanUpdateTaskComment(
      this,
      request,
      options,
    ));
  }

  async createTaskCommentReaction(
    request: operations.KanbanCreateTaskCommentReactionRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(kanbanCreateTaskCommentReaction(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all activities for a task
   */
  async getTaskActivities(
    request: operations.KanbanGetTaskActivitiesRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<Array<operations.KanbanGetTaskActivitiesResponseBody>> {
    return unwrapAsync(kanbanGetTaskActivities(
      this,
      request,
      options,
    ));
  }

  async createTaskActivity(
    request: operations.KanbanCreateTaskActivityRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(kanbanCreateTaskActivity(
      this,
      request,
      options,
    ));
  }

  async deleteTaskData(
    request: operations.KanbanDeleteTaskDataRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(kanbanDeleteTaskData(
      this,
      request,
      options,
    ));
  }
}
