/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpGetApiMcpInfoIdOrSlug } from "../funcs/mcpGetApiMcpInfoIdOrSlug.js";
import { mcpGetApiMcpInstalled } from "../funcs/mcpGetApiMcpInstalled.js";
import { mcpGetApiMcpList } from "../funcs/mcpGetApiMcpList.js";
import { mcpGetApiMcpSearch } from "../funcs/mcpGetApiMcpSearch.js";
import { mcpGetApiMcpShowName } from "../funcs/mcpGetApiMcpShowName.js";
import { mcpGetApiMcpTauriStatus } from "../funcs/mcpGetApiMcpTauriStatus.js";
import { mcpPostApiMcpDownload } from "../funcs/mcpPostApiMcpDownload.js";
import { mcpPostApiMcpInstall } from "../funcs/mcpPostApiMcpInstall.js";
import { mcpPostApiMcpUninstall } from "../funcs/mcpPostApiMcpUninstall.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Mcp extends ClientSDK {
  /**
   * Get MCP package details from marketplace
   */
  async getApiMcpInfoIdOrSlug(
    request: operations.GetApiMcpInfoIdOrSlugRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiMcpInfoIdOrSlugResponse> {
    return unwrapAsync(mcpGetApiMcpInfoIdOrSlug(
      this,
      request,
      options,
    ));
  }

  /**
   * List globally installed MCP servers
   */
  async getApiMcpInstalled(
    options?: RequestOptions,
  ): Promise<operations.GetApiMcpInstalledResponseBody> {
    return unwrapAsync(mcpGetApiMcpInstalled(
      this,
      options,
    ));
  }

  /**
   * List installed MCP packages
   */
  async getApiMcpList(
    request?: operations.GetApiMcpListRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetApiMcpListResponse> {
    return unwrapAsync(mcpGetApiMcpList(
      this,
      request,
      options,
    ));
  }

  /**
   * Search MCP packages in marketplace
   */
  async getApiMcpSearch(
    request: operations.GetApiMcpSearchRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiMcpSearchResponse> {
    return unwrapAsync(mcpGetApiMcpSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get MCP package details
   */
  async getApiMcpShowName(
    request: operations.GetApiMcpShowNameRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiMcpShowNameResponse> {
    return unwrapAsync(mcpGetApiMcpShowName(
      this,
      request,
      options,
    ));
  }

  /**
   * Check tauri-plugin-mcp connection status
   */
  async getApiMcpTauriStatus(
    options?: RequestOptions,
  ): Promise<operations.GetApiMcpTauriStatusResponseBody> {
    return unwrapAsync(mcpGetApiMcpTauriStatus(
      this,
      options,
    ));
  }

  /**
   * Download MCP package to a directory
   */
  async postApiMcpDownload(
    request: operations.PostApiMcpDownloadRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostApiMcpDownloadResponse> {
    return unwrapAsync(mcpPostApiMcpDownload(
      this,
      request,
      options,
    ));
  }

  /**
   * Install an MCP package (supports name, name@version, gh:user/repo, ./path)
   */
  async postApiMcpInstall(
    request: operations.PostApiMcpInstallRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostApiMcpInstallResponse> {
    return unwrapAsync(mcpPostApiMcpInstall(
      this,
      request,
      options,
    ));
  }

  /**
   * Uninstall an MCP package
   */
  async postApiMcpUninstall(
    request: operations.PostApiMcpUninstallRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostApiMcpUninstallResponse> {
    return unwrapAsync(mcpPostApiMcpUninstall(
      this,
      request,
      options,
    ));
  }
}
