/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsCreate } from "../funcs/modelsCreate.js";
import { modelsCreateAlias } from "../funcs/modelsCreateAlias.js";
import { modelsDelete } from "../funcs/modelsDelete.js";
import { modelsDeleteAlias } from "../funcs/modelsDeleteAlias.js";
import { modelsDeleteConfig } from "../funcs/modelsDeleteConfig.js";
import { modelsDisable } from "../funcs/modelsDisable.js";
import { modelsEnable } from "../funcs/modelsEnable.js";
import { modelsGet } from "../funcs/modelsGet.js";
import { modelsGetConfig } from "../funcs/modelsGetConfig.js";
import { modelsGetDefault } from "../funcs/modelsGetDefault.js";
import { modelsList } from "../funcs/modelsList.js";
import { modelsListAliases } from "../funcs/modelsListAliases.js";
import { modelsReload } from "../funcs/modelsReload.js";
import { modelsUpdate } from "../funcs/modelsUpdate.js";
import { modelsUpdateConfig } from "../funcs/modelsUpdateConfig.js";
import { modelsUpdateDefault } from "../funcs/modelsUpdateDefault.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Models extends ClientSDK {
  async getDefault(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsGetDefault(
      this,
      options,
    ));
  }

  async updateDefault(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsUpdateDefault(
      this,
      options,
    ));
  }

  async listAliases(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsListAliases(
      this,
      options,
    ));
  }

  async createAlias(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsCreateAlias(
      this,
      options,
    ));
  }

  async deleteAlias(
    request: operations.ModelsDeleteAliasRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsDeleteAlias(
      this,
      request,
      options,
    ));
  }

  async reload(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsReload(
      this,
      options,
    ));
  }

  /**
   * List all models
   */
  async list(
    request?: operations.ModelsListRequest | undefined,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<operations.ModelsListResponseBody> {
    return unwrapAsync(modelsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new custom idea type
   */
  async create(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsCreate(
      this,
      options,
    ));
  }

  /**
   * Get a specific model by ID
   */
  async get(
    request: operations.ModelsGetRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<operations.ModelsGetResponse> {
    return unwrapAsync(modelsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a single idea by ID
   */
  async delete(
    request: operations.ModelsDeleteRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing idea type
   */
  async update(
    request: operations.ModelsUpdateRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Enable a skill for an agent
   */
  async enable(
    request: operations.ModelsEnableRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsEnable(
      this,
      request,
      options,
    ));
  }

  /**
   * Disable a skill for an agent
   */
  async disable(
    request: operations.ModelsDisableRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsDisable(
      this,
      request,
      options,
    ));
  }

  async getConfig(
    request: operations.ModelsGetConfigRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsGetConfig(
      this,
      request,
      options,
    ));
  }

  async updateConfig(
    request: operations.ModelsUpdateConfigRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsUpdateConfig(
      this,
      request,
      options,
    ));
  }

  async deleteConfig(
    request: operations.ModelsDeleteConfigRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(modelsDeleteConfig(
      this,
      request,
      options,
    ));
  }
}
