/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { patchesList } from "../funcs/patchesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "./types/fp.js";

export class Patches extends ClientSDK {
  /**
   * List pages in workspace
   */
  async list(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(patchesList(
      this,
      options,
    ));
  }
}
