/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { queueCreateClearHistory } from "../funcs/queueCreateClearHistory.js";
import { queueCreateEnqueueBatch } from "../funcs/queueCreateEnqueueBatch.js";
import { queueDeleteTask } from "../funcs/queueDeleteTask.js";
import { queueEnqueue } from "../funcs/queueEnqueue.js";
import { queueGetConfig } from "../funcs/queueGetConfig.js";
import { queueGetStatus } from "../funcs/queueGetStatus.js";
import { queueGetTask } from "../funcs/queueGetTask.js";
import { queueGetTaskRunning } from "../funcs/queueGetTaskRunning.js";
import { queueGetTaskStream } from "../funcs/queueGetTaskStream.js";
import { queueListTasks } from "../funcs/queueListTasks.js";
import { queueRetryTask } from "../funcs/queueRetryTask.js";
import { queueUpdateConfig } from "../funcs/queueUpdateConfig.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Queue extends ClientSDK {
  async enqueue(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueEnqueue(
      this,
      options,
    ));
  }

  async getStatus(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueGetStatus(
      this,
      options,
    ));
  }

  async listTasks(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueListTasks(
      this,
      options,
    ));
  }

  async getTaskRunning(
    request: operations.QueueGetTaskRunningRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueGetTaskRunning(
      this,
      request,
      options,
    ));
  }

  async getTask(
    request: operations.QueueGetTaskRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueGetTask(
      this,
      request,
      options,
    ));
  }

  async deleteTask(
    request: operations.QueueDeleteTaskRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueDeleteTask(
      this,
      request,
      options,
    ));
  }

  async getTaskStream(
    request: operations.QueueGetTaskStreamRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueGetTaskStream(
      this,
      request,
      options,
    ));
  }

  async retryTask(
    request: operations.QueueRetryTaskRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueRetryTask(
      this,
      request,
      options,
    ));
  }

  async getConfig(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueGetConfig(
      this,
      options,
    ));
  }

  async updateConfig(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueUpdateConfig(
      this,
      options,
    ));
  }

  async createEnqueueBatch(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueCreateEnqueueBatch(
      this,
      options,
    ));
  }

  async createClearHistory(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(queueCreateClearHistory(
      this,
      options,
    ));
  }
}
