/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tunnelGetStatus } from "../funcs/tunnelGetStatus.js";
import { tunnelRestart } from "../funcs/tunnelRestart.js";
import { tunnelStart } from "../funcs/tunnelStart.js";
import { tunnelStop } from "../funcs/tunnelStop.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "./types/fp.js";

export class Tunnel extends ClientSDK {
  async getStatus(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(tunnelGetStatus(
      this,
      options,
    ));
  }

  /**
   * Start a Vite preview server for a task
   */
  async start(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(tunnelStart(
      this,
      options,
    ));
  }

  /**
   * Stop a Vite preview server
   */
  async stop(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(tunnelStop(
      this,
      options,
    ));
  }

  async restart(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(tunnelRestart(
      this,
      options,
    ));
  }
}
