/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userCreateMeApiKey } from "../funcs/userCreateMeApiKey.js";
import { userDeleteMeApiKey } from "../funcs/userDeleteMeApiKey.js";
import { userGet } from "../funcs/userGet.js";
import { userListMe } from "../funcs/userListMe.js";
import { userListMeApiKeys } from "../funcs/userListMeApiKeys.js";
import { userListMeFavorites } from "../funcs/userListMeFavorites.js";
import { userUpdateMe } from "../funcs/userUpdateMe.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class User extends ClientSDK {
  async listMe(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(userListMe(
      this,
      options,
    ));
  }

  async updateMe(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(userUpdateMe(
      this,
      options,
    ));
  }

  async listMeFavorites(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(userListMeFavorites(
      this,
      options,
    ));
  }

  async listMeApiKeys(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(userListMeApiKeys(
      this,
      options,
    ));
  }

  async createMeApiKey(
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(userCreateMeApiKey(
      this,
      options,
    ));
  }

  async deleteMeApiKey(
    request: operations.UserDeleteMeApiKeyRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(userDeleteMeApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific task by ID
   */
  async get(
    request: operations.UserGetRequest,
    options?: Omit<RequestOptions, "extraBody">,
  ): Promise<void> {
    return unwrapAsync(userGet(
      this,
      request,
      options,
    ));
  }
}
