/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesGetApiWorkspaces } from "../funcs/workspacesGetApiWorkspaces.js";
import { workspacesGetApiWorkspacesDetect } from "../funcs/workspacesGetApiWorkspacesDetect.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Workspaces extends ClientSDK {
  /**
   * List all workspaces including the global workspace
   */
  async getApiWorkspaces(
    options?: RequestOptions,
  ): Promise<operations.GetApiWorkspacesResponseBody> {
    return unwrapAsync(workspacesGetApiWorkspaces(
      this,
      options,
    ));
  }

  /**
   * Detect folder status (.git and .viben directories)
   */
  async getApiWorkspacesDetect(
    request: operations.GetApiWorkspacesDetectRequest,
    options?: RequestOptions,
  ): Promise<operations.GetApiWorkspacesDetectResponse> {
    return unwrapAsync(workspacesGetApiWorkspacesDetect(
      this,
      request,
      options,
    ));
  }
}
