// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Binding type for agent/executor
 */
export type BindingType = "agent" | "executor";
