// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification mode for channel messages
 */
export type NotificationMode = "none" | "in_app" | "system" | "both";
