// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Webhook channel configuration
 */
export type WebhookConfig = { 
/**
 * Webhook URL
 */
url: string | null, 
/**
 * HTTP method (POST, PUT, etc.)
 */
method: string, 
/**
 * Custom headers
 */
headers: { [key in string]?: string }, };
