import {
  CodeIcon,
  FileIcon,
  ImageIcon,
  TableIcon,
  TextIcon,
  VideoIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  ListIcon,
  LinkIcon,
  QuoteIcon,
  MinusIcon,
  AtSignIcon,
  ListCollapseIcon,
  ListOrderedIcon,
  PanelLeftIcon,
  GridIcon,
  TableOfContentsIcon,
  RadicalIcon,
  CheckSquareIcon,
  SmileIcon,
  AlertCircleIcon,
  type LucideIcon,
} from "lucide-react";
import type { TFunction } from "i18next";

export const BLOCK_ICONS: Record<string, LucideIcon> = {
  Paragraph: TextIcon,
  HeadingOne: Heading1Icon,
  HeadingTwo: Heading2Icon,
  HeadingThree: Heading3Icon,
  Code: CodeIcon,
  CodeGroup: CodeIcon,
  Embed: LinkIcon,
  Image: ImageIcon,
  Video: VideoIcon,
  Blockquote: QuoteIcon,
  TodoList: CheckSquareIcon,
  BulletedList: ListIcon,
  NumberedList: ListOrderedIcon,
  Table: TableIcon,
  Callout: AlertCircleIcon,
  File: FileIcon,
  Divider: MinusIcon,
  Accordion: ListCollapseIcon,
  Steps: ListOrderedIcon,
  Tabs: PanelLeftIcon,
  Carousel: GridIcon,
  TableOfContents: TableOfContentsIcon,
  MathBlock: RadicalIcon,
  Emoji: SmileIcon,
  Mention: AtSignIcon,
};

export function createBlockCategories(t: TFunction): Record<string, string> {
  return {
    Paragraph: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    HeadingOne: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    HeadingTwo: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    HeadingThree: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    TodoList: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    BulletedList: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    NumberedList: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    Blockquote: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    Divider: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    Callout: t("editor.blockCategories.basicBlocks", "Basic blocks"),
    Image: t("editor.blockCategories.media", "Media"),
    Video: t("editor.blockCategories.media", "Media"),
    File: t("editor.blockCategories.media", "Media"),
    Embed: t("editor.blockCategories.media", "Media"),
    Emoji: t("editor.blockCategories.media", "Media"),
    Code: t("editor.blockCategories.code", "Code"),
    CodeGroup: t("editor.blockCategories.code", "Code"),
    Table: t("editor.blockCategories.advanced", "Advanced"),
    Accordion: t("editor.blockCategories.advanced", "Advanced"),
    Steps: t("editor.blockCategories.advanced", "Advanced"),
    Tabs: t("editor.blockCategories.advanced", "Advanced"),
    Carousel: t("editor.blockCategories.advanced", "Advanced"),
    TableOfContents: t("editor.blockCategories.advanced", "Advanced"),
    MathBlock: t("editor.blockCategories.advanced", "Advanced"),
    Mention: t("editor.blockCategories.inline", "Inline"),
  };
}

export function getCategoryOrder(t: TFunction): string[] {
  return [
    t("editor.blockCategories.basicBlocks", "Basic blocks"),
    t("editor.blockCategories.media", "Media"),
    t("editor.blockCategories.code", "Code"),
    t("editor.blockCategories.advanced", "Advanced"),
    t("editor.blockCategories.inline", "Inline"),
    t("editor.blockCategories.other", "Other"),
  ];
}

export const BLOCK_CATEGORIES: Record<string, string> = {
  Paragraph: "Basic blocks",
  HeadingOne: "Basic blocks",
  HeadingTwo: "Basic blocks",
  HeadingThree: "Basic blocks",
  TodoList: "Basic blocks",
  BulletedList: "Basic blocks",
  NumberedList: "Basic blocks",
  Blockquote: "Basic blocks",
  Divider: "Basic blocks",
  Callout: "Basic blocks",
  Image: "Media",
  Video: "Media",
  File: "Media",
  Embed: "Media",
  Emoji: "Media",
  Code: "Code",
  CodeGroup: "Code",
  Table: "Advanced",
  Accordion: "Advanced",
  Steps: "Advanced",
  Tabs: "Advanced",
  Carousel: "Advanced",
  TableOfContents: "Advanced",
  MathBlock: "Advanced",
  Mention: "Inline",
};

export const IS_MAC =
  typeof navigator !== "undefined" && /Mac/.test(navigator.userAgent);

export const MOD_KEY = IS_MAC ? "\u2318" : "Ctrl";
